### ISSUE TITLE
Reforged Eden 2

### ISSUE THREAD

**Issue by jamrev73** [RavienGaming/Reforged-Eden-2#101]
### Reforged Eden 2 Build Number

RE 2 Build 10

### Game mode

Single Player

### Tested in vanilla

Issue does not happen in vanilla

### Description of issue

I was on Akua leaving the Talon village for a side quest (making 10 regulators for the farmer) I hwas in my HV which was built from scratch I hit a tree i began spinning then found myself in space. Screen shot taken FYI notice the speed in the upper right corner  taken in game I was traveling.  This is the EGS saved content screen shot.  https://steamcommunity.com/sharedfiles/filedetails/?id=3263891135 I started a new game to see if it will happen again. Nothing yet.

### POI Name

Talon Settlement  (main quest)

### Playfield Name

Akua starter planet

### Playfield Class

Temperate starter

### Star Name

Alpha

### Star Class

Alpha [Gstarting system]

### Mission Name

Farmer quest 10 regulators for his crops

### Mission Objective

10 regulators

### Game Seed

123456789   I know it's the same combination as my luggage...

**Comment by RavienGaming** [comment]
This issue has already been reported here: #77 

This is likely a game bug and will need to be reproduced and reported using a vanilla save game.
When reproducing a game bug in a vanilla save, make sure you are using the same mode _(singleplayer/co-op/dedicated multiplayer, survival/creative)_ as what you were using when the issue happened in the scenario.
To see a list of known game bugs or to report a new one please see: https://empyriononline.com/forums/bugs.24/
