### ISSUE TITLE
Stuck on Loading Screen

### ISSUE THREAD

**Issue by Keoke-san** [RavienGaming/Reforged-Eden-2#102]
### Reforged Eden 2 Build Number

v1.11.6 4471

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

I go to single player, scenario, RE2 Beta, Get my settings how I want them, hit join, and I get to the planetary blue loading screen, I will then be there for a brief moment, and get the RE2 loading screen discussing how it is still in beta. Then after about 15 seconds or so, i go back to the planetary sunrise loading screen and nothing happens, and i'm stuck there. I can't close the game unless I alt+f4. 

I have unsubbed and the subscribed again and the same thing happens again.

**Comment by Keoke-san** [comment]
Update on this, when I load with out changing any settings it works fine.

**Comment by RavienGaming** [comment]
Duplicate issue. Please see issue #19 for two workarounds.
