### ISSUE TITLE
Kenex Station Misplaced Quest Marker

### ISSUE THREAD

**Issue by Kainne00** [RavienGaming/Reforged-Eden-2#103]
### Reforged Eden 2 Build Number

10

### Game mode

Single Player, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

The "[Find the Coms Chief]" section of Message Interrupted, in The Cruel Stars quest chain places a map marker for the comms chief approximately 64m below and to the side of the player when completing discussion with the PoLSec operator.

This waypoint is outside on the cargo dock. The comms chief is 10 feet away from the player when they are told to locate him.  It updates normally IF the player knows where to go. but the waypoint location is wrong in both dedicated server / MP and single player.

### POI Name

Kenex Station

### Playfield Name

Omicron Orbit

### Mission Name

The Cruel Stars / Message Interrupted

### Mission Objective

Message Interrupted / [Find the Coms Chief]

**Comment by Kainne00** [comment]
Follow On:

The map marker for the comms chief is also in the wrong palce for the return to the comms chief section of this same quest.
![image](https://github.com/RavienGaming/Reforged-Eden-2/assets/168397912/f66dac13-0116-48c0-8ec4-7f98bdde818a)

**Comment by VermillionX** [comment]
Fixed for next update.
Looks like the Coms Chief block lost his unique name.
