### ISSUE TITLE
Gerald's Quest line on UCH ships. Multiplayer.

### ISSUE THREAD

**Issue by ausmarvin** [RavienGaming/Reforged-Eden-2#104]
### Reforged Eden 2 Build Number

First beta weeked

### Game mode

Co-op, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Geralds corrupted logs quest.  Multiplayer
Got keys, unlocked doors (Doors were shut and needed key to open) but only one of the 3 chest had the a Partial log in it. 
Unable to complete. 
Cant pick up Keys again to open other doors either so cant wait till the reset it appears.

### POI Name

UNCH Odyssey

### Playfield Name

UNCH Odyssey

### Star Name

Delta was the system I was in

### Star Class

Starter Delta

### Mission Name

No listed quest ot mission in list - Gerlds logs

### Mission Objective

Get 3 "Gerald's partially corrupted Log's:

### Game Seed

Unknown

**Comment by RavienGaming** [comment]
You can't get the other logs on the same ship. You need to visit another research vessel to get the next log.

So just to double check you have one log right now, after visiting one ship? If so that is correct.

**Comment by ausmarvin** [comment]
I travelled to UCHN Odyssey, I collected the key for Access panel 12-A, I then went to Alpha and Beta UCHN ships and collected keys for Access panel 12-B and 12-C.
I then went back to Delta door Access Panel 12-A was shut. I opened that door and the Key for this door disappeared. When I went up stairs and checked the box's that was nothing there. 
I went to Access panel 12-B which was also shut.. opened the door and the key was removed from my inventory. Again I went up the ladder and checked the box and fridge, both were empty.
I then went to access 12-c this was open. I checked the box again it was empty.
I then went to Beta UCHN ship and found the door to Access 12-C and it was shut. So I opened it and the key was removed from inventory. I checked the boxes there and found one of the corrupted logs. 
I went to the doors 12-A and 12-B both where shut so I could not open them. 
I am unable to get any more access keys to open the doors and still only have 1 corrupted logs.
In RE1 was only able to get 1 key from each ship, but I was able to open all three access points on one ship and get all three logs from one ship. Has this change?
Either way, the keys have been consumed and now I have no way of opening another door on another ship if I can only get one log per ship.

**Comment by RavienGaming** [comment]
Thanks. I changed it for next update so you obtain the logs via dialogue so now it won't be empty if someone else took the log before you. However if you lose the door keys you still won't be able to get a new key.

**Comment by Xerkus** [comment]
This change broke the quest.
In a new game started with build 11 gerald's pda does nothing when trying to interact with it. Tried Alpha system with access A then Delta system with access B.

**Comment by RavienGaming** [comment]
Thanks. Fixed (again) for next update.

**Comment by MabDeno** [comment]
Just attempted this quest in Build 11. The second data pad on the floor couldnt be interacted with. If you hit F without your jetpack on it would just centre your vision to horizontal with no dialogue.

**Comment by RavienGaming** [comment]
> Just attempted this quest in Build 11. The second data pad on the floor couldnt be interacted with. If you hit F without your jetpack on it would just centre your vision to horizontal with no dialogue.

Hi, the scenario is currently on build 13. Please try again after updating the scenario and then post back if it's still not working.
