### ISSUE TITLE
SV Constructor - Construction window shows it as a HOVER CONSTRUCTOR

### ISSUE THREAD

**Issue by ausmarvin** [RavienGaming/Reforged-Eden-2#105]
### Reforged Eden 2 Build Number

Beta V1.16.6 4471 09-06:48

### Game mode

Co-op, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

SV Constructor - in construction window is called a Hover Constructor in the top left corner
![SVConstructorName](https://github.com/RavienGaming/Reforged-Eden-2/assets/22611778/d8484461-6ebf-4e2a-8c32-c96dcdff463e)

### POI Name

NA

### Playfield Name

NA

### Playfield Class

NA

### Star Name

NA

### Star Class

NA

### Mission Name

NA

### Mission Objective

NA

### Game Seed

NA

**Comment by RavienGaming** [comment]
This is a limitation of the game and cannot be fixed within the scenario. That part of the UI is hard coded and doesn't appear in the localization that I can see.
