### ISSUE TITLE
Typo in loading screen

### ISSUE THREAD

**Issue by Mario-Radinovic** [RavienGaming/Reforged-Eden-2#106]
### Reforged Eden 2 Build Number

RE2 Build 10

### Game mode

Survival, Creative, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

![20240609101639_1](https://github.com/RavienGaming/Reforged-Eden-2/assets/65545773/eedaa2be-af47-43f9-a0ee-835366339e78)

"h" is missing I think

**Comment by RavienGaming** [comment]
Thanks fixed for next update.
