### ISSUE TITLE
Light Automatic Turrets (CV) can only be upgraded if the chosen variant is Cannon

### ISSUE THREAD

**Issue by danielsolaro** [RavienGaming/Reforged-Eden-2#107]
### Reforged Eden 2 Build Number

10

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Light Automatic Turrets can't be upgraded if placed as gatling variant, retrieving it and placing as cannon allows to upgrade.

**Comment by VermillionX** [comment]
Fixed for next update.
Also included Light Missile Turret.
