### ISSUE TITLE
Description of Large Shield Boosters has inconsistent power consumption info

### ISSUE THREAD

**Issue by danielsolaro** [RavienGaming/Reforged-Eden-2#108]
### Reforged Eden 2 Build Number

10

### Game mode

Survival, Co-op, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

The block itself says 20kw/h, when choosing which variant both say 16kw/h consumption, which is consistent with the control panel information once block is placed.
![20240609102119_1](https://github.com/RavienGaming/Reforged-Eden-2/assets/8516353/4b05d526-99ff-45b8-99c3-89e3ee3f6b21)
![20240609102134_1](https://github.com/RavienGaming/Reforged-Eden-2/assets/8516353/5a833975-576d-47d5-8d42-1d9f3686bfaa)
![20240609102235_1](https://github.com/RavienGaming/Reforged-Eden-2/assets/8516353/68430a36-9842-4270-ab78-ff65727fb2b7)

**Comment by VermillionX** [comment]
Fixed for next update.
