### ISSUE TITLE
Using DI on manual medium railgun (CV) causes crash loop (divided by zero blablabla)

### ISSUE THREAD

**Issue by danielsolaro** [RavienGaming/Reforged-Eden-2#110]
### Reforged Eden 2 Build Number

10

### Game mode

Creative

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Took a while to find what was causing me creative crashes, can't use the "di" command with manual medium railgun (CV)
![20240609212505_1](https://github.com/RavienGaming/Reforged-Eden-2/assets/8516353/007ab193-ccbd-42db-9678-06aea9306d6b)
Also noticed some railguns had their names disappear from panel despite being the same variant. It becomes just the icon with empty space. Not all of them had this, tho.

**Comment by RavienGaming** [comment]
This issue has already been reported here: #11

**Comment by danielsolaro** [comment]
shield wasn't on but you did give me a tip. Turns out I  had removed the big shield capacitors yesterday resulting in no shield (was the shield generator and a bunch of  chargers). Adding a big capacitor back fixed it. Removed capacitor it crashed again.
Also noticed I don't need to look at the railgun specifically but any part of this poi. So I guess di makes the game check shield of a vessel and its percentage or something relative to the shield max, which causes this issue.

Makes sense? :P Gonna test on vanilla and report if it happens there.

**Comment by danielsolaro** [comment]
No shield boosters in vanilla, rip.
