### ISSUE TITLE
Pumping Station [POL] not sealed on Lava planet

### ISSUE THREAD

**Issue by StHotPants** [RavienGaming/Reforged-Eden-2#112]
### Reforged Eden 2 Build Number

RE2 Beta Build 10

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Went to a [POL] Pumping Station on a Lava planet in my SV. Entered in thru the shutter doors for the SV landing pad. When I got out the shutter doors had closed but internal temperature in the POI was still 585C. 

### POI Name

Pumping Station

### Playfield Class

Lava

**Comment by RavienGaming** [comment]
One of the outdated RE1 or vanilla POI groups that will need to be updated.

**Comment by RavienGaming** [comment]
I removed them from spawning for the next update until they can be updated or rebuilt.
