### ISSUE TITLE
[Talon] Crawler spawned on Frozen Inferno in Polaris Territory

### ISSUE THREAD

**Issue by Mario-Radinovic** [RavienGaming/Reforged-Eden-2#114]
### Reforged Eden 2 Build Number

RE2 Build 10

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Frozen Inferno planet (Glacier Snow biome) spawns [Talon] Crawler NPC in the wild without any talon POI present on the planet.

**Comment by RavienGaming** [comment]
Thanks. Fixed for next update.
