### ISSUE TITLE
Cooling Boosters Show No Mass Value

### ISSUE THREAD

**Issue by Ipurgepeople** [RavienGaming/Reforged-Eden-2#118]
### Reforged Eden 2 Build Number

Build 10

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

There is no Mass value on the Cooling Booster or Advanced Cooling Booster tooltips.

**Comment by VermillionX** [comment]
Fixed in next update.
The display for mass was set to false for some reason.
