### ISSUE TITLE
Drifting Markers

### ISSUE THREAD

**Issue by Ipurgepeople** [RavienGaming/Reforged-Eden-2#119]
### Reforged Eden 2 Build Number

Build 10

### Game mode

Survival, Single Player

### Tested in vanilla

Issue does not happen in vanilla

### Description of issue

On planetary playfields (Planets, moons), placing a marker via right-click, and editing the marker (renaming it, changing icon, etc.) allows the marker to drift off course, almost like the rotation of the planet is taking the marker with it.

If you place a marker quickly (<1 second) the issue doesn't typically occur. However, even when attempting to edit the marker after the fact it can still drift.

Awkwardly, while attempting to diagnose the issue while writing up this report, I went into a vanilla game and checked it there (It didn't happen), and when I went back to RE2, I have now been unable to reproduce it since.

**Comment by RavienGaming** [comment]
This is likely a game bug and will need to be reproduced and reported using a vanilla save game. (I know you already tried)
When reproducing a game bug in a vanilla save, make sure you are using the same mode _(singleplayer/co-op/dedicated multiplayer, survival/creative)_ as what you were using when the issue happened in the scenario.
To see a list of known game bugs or to report a new one please see: https://empyriononline.com/forums/bugs.24/
