### ISSUE TITLE
EMP Cruise Missile deals far less shield damage than normal Cruise

### ISSUE THREAD

**Issue by danielsolaro** [RavienGaming/Reforged-Eden-2#120]
### Reforged Eden 2 Build Number

10

### Game mode

Creative

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Decided to test these in a more controlled scenario given it felt weak in survival play. Went creative, set a ship with 6x cruise missiles launchers, ammo blablabla and turned them on at the same, with the intention of checking the damage per volley against a tovera on 100% shield. Both normal and EMP cruises have same RPM.
One volley of:
6x normal cruise missiles = tovera at 93% shield
![20240611044555_1](https://github.com/RavienGaming/Reforged-Eden-2/assets/8516353/1ebbff8c-524e-4db2-862e-f3c7e77918a4)

6x EMP cruise missiles = tovera at 97% shield (sometimes shows 96%, but in ten volleys it never dealt more than 4%)
![20240611044658_1](https://github.com/RavienGaming/Reforged-Eden-2/assets/8516353/3e74d3e6-3a70-4262-a1a6-deaa7e7e3382)

EMP deals around half shield damage than normal cruise.
Also description damage values don't check out with the described shield damage. Shield damage = 15k normal, 60k EMP. Damage numbers are 15k no bonus and 7.5k 100% bonus (which results in the same?).
![20240611045945_1](https://github.com/RavienGaming/Reforged-Eden-2/assets/8516353/1bd7e69c-0ad2-4ed5-9e8e-f1cb9c45b3f7)
![20240611045947_1](https://github.com/RavienGaming/Reforged-Eden-2/assets/8516353/817c885d-392f-4107-942b-e8eb5cc7bd6b)

Thank you.

**Comment by danielsolaro** [comment]
I'm not 100% sure I understood this correctly but it seems the EMP missiles are using the normal damage multiplier setup, which is 8 times weaker versus shields (0.25 versus 2.0). Because EMP has half the impact damage, and per description should deal 4x the shield damage of the base cruise, thats a 8x multiplier missing. Fits too perfectly 😶
![itemconfig](https://github.com/RavienGaming/Reforged-Eden-2/assets/8516353/ff507d4f-f7e1-4ec5-8db9-dafd51ce31a4)
![multiplierconfig](https://github.com/RavienGaming/Reforged-Eden-2/assets/8516353/165c7cfe-5126-466c-903e-ab40493e8580)

**Comment by RavienGaming** [comment]
Thanks fixed for next update.
