### ISSUE TITLE
Cruise Missile Turrets deal almost zero dmg to surrounding blocks when destroyed

### ISSUE THREAD

**Issue by danielsolaro** [RavienGaming/Reforged-Eden-2#122]
### Reforged Eden 2 Build Number

10

### Game mode

Creative

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Both base and EMP cruise turrets (heavy) are barely hurting the blocks around when they get destroyed,  stuff like 10~80 damage while a medium missile causes 5-6k. Even a light automatic turret causes 500+.
Medium Missile Turret exploding:
![20240611230055_1](https://github.com/RavienGaming/Reforged-Eden-2/assets/8516353/c2b34740-9c30-485d-8b21-ea251deb691f)
![20240611230106_1](https://github.com/RavienGaming/Reforged-Eden-2/assets/8516353/decdc11c-650c-413a-9e5f-18d907ba8072)
Cruise Missile Launcher exploding:
![20240611230123_1](https://github.com/RavienGaming/Reforged-Eden-2/assets/8516353/03bc145b-6e94-48cd-9b23-2503af7f41e0)

**Comment by RavienGaming** [comment]
Thanks. I will make sure they get more explodium added.

**Comment by RavienGaming** [comment]
Fixed for next update.
