### ISSUE TITLE
Deconstructing auto mining device (basic) gives wrong components

### ISSUE THREAD

**Issue by Mario-Radinovic** [RavienGaming/Reforged-Eden-2#123]
### Reforged Eden 2 Build Number

RE2 Build 10

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

When Auto Mining Device (basic) is deconstructed it gives back materials that are not related to materials used to construct it

**Comment by RavienGaming** [comment]
It's deconstructing the auto miner core.
