### ISSUE TITLE
Cosmozoans Spawn Hostile in Eden Legacy Fields

### ISSUE THREAD

**Issue by Kainne00** [RavienGaming/Reforged-Eden-2#126]
### Reforged Eden 2 Build Number

10

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

In Eden Asteroid Fields - the pink ones with legacy inside of them, the "Cosmozoan" deco CVs now have names like a CV, show as <Heat Signature> until the name resolves.  They display the eye and ! as if they were hostile CVs and are factioned pink with the rest of the Legacy Asteroid field.

This also causes them to be subject to player turret targeting, increasing difficulty in Legacy Asteroid fields, as turrets will fire on them instead of actual hostile OPVs.

This seems unintended, as the blue ones in ice fields in RE1 did not have named/signatures and did not draw weapons fire.

### Error code from console or log (Optional)

![image](https://github.com/RavienGaming/Reforged-Eden-2/assets/168397912/c21ac1d5-00a6-46b2-b04a-1ea3d2e60a6b)

### Playfield Class

Eden Asteroid Field(s)

### Star Class

Q23

**Comment by RavienGaming** [comment]
Fixed next update, though this may make them no longer path correctly.
