### ISSUE TITLE
Colonist scrapyard boarding ramp opens from outside, but not inside.

### ISSUE THREAD

**Issue by Codock** [RavienGaming/Reforged-Eden-2#127]
### Reforged Eden 2 Build Number

Beta build 10

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

![image](https://github.com/RavienGaming/Reforged-Eden-2/assets/39315792/d710d0ff-63b4-423b-b807-61c2e1098522)

Was looking over the ship and the boarding ramp underneath opened up, so I wandered inside. Boarding ramp closed and I can't find a way to get it to open from the inside.

### Error code from console or log (Optional)

None

### POI Name

Colonist scrapyard

### Playfield Name

Ishul

### Playfield Class

Colonist Scrapyard

### Star Name

Iblomustora

### Star Class

K

### Mission Name

None

### Mission Objective

None

### Game Seed

?

**Comment by RavienGaming** [comment]
Thanks. Fixed for next update.
