### ISSUE TITLE
Missing Cargo Dialog says you get reputation points when that is no longer the case

### ISSUE THREAD

**Issue by Ishantil** [RavienGaming/Reforged-Eden-2#128]
### Reforged Eden 2 Build Number

Build 10

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

The missing cargo dialog states that you get 100 reputation points when turning in packages, but this is no longer the case.

**Comment by RavienGaming** [comment]
Did you check your reputation level in the reputation window before and after?

**Comment by Ishantil** [comment]
Normally don't you get a notification about reputation?

--------------------------------
Matthew D. Cleveland

**Comment by RavienGaming** [comment]
There is no notification for reputation if given using dialogue. See #74

**Comment by RavienGaming** [comment]
I will close this ticket, but if you notice your actual reputation level not changing in the reputation overview please submit a new issue!

**Comment by Ishantil** [comment]
I will double check this for you and open a new ticket if it's wrong.
Sorry for the confusion.

--------------------------------
Matthew D. Cleveland

**Comment by Ishantil** [comment]
Ravien, I confirmed that the Missing Cargo is indeed working correctly.  Sorry for the extra bug report when it was not necessary.
