### ISSUE TITLE
Unable to complete Survey Galaxy (Exotic Systems) as only 1 R class system and this is in progenitor space

### ISSUE THREAD

**Issue by trevornicholls** [RavienGaming/Reforged-Eden-2#130]
### Reforged Eden 2 Build Number

Build 10

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

When doing the Survey Galaxy mission the Exotic Systems section you are asked to visit 3 R class systems, searching only brings up 1 system, this being the dyson sphere system in progenitor space. 
This may be intenional or a result of the R class systems being renamed to R-Drone. Going to one of these systems does not trigger a probe request.
This is the Broken Eden 2 server hosted by Spanj

### Star Class

R

### Mission Name

Survey Galaxy (Exotic Systems) 

### Mission Objective

Scan 3 x R class systems

### Game Seed

16156

**Comment by RavienGaming** [comment]
Thanks fixed for next update but the fix will only apply to new save games.
