### ISSUE TITLE
Science Station says it needs to be locked in the tech tree, but does not exist there

### ISSUE THREAD

**Issue by Nothemal** [RavienGaming/Reforged-Eden-2#131]
### Reforged Eden 2 Build Number

10

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Can not build a science station. In advanced constructor it says it needs to be unlocked in the tech tree. However, it does not exist in the tech tree.

**Comment by RavienGaming** [comment]
Assuming you already restarted your game all the way back to windows desktop?

This is likely a game bug and will need to be reproduced and reported using a vanilla save game.
When reproducing a game bug in a vanilla save, make sure you are using the same mode _(singleplayer/co-op/dedicated multiplayer, survival/creative)_ as what you were using when the issue happened in the scenario.
To see a list of known game bugs or to report a new one please see: https://empyriononline.com/forums/bugs.24/

**Comment by Nothemal** [comment]
Well, yes, I had restarted the game before reporting. Several times all the way out. However, going back in today, its working fine. So, yep, game bug. No way I am going to be able to reproduce this though.
