### ISSUE TITLE
Colonists Light Freighter chains to generators when destroying B Thrusters

### ISSUE THREAD

**Issue by Mario-Radinovic** [RavienGaming/Reforged-Eden-2#132]
### Reforged Eden 2 Build Number

RE2 Build 10

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

I attacked Colonists Light Freighter with SV using Light Laser manual guns and targeted back thrusters. After destroying one of thrusters on right back side (when facing its back side) it chained and destroyed all of the generators making ransom not possible

**Comment by RavienGaming** [comment]
Thanks. Fixed for next update.
