### ISSUE TITLE
Placeholder Pirate POIs do not remove terrain

### ISSUE THREAD

**Issue by Nothemal** [RavienGaming/Reforged-Eden-2#134]
### Reforged Eden 2 Build Number

10

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

The Pirate placeholder POI are not removing terrain, so any underground area is pretty much unplayable.  Seen on several different worlds and at least Placeholder RE2PirateMain (which looks like a LOT of fun) and Placeholder R2PirateAuxT2, which are the only Pirate POIs with under ground areas that I have seen so far. 
![BE2-B1_2024-06-16_12-36-14](https://github.com/RavienGaming/Reforged-Eden-2/assets/126076224/6bb41246-0495-4b46-b1cc-4f141f4272fe)
![BE2-B1_2024-06-13_17-37-56](https://github.com/RavienGaming/Reforged-Eden-2/assets/126076224/a13486b7-dc0f-4bfe-9eed-224e51089a6f)

**Comment by RavienGaming** [comment]
Those POIs are only there for placement previewing. In the future they will be completely replaced with actual updated or new POIs. You shouldn't really run these or anything, the only reason they exist is because there needs to be some kind of POI in the POI spawn group.
