### ISSUE TITLE
Tech Tree_CV Turrets: Need to show Range

### ISSUE THREAD

**Issue by Omegaflux** [RavienGaming/Reforged-Eden-2#135]
### Reforged Eden 2 Build Number

11

### Game mode

Survival, Co-op

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Any way to squeeze at least the Range and Damage onto the tech tree or constructor tips for CV Turrets? I know the boxes getting too big but seems important info before deciding to craft it. Maybe can replace the "unlock Cost and level since that is redundant info you already see in tech tree. If anything, Range is what I was looking for.
![Range for Turrets](https://github.com/RavienGaming/Reforged-Eden-2/assets/173006063/7603385c-b323-4a9e-b3a1-b696cbd10dc9)

**Comment by VermillionX** [comment]
No.
You're showing the parent blocks, which include laser AND plasma turrets. Which have different ranges and a second set of ranges that are even more different between planet and space.

**Comment by Omegaflux** [comment]
I am aware I am showing the only Turret tooltips we have and they are the parent block; but got it; your answer is a flat No, we do not get to see the breakdown and ranges of the Child Turrets in the Tech Tree or constructor in survival in order to make an educated decision before we craft it.  So its use creative or craft it first then look at stats, unless I am missing another option.
