### ISSUE TITLE
Zirax Mechs on lava planet surface in middle of PoL Space?

### ISSUE THREAD

**Issue by Omegaflux** [RavienGaming/Reforged-Eden-2#136]
### Reforged Eden 2 Build Number

11

### Game mode

Survival, Co-op

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Are these intended to be here? Multiple squads of Zirax Mechs on surface of lava planet in middle of PoL space territory. I verified this was not anywhere near the edge of PoL Space.
![Zirax Mechs PoL Space](https://github.com/RavienGaming/Reforged-Eden-2/assets/173006063/137eae4f-1942-4c91-bd28-66ef143f7e0e)

### Playfield Name

Dagal

### Playfield Class

Crusted Lava

### Star Name

Banshamara

### Star Class

K5

**Comment by RavienGaming** [comment]
Thanks. Fixed for next update.
