### ISSUE TITLE
Long Heavy Barrel, weapon mod clones after every death.

### ISSUE THREAD

**Issue by GoldenFinch91** [RavienGaming/Reforged-Eden-2#138]
### Reforged Eden 2 Build Number

Build 10

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

After dying on Broken Eden 2 server the Long Heavy Barrel clones itself.
Starter planet Ningues.

### Playfield Name

Ningues

**Comment by RavienGaming** [comment]
This is likely a game bug and will need to be reproduced and reported using a vanilla save game.
When reproducing a game bug in a vanilla save, make sure you are using the same mode _(singleplayer/co-op/dedicated multiplayer, survival/creative)_ as what you were using when the issue happened in the scenario.
To see a list of known game bugs or to report a new one please see: https://empyriononline.com/forums/bugs.24/
