### ISSUE TITLE
Unlocking Trader faction traders does not increase rep with Trader Faction

### ISSUE THREAD

**Issue by Nothemal** [RavienGaming/Reforged-Eden-2#139]
### Reforged Eden 2 Build Number

10

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Unlocking trader for Trader Faction on Trader POIs in Trader space does not increase rep with Trader faction.  Tested on several different POIs in Trader space.

**Comment by RavienGaming** [comment]
Did you check the faction screen to verify if your reputation was increased or not?

**Comment by Nothemal** [comment]
Absolutely. Checked after each of about six different traders, both doing a supply request and unlocking them.

**Comment by RavienGaming** [comment]
Thanks do you remember the names of the traders you had tried? We'll look into this but that would help. Or at least the POI names.

**Comment by Nothemal** [comment]
All the ones on Trade Station Olivine is what I remember, but I will go back and get some more names for you later today.

**Comment by Nothemal** [comment]
On Spanj's server:
Eurynelin - Aoaelydi Moon - Trade Station Tourmaline - ServantCorp Outfitters II (Looking for work) - no rep
Eurynelin - Aoaelydi Moon - Trade Station Tourmaline - InterWeapon Heavy (Looking for work) - no rep
Eurynelin - Aoaelydi Moon - Trade Station Tourmaline - MarketCafe - Didn't unlock (Do Blue Peppers still exist???)
Eurynelin - Aoaelydi Moon - Trade Station Tourmaline - Grimgar's Garden (Looking for work) - no rep
Eurynelin - Aoaelydi Moon - Trade Station Tourmaline - Ok Medical (Looking for work) - no rep
Eurynelin - ABOU I - Placeholder R2TraderAuxT1 - Flight Mechanic - REP!!
Eurynelin - ABOU I - Placeholder R2TraderMain - Flight Mechanic - REP!! (amount double the dialog maybe?)
Eurynelin - Marelzae Sector - Trade Station Citrine - M.A. Corp Advanced (looking for work) - no rep
Eurynelin - Asmiman - Space Colony - Settlement - REP!! (only did the first job)

So, a little hit and miss. Looks like no rep for the older "looking for work" jobs and only the newer traders maybe?

I would like to have tried more "locked" traders like the Flight Mechanic, but there aren't that many right now.

**Comment by Nothemal** [comment]
FYI, along with Blue Peppers, leather is also almost or not existent.  Missing the Talon traders currently it looks like.

**Comment by VermillionX** [comment]
Trade station traders that operate regular stores do not, nor have they ever given rep. They don't even say they give rep either, so there's nothing to report.
This is because they are a storeclerk, not a representative of a company or faction and are used interchangeably on multiple different factions' POIs. You do not "unlock" their trades like you do with the mechanic or factories. They are always available.

Settlements and Flight Mechanics do give rep since they're not storeclerks.

**Comment by Nothemal** [comment]
Understood. Not a lot of opportunity to increase rep with the only faction that has gameplay requiring it, but maybe more will come later as the faction is developed again.
