### ISSUE TITLE
Not enough sources of Advance Upgrade Kits

### ISSUE THREAD

**Issue by Nothemal** [RavienGaming/Reforged-Eden-2#140]
### Reforged Eden 2 Build Number

10

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Advance Upgrade Kits (AUK) are a very limiting resource for progression.  There are not really any good ways to obtain them besides purchase from vender (granted, lots of options there). None of the early game accessible ships and POIs give AUKs (no Zirax ships through Periot, none of the space POIs that replaced Luarks). AUKs were why players famed Luarks in the first place. 

Recommend, add a couple turrets the savage  with AUKs to Solar Stations or Orbital Stations (Zirax) and add 2x turrets with them to Sunats or Periots or both.

**Comment by RavienGaming** [comment]
Hi GitHub is to be used for reporting bugs. If you have general feedback on balancing etc please post that on the workshop or in a discord channel that we're in. Thank you!
