### ISSUE TITLE
Grimgar's Garden Vendor has stock but unable to sell Dapibus Sprout(s)

### ISSUE THREAD

**Issue by StHotPants** [RavienGaming/Reforged-Eden-2#141]
### Reforged Eden 2 Build Number

RE2 Beta Build 10

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Grimgar's Garden vendor has stock of Dapibus Sprout seeds but has no Sell or Buy amount listed so is unable to complete transaction.

![image](https://github.com/RavienGaming/Reforged-Eden-2/assets/169509491/5346d673-1df5-4d85-96a9-898f97211ae0)

### POI Name

[POL] Trade Station Iota

**Comment by VermillionX** [comment]
I can't find any problem in the trader config for this. Is it just those seeds or the other ones as well?

**Comment by Nothemal** [comment]
saw this as well. It was on the list, but didn't have a buy or sell price.

**Comment by StHotPants** [comment]
> I can't find any problem in the trader config for this. Is it just those seeds or the other ones as well?

It was only these particular seeds. All the other seeds in the list had quantities and buy / sell values to enable purchasing

**Comment by StHotPants** [comment]
![image](https://github.com/RavienGaming/Reforged-Eden-2/assets/169509491/eae3c1a6-7180-4a87-bcea-63db1ac70294)

**Comment by VermillionX** [comment]
I know what the problem is. It's the sprout itself, not the trader.
Fixed for next update.
