### ISSUE TITLE
Nursery Hive Guardians have shields turned off

### ISSUE THREAD

**Issue by michael-harris** [RavienGaming/Reforged-Eden-2#142]
### Reforged Eden 2 Build Number

11

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Shields are turned off on Hive Nurserys.  GM IV and I can turn them back on.

**Comment by RavienGaming** [comment]
Thanks. Fixed for next update.
