### ISSUE TITLE
Locked out Chapter 6 Main Story

### ISSUE THREAD

**Issue by CrazyGamer9191** [RavienGaming/Reforged-Eden-2#143]
### Reforged Eden 2 Build Number

11

### Game mode

Co-op

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

During Chapter 6 of the main campaign on the Akura Moon Zerax comm base. I opened the door to the room with the fire and was trying to access the rectors to shut down locks but I died. I respawned in my ship with the access rector quest still needing to be completed. However the door to the fire room is locked and the way I opened it the first time no longer works. I tried to force complete but it will not let me. I don't do any damage to blocks with any type of damage

### POI Name

Comm Base on Akura's moon

### Playfield Name

Akua Moon

### Playfield Class

Starter Moon

### Star Name

Alpha

### Star Class

Gstartersystem

### Mission Name

Hostile Apparatus

### Mission Objective

Access the Reactor Controls

### Game Seed

814453

**Comment by VermillionX** [comment]
What is rectors?

**Comment by CrazyGamer9191** [comment]
> What is rectors?

Reactor I forgot the a letter

**Comment by VermillionX** [comment]
The reactor is in no proximity in the quest to the incinerator.
If you are up to the reactor without clearing the incinerator (which is part of the mission), then you forcibly skipped the mission objectives without completing them.

You're likely not locked out, you're just doing the wrong things. You should under no circumstances use the manual completion function unless the target is to kill something and it's gone missing or been killed by someone/something else.

**Comment by CrazyGamer9191** [comment]
I have never force completed a quest yet in RE2 never had to. I cleared the incinerator room after flipping switch in vent. First door opened I did some talking on a console, lied my way through other door in ininerator. killed folks then did next console and it shut first door to incinerator. It told me to clear area and go to reactors I got there and bleed out and die while talking with reactor console. Don't know if any of that helps

**Comment by VermillionX** [comment]
The door through the incinerator is opened and closed by a motion sensor that is activated by the dialogue from the console in the incinerator. It can only be activated once and once it has been activated, the sensor will remain active.
However, the sensor only detects 1 block on each side of the door. You will need to walk right up to the door for it to open. You cannot open it with F, even if it says ACCESS DENIED, you just need to physically walk up and touch the door.
If that still doesn't work, then it would be a game bug with signal logic. If you're in MP, it's possible for that to happen.

**Comment by CrazyGamer9191** [comment]
I'll go back there tomorrow I got to find some ores first. Thank you

**Comment by VermillionX** [comment]
Wait, it says you're doing this in Co-op. Were you playing through the mission with another player?
If they talked to the console that activates the sensor, it may be possible that it re-flagged the sensor and turned it off when they did the mission.

**Comment by CrazyGamer9191** [comment]
I was playing with my son, he isn't doing any of the quest this time just looting and shooting for him. I got side track this morning building a new CV and didn't even load that save. I think it was something on my end I am having a hard time understanding everything. I'm new to the game only 100 hours I didn't like vanilla thought I try RE2 before I quit and so far you fixed most of my vanilla game issues.

**Comment by R173YM0N** [comment]
im actually stuck trying to get the control room door to open

**Comment by VermillionX** [comment]
The next update to RE2 will include the addition of a computer console that will allow you to manually toggle the state of the Incinerator and the doors if you get stuck.
It will not function if you are not up to the part where it gets stuck though.

There are multiple control rooms, so you'll have to be more specific.
