### ISSUE TITLE
Polaris OPV missing or extremely rare?

### ISSUE THREAD

**Issue by danielsolaro** [RavienGaming/Reforged-Eden-2#144]
### Reforged Eden 2 Build Number

11

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Been looking around for a Skenya to fight and realized how hard it is to find any Polaris OPV around, both in neutral territory and in polaris. I understand if lore wise they are protected by the Zirax but even on Polaris territory they have nothing, its one OPV every few orbits. For the most part its orbital POIs and no movement.
Question is if thats a design choice, a bug, or just WIP (you intend to have more?)
thank you.
ps. I didn't find a skenya and gave up lol

**Comment by RavienGaming** [comment]
This isn't a bug. They are spawning in their intended numbers. Of course these numbers may change in the future.
For anyone wondering: playfields can only safely have so many patrol vessels. RE2 is going to have far fewer per orbit than RE1 did to lower the chances of things like desynced patrol vessels, broken AI, etc.
