### ISSUE TITLE
Error starting Dedicated Server (CoQ)

### ISSUE THREAD

**Issue by WinterborneTE** [RavienGaming/Reforged-Eden-2#145]
### Reforged Eden 2 Build Number

12

### Game mode

Dedicated Server

### Tested in vanilla

Issue does not happen in vanilla

### Description of issue

I get a Continue or Quit error upon loading into a dedicated server after updating the game and the scenario. Error from log file included below. This error seems to prevent the playfield server from loading.

### Error code from console or log (Optional)

System.Exception: Unknown block name 'HeavyWindowPSmall' in action!

**Comment by RavienGaming** [comment]
That block is in the scenario configs. Maybe something went wrong with you updating the scenario files. Double check that you didn't accidentally do something like rename the folder, etc.

**Comment by WinterborneTE** [comment]
Deleted the files server side and locally. Redownloaded them fresh from workshop, re-uploaded them. Same issue. Tried with a new save, and the game starts a new save correctly. Am confident that there was some kind of hiccup with updating the files and that it carried over to the save file. You can go ahead and close this.

**Comment by RavienGaming** [comment]
Okay if anyone else has the same issue please feel free to open a new ticket, though the servers I follow were able to update time.
