### ISSUE TITLE
very large gold deposits

### ISSUE THREAD

**Issue by Shandril79** [RavienGaming/Reforged-Eden-2#146]
### Reforged Eden 2 Build Number

12

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Very large gold deposits on Midnight planets are nugget type deposits. removal of the ore detector makes these deposits almost impossible to mine out. Tested in a new survival game in build 12.

**Comment by RavienGaming** [comment]
Thanks. Fixed for next update by making them voxel deposits instead. Will only apply to newly generated star systems.
