### ISSUE TITLE
Resources the planet map said it had lied

### ISSUE THREAD

**Issue by CrazyGamer9191** [RavienGaming/Reforged-Eden-2#150]
### Reforged Eden 2 Build Number

12

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

I went to a G type system found a moon that said it had gold and no tungsten. It ended up with having a tungsten node no gold. The map when you are on the planet shows different resources than looking at from the galaxy map.
Also the tungsten node that was there did not show the size or a % mining and didn't disappear after mined.

### Playfield Name

Asteeris Moon

### Playfield Class

Temperate Moon Small

### Star Name

Sca Beta

### Star Class

G 

### Game Seed

814453

**Comment by RavienGaming** [comment]
Gold thing will be fixed for next update.
Custom ores like Tungsten and Palladium do not show on the map.
