### ISSUE TITLE
Deco Holo consoles use 12 cpu

### ISSUE THREAD

**Issue by Ente2k** [RavienGaming/Reforged-Eden-2#153]
### Reforged Eden 2 Build Number

13

### Game mode

Survival, Creative, Single Player, Co-op, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

The console deco doesn not cost cpu, but the glowing colorable holo displays, that are also placeable on SVs, do cost 12 cpu each. They should probably be no cpu cost.

**Comment by VermillionX** [comment]
Fixed for next update
