### ISSUE TITLE
Mission Survey Galaxy - Exotic Systems only one R class star (The Dyson Sphere) Which it wants me to go to?

### ISSUE THREAD

**Issue by InclineNor** [RavienGaming/Reforged-Eden-2#155]
### Reforged Eden 2 Build Number

10

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

On the mission Survey Galaxy - Exotic Systems I'm told to find R-Class system 1/3. There currently is only one R system. The Dyson Sphere in Progentior Space... Seems kinda excessive to jump there to comple 1 part of this mission. Seeing as this area is part of another mission chain? is this correct or plain and simply a bug?

### Error code from console or log (Optional)

na

### Mission Name

Survey Galaxy - Exotic Systems

### Mission Objective

Warp to R class system 1/3 Only Dyson sphere is R class.

### Game Seed

1011345

**Comment by RavienGaming** [comment]
This issue has already been reported here: #130
