### ISSUE TITLE
Shield Penetration

### ISSUE THREAD

**Issue by jmh033089** [RavienGaming/Reforged-Eden-2#156]
### Reforged Eden 2 Build Number

1.11.7 4480

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Issue does not happen in vanilla

### Description of issue

It makes the game almost unplayable, when you lose blocks fighting basic ships; How do you ever get to end game when you can't get through mid game. There is about 9 of us in our faction that have put 1000's of hours on RE1 and 100's on RE2, I am not saying it should not be a thing at all but its way to high, and we have done testing and looked at the coding and it makes almost impossible at mid game, and add unneed time to the game to repair your ships after ever fight.

**Comment by RavienGaming** [comment]
This is working as intended in the scenario. I'm only using GitHub for reporting scenario bugs, feedback can be left on the workshop or Discord. Thank you!
