### ISSUE TITLE
No gold from salvaging Small Matrix

### ISSUE THREAD

**Issue by Emp1xD** [RavienGaming/Reforged-Eden-2#160]
### Reforged Eden 2 Build Number

RE2 Build 13

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Using CV deconstructor, no gold from small Matrix

**Comment by VermillionX** [comment]
Optronic Matrixes cannot be deconstructed as they are base items.
