### ISSUE TITLE
Quest "Chapter 5: Offworld Grave: Fly me to the moon" activates on entering Ningues moon playfield without Titan wreckage

### ISSUE THREAD

**Issue by bld** [RavienGaming/Reforged-Eden-2#161]
### Reforged Eden 2 Build Number

12/13

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

I did a Ningues start with build 12 that upgraded to build 13. I followed the main story mission through Chapter 5: Offworld Grave > Fly Me to the Moon. That step in the quest told me to go to the Akua moon to find the Titan wreckage. Before going there, I visited Ningues Moon 1. The quest advanced like I had visited the Akua moon mentioned in the quest, and directed me to find the 3 pieces of the Titan wreckage, even though there are none on the Ningues moon. I haven't checked if there are other starts that have this happen as well.

### Playfield Name

Ningues Moon 1

### Star Name

Beta

### Star Class

FStartingSystem

### Mission Name

Chapter 5: Offworld Grave: Fly Me to the Moon -> Crash of the Titans

### Mission Objective

Locate forward, middle, rear sections

### Game Seed

Any

**Comment by RavienGaming** [comment]
Thanks. Fixed for next update. Will require a new save game.

**Comment by bld** [comment]
Great! I ended up going to Roggery's moon to continue the quest, since Akua's at another star.
