### ISSUE TITLE
SV/HV wrong drill ID

### ISSUE THREAD

**Issue by vixenfoxz** [RavienGaming/Reforged-Eden-2#162]
### Reforged Eden 2 Build Number

Build 13

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

me and one of my friends switched from RE to RE2 recently and noticed that the mechanical drill IDs for HV and SV are swapped, i like to use workshop ships and used this one back in RE1 https://steamcommunity.com/sharedfiles/filedetails/?id=2586340445 but when i went to bring it over to RE2 the drills where for HV instead of SV

**Comment by VermillionX** [comment]
This is not a bug. The IDs are not wrong.
In RE1 the HV and SV share the same mechanical drill. In RE2 the HV and SV have separate mechanical drills.
They are not switched; The SV Mechanical Drill did not exist in RE1.

**Comment by VermillionX** [comment]
This is not a bug. The IDs are not wrong.
In RE1 the HV and SV share the same mechanical drill. In RE2 the HV and SV have separate mechanical drills.
They are not switched; The SV Mechanical Drill did not exist in RE1.
