### ISSUE TITLE
POI's not regenerate

### ISSUE THREAD

**Issue by Almonra** [RavienGaming/Reforged-Eden-2#164]
### Reforged Eden 2 Build Number

build 13

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

When I was in the starter system all abandon buildings regen, but once leaving the start system they do not. Its running on a Host Havoc server.
When first saw this double chected that regen on POI was marked at yes, in fact everywhere was marked ,,,solo,,MP,, ect

**Comment by RavienGaming** [comment]
POIs have varying regeneration timers. Major ones are set at 3 irl days. If POIs are not regenerating even after that time it would be a server configuration issue not something that could be fixed in the scenario.
