### ISSUE TITLE
Can't sell thrusters to Flight Mechanic

### ISSUE THREAD

**Issue by Gavodir** [RavienGaming/Reforged-Eden-2#166]
### Reforged Eden 2 Build Number

2474815

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

https://cdn.imgchest.com/files/k46acpq9vz7.png

In trying to sell jet thrusters to this vendor, the ones with name mismatches say "no stock." I sold Large jet thrusters just fine, but medium and advanced I'm unable to sell. After trying to figure out why, I think it's because the item name in the shop doesn't match the craftable item. The shop says "thruster" when the crafted item is "thrusters" on types with multiple options. These types I can't sell to the shop.

### POI Name

Trade Station CB802N

**Comment by VermillionX** [comment]
Ah, forgot to change those over to the new parent block.
Fixed in next update.
