### ISSUE TITLE
Abandoned Mine Portal can be destroyed before core is removed 

### ISSUE THREAD

**Issue by Grabber48** [RavienGaming/Reforged-Eden-2#167]
### Reforged Eden 2 Build Number

13

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

In  the Abandoned Mine can shoot and destroy the portal in front of the core from just outside the room then can destroy the core. Once you enter the room and the sensor detects you and sets off the explosion that is supposed to destroy the core but destroys the Bio Box instead because the core is gone losing the loot. Portal needs to be indestructible until core is destroyed.

### POI Name

Abandoned Mine

### Star Class

F

**Comment by VermillionX** [comment]
The portal cannot be indestructible. If it was indestructible, it would not be destroyed by the explosive block next to the core. Ultimately, the portal has zero effect on the destruction of the biobox. It was destroying the core by hand and then walking onto the sensor that destroyed the biobox (which is a half-block space nowhere near the portal), so just don't do that.

**Comment by Grabber48** [comment]
Why have an explosive block if you can just shoot the core from a distance? Or you could put a heavy window between the portal and the core, hard to know you're not supposed to shoot the core when it is such an easy target. Not arguing just curious why the portal can be destroyed when most things in a poi can't be damaged while the core is intact, could the hit points be increased. Sorry for taking up your time but I have a curious mind and like to know how things work in game and in life.

**Comment by RavienGaming** [comment]
I believe this issue has been fixed now.
