### ISSUE TITLE
Luxury Goods in Abandoned Tomb

### ISSUE THREAD

**Issue by Ipurgepeople** [RavienGaming/Reforged-Eden-2#168]
### Reforged Eden 2 Build Number

Build 8 (Haven't found one since!)

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

"Luxury Goods" item is still dropping as loot in the Abandoned Tomb POI. According to the config file these are now defunct. 

Furthermore, they have dropped from something else as well, presumably Pirate OPVs, in Build 13.

### POI Name

Abandoned Tomb

**Comment by RavienGaming** [comment]
Thank you the pirate OPVs should be gone now (if you find any in new star systems please let me know). The abandoned tomb I will have to update later.

**Comment by RavienGaming** [comment]
I went through the loot of the abandoned tomb and I "think" I got all the luxury goods replaced with jewelry for next update.
If you find any in newly generated tombs after the scenario update please feel free to open a new ticket, with a screenshot of the location where you found it (there's a LOT of containers in there).
