### ISSUE TITLE
Resource name not found: @rg_projectiles/RG_ProjectileBeamDrillHandBlue 

### ISSUE THREAD

**Issue by CadaVezNL** [RavienGaming/Reforged-Eden-2#170]
### Reforged Eden 2 Build Number

RE2BUILD14

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

When i use the Project Eden Debug drill, it doesnt show up the blue line, and in console it spams full with error messages.
![Èrror](https://github.com/RavienGaming/Reforged-Eden-2/assets/10815481/10046bfe-2439-40f9-9758-b4921fab207b)

### Error code from console or log (Optional)

![Èrror](https://github.com/RavienGaming/Reforged-Eden-2/assets/10815481/588f45c0-d773-4f79-a64f-b3bc159959d5)

### POI Name

any

### Playfield Name

any

### Playfield Class

any

### Star Name

any

### Star Class

any

### Mission Name

any

### Mission Objective

any

### Game Seed

any

**Comment by CadaVezNL** [comment]
The Issue did not exist in verions RE2Build13

**Comment by RavienGaming** [comment]
Is this on a server? If so you'll need to contact your server admin for assistance. If you are the server admin you need to follow the directions to properly upload the bundle files using binary mode in your FTP client. If you're using the new shareddata cache download feature, that thing has all kinds of problems but we can go over possible solutions here if so.

**Comment by RavienGaming** [comment]
Scratch my last reply. I'll look into this.

**Comment by RavienGaming** [comment]
Is this on a server or SP?

**Comment by CadaVezNL** [comment]
On a server

**Comment by CadaVezNL** [comment]
we hire the server from nitrado :)

**Comment by RavienGaming** [comment]
> On a server

Thanks. I was not able to reproduce it so it's an issue with the server.
You should contact your server admin so they can fix this. If you are the admin, make sure to upload the scenario files using binary mode in your FTP client. If you're trying to use the new shareddata cache download method, that has several issues that we can go over here.

**Comment by CadaVezNL** [comment]
i will check :) thx for the great work your doing :)

**Comment by CadaVezNL** [comment]
is there a change in uploading the files my ftp will time out now, if i use binarymode or not ;o

**Comment by RavienGaming** [comment]
I'm not sure, I can't really help troubleshooting FTP issues sorry.

**Comment by CadaVezNL** [comment]
no worries i will find out ;)
