### ISSUE TITLE
Heavy Railgun Turret requires 'Light Railgun Turret' unlocked, which does not exist.

### ISSUE THREAD

**Issue by Zalmithius** [RavienGaming/Reforged-Eden-2#174]
### Reforged Eden 2 Build Number

14

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

The 'Heavy Railgun Turret' schematic lists 'Light Railgun Turret' as a prerequisite, but this prerequisite does not exist in the tech tree. The node leading to 'Heavy Railgun Turret' is 'Medium Railgun Turret', and the Heavy schematic does not appear in any category of the schematic unlock menu after unlocking the Medium turret. Unlock points aren't the issue.

![image](https://github.com/RavienGaming/Reforged-Eden-2/assets/44933916/c63d50b3-973e-41bb-b966-667ba52a6a40)
![image](https://github.com/RavienGaming/Reforged-Eden-2/assets/44933916/1bb87698-38f3-4811-a407-1e0cd525ff3d)

**Comment by RavienGaming** [comment]
Thanks. Fixed for next update.

**Comment by Zalmithius** [comment]
Thank you for all the work you put in.
