### ISSUE TITLE
Mainframe hack

### ISSUE THREAD

**Issue by curtnoel** [RavienGaming/Reforged-Eden-2#176]
### Reforged Eden 2 Build Number

14

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

You have to hack the scanning arrays first then hack the terminals on the Mainframe. I hack the arrays then hack 1 on the mainframe then I went to the next terminal and it said it was already hacked. So I went to the mainframe terminal in the center and it says I still need to hack. This happened to me 2x. So mission wont complete.

### POI Name

EdenSpace_POI_HackT1_1

### Playfield Name

Rauadeade Tau sector  Iblekaltho system

### Playfield Class

the poi name

### Star Name

 Iblekaltho system

### Star Class

R

### Mission Name

EdenSpace_POI_HackT1_1

### Game Seed

not sure where to find. this is a multiplayer server

**Comment by RavienGaming** [comment]
Thanks, found what I think is causing the issue and should be fixed in next update.
