### ISSUE TITLE
Derelict Tanks POI

### ISSUE THREAD

**Issue by Bonedog-DHB** [RavienGaming/Reforged-Eden-2#178]
### Reforged Eden 2 Build Number

Current

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Cargo Drums 4, 5, and 6 are all empty on this POI, I tested this on two of them. Not sure if this is a vanilla POI in the Orbit around Tallodar or not.

### POI Name

Derelict Tanks

### Playfield Name

Tallodar Sector

### Star Name

Alpha

### Game Seed

240630

**Comment by RavienGaming** [comment]
Thanks. I added a single toxic waste to each for next update so they aren't "empty" since they aren't meant to have much loot.
