### ISSUE TITLE
Talon Fishing Equipment invisible

### ISSUE THREAD

**Issue by curtnoel** [RavienGaming/Reforged-Eden-2#180]
### Reforged Eden 2 Build Number

14

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Went to do the Talon fishing quest. Bought the pole and the bait then caught a fish. All three items have no graphics

### POI Name

Talon Fishing Hut

### Playfield Name

various

**Comment by RavienGaming** [comment]
This will need to be removed from the scenario. I would destroy the items as they are going to be removed next update.
