### ISSUE TITLE
Schematic - Heavy Blaster Cannon UCH turn in does not unlock recipe and does not exist in F3 Tech Tree menu

### ISSUE THREAD

**Issue by StHotPants** [RavienGaming/Reforged-Eden-2#181]
### Reforged Eden 2 Build Number

RE2 Beta Build 14

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Received Schematic: Heavy Blaster Cannon as a drop from an Ultra Rare alien loot container. Followed UCH vessel technology unlock process but when I go to create one (picture below from Universal Constructor interface) it shows as still locked and references to unlock it in the Tech Tree F3 menu. There is no Heavy Blaster Cannon entry in the Tech Tree to unlock the device.
![image](https://github.com/RavienGaming/Reforged-Eden-2/assets/169509491/2939deb4-8d27-4535-a921-81b5e96fe049)

**Comment by RavienGaming** [comment]
Please update to build 15 as this is fixed then.

**Comment by RavienGaming** [comment]
Though I just noticed the schematic name wasn't fixed in b15. Will be in next update though that won't affect unlocking it.
