### ISSUE TITLE
Ore Deposits have a gravel texture.

### ISSUE THREAD

**Issue by thomaslambert-gamesdesigner** [RavienGaming/Reforged-Eden-2#182]
### Reforged Eden 2 Build Number

15

### Game mode

Survival

### Tested in vanilla

Issue does not happen in vanilla

### Description of issue

Any ore deposit that I mine appears to have the texture of graphite. Not sure what the issue is. Thankfully I can still mine it and receive the ore the marker says it is so it is not game breaking.

**Comment by RavienGaming** [comment]
Need to know the planet type and which ore.

**Comment by thomaslambert-gamesdesigner** [comment]
> Need to know the planet type and which ore.

It was on Akua and Akua Moon and it was alumnium and graphite

**Comment by RavienGaming** [comment]
Fixed missing graphite ore texture on Akua and Tallodar for next update. The moon has no texture slots free so some ore deposits will show the default gray texture.

**Comment by dot-sent** [comment]
@RavienGaming I've just experienced the same issue on build 45 with all deposits but Iron (that is: Copper, Promethium, Zascosium and Gold) on a Crusted Lava randomly generated planet. I have read your explanation elsewhere regarding the technical limit on textures per planet type - but I don't think there is a publicly available list of known planets with this issue. Should I report this properly with all the technical details or is it a known issue? Also, if you'd like a proper report, would you prefer me to open a new issue or just drop a comment here?

**Comment by RavienGaming** [comment]
> [@RavienGaming](https://github.com/RavienGaming) I've just experienced the same issue on build 45 with all deposits but Iron (that is: Copper, Promethium, Zascosium and Gold) on a Crusted Lava randomly generated planet. I have read your explanation elsewhere regarding the technical limit on textures per planet type - but I don't think there is a publicly available list of known planets with this issue. Should I report this properly with all the technical details or is it a known issue? Also, if you'd like a proper report, would you prefer me to open a new issue or just drop a comment here?

Hmmm maybe just open a new issue on that. That way I don't forget to check it.
Thank you!
