### ISSUE TITLE
Universal Constructor does not produce Deuterium Fuel

### ISSUE THREAD

**Issue by GeodeTheRock** [RavienGaming/Reforged-Eden-2#183]
### Reforged Eden 2 Build Number

Build 15

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

The universal Constructor does not list Deuterium Fuel as a product.

**Comment by GeodeTheRock** [comment]
Low Priority, but I assume the Universal Constructor would be meant to have this product.

**Comment by RavienGaming** [comment]
Thanks. Fixed for next update.
