### ISSUE TITLE
Turned in 5 nav data and game crashes

### ISSUE THREAD

**Issue by CrazyGamer9191** [RavienGaming/Reforged-Eden-2#184]
### Reforged Eden 2 Build Number

15

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

I turned in 5 nav data at UCH ship and when I go to devices in my CV and click warp drive to see range it did not change and crashes to main menu. It is a spawned in ship from factory. When I click cont. & mail it say error. I have used the H menu a bit and God mode twice in save before error.

### Game Seed

919

**Comment by RavienGaming** [comment]
This is likely a game bug and will need to be reproduced and reported using a vanilla save game.
When reproducing a game bug in a vanilla save, make sure you are using the same mode _(singleplayer/co-op/dedicated multiplayer, survival/creative)_ as what you were using when the issue happened in the scenario.
To see a list of known game bugs or to report a new one please see: https://empyriononline.com/forums/bugs.24/
This is likely a game bug and will need to be reproduced and reported using a vanilla save game.
When reproducing a game bug in a vanilla save, make sure you are using the same mode _(singleplayer/co-op/dedicated multiplayer, survival/creative)_ as what you were using when the issue happened in the scenario.
To see a list of known game bugs or to report a new one please see: https://empyriononline.com/forums/bugs.24/

**Comment by CrazyGamer9191** [comment]
How do I reproduce turning in Nav data to get extra warp jump range from UCH in vanilla , isn't all that part of RE2. I had to quit after the issue yesterday.  I logged in today everything seems fine still don't see where I got credit for the extra LY jump range. Sorry if I'm confused or not understanding what is vanilla and what is RE2.

**Comment by CrazyGamer9191** [comment]
I'm so sorry for wasting your time I was just dumb, I did get up grade to jump I wasn't aware that it changes the number to all your warp drives now and future. Game probably crashed for some other reason.

**Comment by RavienGaming** [comment]
Glad it's working now. And yeah it would have been a game bug most likely that caused a crash. There's been a lot of people crashing since the last game update.
