### ISSUE TITLE
Unreachable loot container on Titan Wreck (Mid)

### ISSUE THREAD

**Issue by bonesbro** [RavienGaming/Reforged-Eden-2#186]
### Reforged Eden 2 Build Number

15

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

There is an alien container behind two walkways in R2BA_CrashedTitanMid.  It looks like you're supposed to destroy the walkways to access the container, but the structure has an admin core and the walkways have full health, so they cannot be damaged.

### POI Name

Crashed Titan (Mid), R2BA_CrashedTitanMid

### Mission Name

Chapter 5, Offworld Grave, Titan's rest

**Comment by VermillionX** [comment]
Will investigate

**Comment by VermillionX** [comment]
Fixed in next update
