### ISSUE TITLE
Very-Berry Milkshake movement buff does not work. 

### ISSUE THREAD

**Issue by StHotPants** [RavienGaming/Reforged-Eden-2#187]
### Reforged Eden 2 Build Number

RE2 Beta Build 14

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

The Very-Berry Milkshake:
![image](https://github.com/RavienGaming/Reforged-Eden-2/assets/169509491/778627ac-7a0c-491a-8558-0d9eb37be818)

Drinking does give the Stamina buff but there is no 75% increase in movement speed as listed.

**Comment by RavienGaming** [comment]
The build being used is out of date, though that doesn't affect this issue it may mean other issues that have already been fixed will show up.

Looks like in the configs the buff needs to be changed from:
```
    Stat: speedmodifier
    SetValue: 1.75
    Type: speedmodifier
```
To:
```
    Stat: speedmodifier
    ModifyMaxValue: 0.75
    NumberOperationType: Factor
```

That will increase the player's maximum speed (I assume by 75%). Probably needs to have the same thing done for any other buffs that are meant to increase a player's max speed.

**Comment by VermillionX** [comment]
No, it's correct.
0.75 would reduce the player's speed to 75% of normal.
ModifyMaxValue shouldn't even work on speed since SetValue is dedicated to the speedmodifier.
