### ISSUE TITLE
Advanced Health Nanite Injector missing Description

### ISSUE THREAD

**Issue by DarkestWarrior** [RavienGaming/Reforged-Eden-2#190]
### Reforged Eden 2 Build Number

15

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

The description for the Advanced Health Nanite Injector displays as "Eden_RegenKit2Info". Also the status icon is weird when you have used the advanced health nanite injector.
![AdvancedHealthDescription](https://github.com/RavienGaming/Reforged-Eden-2/assets/174888495/3eca9aa3-56bf-4846-941e-1c12e08af40f)
![AdvancedHealthIcon1](https://github.com/RavienGaming/Reforged-Eden-2/assets/174888495/820cd582-4079-4273-af38-abb280b9cc27)
![AdvancedHealthIcon2](https://github.com/RavienGaming/Reforged-Eden-2/assets/174888495/35073b3a-0b80-4122-a906-61d27e5f64c7)

**Comment by RavienGaming** [comment]
The description is fixed in next update.
The icon has to be a unique one so it stacks with similar effects (or rather, so it actually shows you that it's still on you) so I had to get creative.
