### ISSUE TITLE
Tropical Cave Issues

### ISSUE THREAD

**Issue by Ipurgepeople** [RavienGaming/Reforged-Eden-2#191]
### Reforged Eden 2 Build Number

Build 15

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

No dialogues in the cave. Neither the Abandoned Mining Camp dialogue nor the Mushroom Formation dialogue work.

### POI Name

Cave

### Playfield Class

Tropical

**Comment by RavienGaming** [comment]
Thanks. Fixed for next update. Removed the dialogue blocks since it was something I had never finished.
