### ISSUE TITLE
Luxury Goods

### ISSUE THREAD

**Issue by Ipurgepeople** [RavienGaming/Reforged-Eden-2#192]
### Reforged Eden 2 Build Number

Build 15

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Luxury Goods are rearing their metaphorical head again. I found them in 2 more places:

1. Tropical Cave loot; &
2. Treasure POIs on Jungle planets.

### POI Name

Cave (on Tropical Planets) / Treasure (Jungle planets)

### Playfield Class

Tropical (for caves) / Jungle (For Treasure)

**Comment by RavienGaming** [comment]
Thanks I'll look over the loot and get that fixed!

**Comment by RavienGaming** [comment]
Thanks. This should be fixed for next update for any containers that use the special treasure chest loot ID.
