### ISSUE TITLE
Pentaxid Seeds

### ISSUE THREAD

**Issue by Ipurgepeople** [RavienGaming/Reforged-Eden-2#193]
### Reforged Eden 2 Build Number

Build 15

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Seed Trader NPC in Talon Big Market (And I found them in some other orbital POI but for the life of me I cannot recall where) has Pentaxid Seed Crystal in stock, but it is not purchasable.
![image](https://github.com/RavienGaming/Reforged-Eden-2/assets/172309983/831e9ff3-141f-4c06-ae6d-9b91f8c26e3d)

### POI Name

[Tal'on] Big Market

### Playfield Class

Tropical

**Comment by VermillionX** [comment]
Fixed in next update
