### ISSUE TITLE
Placeholder R2PirateMain FILLED WITH DIRT

### ISSUE THREAD

**Issue by Ipurgepeople** [RavienGaming/Reforged-Eden-2#194]
### Reforged Eden 2 Build Number

Build 15

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Tried to take out the (Placeholder) Pirate Main Base and the entire underground section is filled with dirt so raiding it is completely out of the question. See partially dug out staircase:
![image](https://github.com/RavienGaming/Reforged-Eden-2/assets/172309983/631d8dfa-81ce-4e69-a79b-bffc2745d715)

### POI Name

Placeholder R2PirateMain

### Playfield Name

Alpha 6083 I Moon

### Playfield Class

Temperate Moon

### Star Name

Dagur-elle

### Star Class

K

### Game Seed

17764

**Comment by RavienGaming** [comment]
These are placeholders only used for POI placement they aren't even meant to be interacted with.
