### ISSUE TITLE
Rude Medical Droid

### ISSUE THREAD

**Issue by Ipurgepeople** [RavienGaming/Reforged-Eden-2#195]
### Reforged Eden 2 Build Number

Build 15

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

The Medical Droid in the Placeholder Colonist Bar is quite rude and refuses to speak to me. Has no dialogue/inventory, so cannot trade.

### POI Name

Placeholder R2ColonistMission

**Comment by RavienGaming** [comment]
Duplicate of #194
