### ISSUE TITLE
Zirax civilian rescue quest cannot be completed: Unknown item 12.7mmBullet

### ISSUE THREAD

**Issue by bonesbro** [RavienGaming/Reforged-Eden-2#196]
### Reforged Eden 2 Build Number

15

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

In the Cultist Nexus POI there are several prisoners.  One prisoner is a ZiraxCivilianBlueFemaleStatic.  She asks me to fetch her a sniper rifle and 25 12.7mm sniper bullets so she can get revenge.  This cannot be completed - the dialogue is looking for item '12.7mmBullet' which does not exist.  (Tested and neither 12.7mm ammo, which is ammo for gatling turrets, nor regular 7.62mm sniper bullets satisfy the question)

### Error code from console or log (Optional)

-ERR- Dialogue cannot find item with name '12.7mmBullet'

### POI Name

Cultist Nexus, Eden_BA_CultNexus

### Playfield Name

Planet named "Seddacilna"

### Playfield Class

Fungal

### Star Name

Satidustor

### Star Class

M4

### Game Seed

1

**Comment by RavienGaming** [comment]
Thanks. Fixed for next update.
