### ISSUE TITLE
Polaris Trade station sector in neutral space contains outdated Trading Station

### ISSUE THREAD

**Issue by Mario-Radinovic** [RavienGaming/Reforged-Eden-2#197]
### Reforged Eden 2 Build Number

RE2 Build 15

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Most of the stars in neutral space that contains polaris trading station playfield (Orange station icon) contain outdated trading station - one that contains traders without missions and having outdated stocks

**Comment by Mario-Radinovic** [comment]
Forgot to add: POI name is [Polaris] Trade Station

**Comment by RavienGaming** [comment]
Adding updated Polaris orbital trading stations for next update.
