### ISSUE TITLE
Zirax Ground troops and Mechs on surface of Elder barren and Snow Planets in PoL Territory

### ISSUE THREAD

**Issue by Omegaflux** [RavienGaming/Reforged-Eden-2#199]
### Reforged Eden 2 Build Number

1.11.7

### Game mode

Survival, Co-op

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Attacked by Zirax Ground Troops and Mechs while flying along surface of Elder Barren and again on Snow Planet well inside Polaris Space Territory. This looks like a systemic issue across multiple planet types now.

### Playfield Name

SIIN 23939 IV and SIIN 23939 III

### Playfield Class

Elder Barren and Snow

### Star Name

Beelochi

### Star Class

F

**Comment by RavienGaming** [comment]
I fixed the one on Elder Barren for next update but I just checked the Snow type planets and those were set correctly.
Was it a "snow" planet or a different type of planet?

**Comment by Omegaflux** [comment]
It was snow but a report from faction mates not firsthand. I just scouted the Snow and do not see any Zirax. My apologies on that one. Thanks, will let you know if I find any others.

**Comment by RavienGaming** [comment]
Okay thank you I will mark this as fixed in next update then.
