### ISSUE TITLE
Player weapon reticle alignment issues

### ISSUE THREAD

**Issue by Stan2112** [RavienGaming/Reforged-Eden-2#20]
### Reforged Eden 2 Build Number

April 23 (v1.11.6 4471)

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

A number of RE2 player hand weapons have varying degrees of misalignment when going in to ADS (aim down sights, or default RClick).  It seems to only affect weapons with iron sights and red dot-type sights.  All weapons with scopes (sniper rifles, advanced assault rifle, LS-38 laser pistol, etc) align just fine when ADS.  I also tested the various player hand weapons in vanilla and while some do also misalign, it's not consistent with what happens in RE2.

Summary:
![summary](https://github.com/RavienGaming/Reforged-Eden-2/assets/168505441/22517bbc-1f49-41af-9def-cc82accd8e7c)

Pistol
![pistol-hip](https://github.com/RavienGaming/Reforged-Eden-2/assets/168505441/49141730-b3a3-4c01-9f4d-4955d82699f6)
![pistol-ADS](https://github.com/RavienGaming/Reforged-Eden-2/assets/168505441/8caba3d7-fbf5-4d21-ac0b-64747e49a971)

Advanced Pistols (FW-9 Wasp, LS-22, Elite Combat Pistol, Starhawk)
![WaspPistol-hip](https://github.com/RavienGaming/Reforged-Eden-2/assets/168505441/a630ace8-df1a-4e4d-873e-284f2252d81c)
![WaspPistol-ADS](https://github.com/RavienGaming/Reforged-Eden-2/assets/168505441/07f5e765-e3ad-4600-9d64-33d020d55ef7)

FB-MK2 Farr blaster
![Farr-hip](https://github.com/RavienGaming/Reforged-Eden-2/assets/168505441/a0e30df8-5360-453e-bf4f-1b0de3311ff0)
![Farr-ADS](https://github.com/RavienGaming/Reforged-Eden-2/assets/168505441/d0a51544-d131-4e64-b56e-2bda778a1caf)

SMG
![SMG-hip](https://github.com/RavienGaming/Reforged-Eden-2/assets/168505441/67d48252-dd6b-443e-a9a7-55250d08e901)
![SMG-ADS](https://github.com/RavienGaming/Reforged-Eden-2/assets/168505441/af14bbc3-d442-41a9-8290-19c2c2e078a8)

Advanced SMG
![advSMG-hip](https://github.com/RavienGaming/Reforged-Eden-2/assets/168505441/3186ab06-6642-4803-9546-dfc54a89103b)
![advSMG-ADS](https://github.com/RavienGaming/Reforged-Eden-2/assets/168505441/29ece571-449a-49fd-90de-7f118cad9210)

Laser SMG
![LaserSMG-hip](https://github.com/RavienGaming/Reforged-Eden-2/assets/168505441/88f9c700-21f7-4a0e-8d9d-09b763070559)
![LaserSMG-ADS](https://github.com/RavienGaming/Reforged-Eden-2/assets/168505441/402e9c00-08c8-4f74-8281-e76fe5b66736)

Shotgun
![shotgun-hip](https://github.com/RavienGaming/Reforged-Eden-2/assets/168505441/e6e87a3d-e03d-4d50-a3ef-e12c7f386ef6)
![shotgun-ADS](https://github.com/RavienGaming/Reforged-Eden-2/assets/168505441/e2e35a94-aa09-411c-9e8e-55626c69af26)

Advanced Shotguns (Combat Shotgun, Assault Shotgun)
![advShotgun-hip](https://github.com/RavienGaming/Reforged-Eden-2/assets/168505441/d9116261-a5fd-44e7-83c4-cc2684da200c)
![advShotgun-ADS](https://github.com/RavienGaming/Reforged-Eden-2/assets/168505441/b39af968-bb9a-4601-b611-955a9dff72b1)

Assault Rifle
![assault-hip](https://github.com/RavienGaming/Reforged-Eden-2/assets/168505441/70cf5712-d092-4a7a-98da-f844a2abddd1)
![assault-ADS](https://github.com/RavienGaming/Reforged-Eden-2/assets/168505441/995c0dd9-945e-416d-9c06-37407d8dcccf)

Zirax Heavy Shotgun (by far the worst, barrel doesn't even point toward the reticle)
![ZiraxHvyShotgun-hip](https://github.com/RavienGaming/Reforged-Eden-2/assets/168505441/be617182-91ad-41c9-8f41-47213eec47b4)
![ZiraxHvyShotgun-ADS](https://github.com/RavienGaming/Reforged-Eden-2/assets/168505441/77b323ee-a115-46b6-8f01-3b5824405074)

**Comment by RavienGaming** [comment]
Tested this a little and trying to fix it using the movements, it might be an issue that **can't** be fixed within a scenario for some of these custom weapon models. I was able to get the Assault Rifle to not change your aim point very much, but then the entire gun clips through the player's view during the transition from hipfire to ADS which looks bad. So it might be possible to improve it for some weapons but I think it's still going to be off for some models.
One note is that this doesn't actually make your aim miss, you'll still hit where the sights are lined up, but it does change your aiming location between hipfire and ADS.

Probably a result of a combination of using custom weapon models, custom weapon movements, and Empyrion jankiness. Vermillion might know more.
Thanks for reporting this.

**Comment by VermillionX** [comment]
There's no way to fix any of them except for maybe the T1 Pistol, T2 Pistol, T2 SMG and T1 Assault Rifle because those models were added by me.
Unfortunately, that's a nightmare. Because the center of the screen in-game is not a real location in Unity to aim them at. So no frame of reference.

I might just remove the ability to use the sights on a zirax shotgun, since eleon screwed that one up beyond fixing.

**Comment by Stan2112** [comment]
I just tried all the similar weapons in RE1 under similar controlled conditions.  I didn't realize that there were alignment issues there as well.  Seems overall RE1 weapons are much better at alignment, but still less than ideal.

Not really a bug report per se, but the RE2 assault rifle feels anemic.  The combination of awful ADS alignment, model perspective/proportion like a stick you'd find in the woods, and it doesn't "feel" right makes for a bad experience.  I'd rather return to the RE1 model honestly.  A critical part of FPS play is knowing that your gun is going to shoot where you aim it (at least for the first few shots before recoil gets crazy) and that aim point will not change between hipfire and ADS.  I appreciate the dealing with all this is a real PITA, but these are the touches that reduce frustration in an already janky game.  TY for taking a look.

**Comment by VermillionX** [comment]
I have other assault rifle models. There's an ironsight version of the T2 Assault Rifle in my assets which I used first. The only thing is that the ironsights on the model are through the carry handle, which blocks off a lot of the player's view and looks weird as hell.
I could probably attach a red dot sight to the top, but that might look weirder since it's a tall gun.
The RE1 T1 Assault Rifle doesn't match any other model in the game, it's bulbous and comically large for an assault rifle.

**Comment by VermillionX** [comment]
![JankyIronsights](https://github.com/RavienGaming/Reforged-Eden-2/assets/10645298/ee5ba129-4346-4fb4-a912-6eb41e6784c4)
These are the ironsights on the Assault Rifle model. (Pulse Rifle for vanilla/RE1) They're weird. I've stuck a reflex sight on top, but it looks a bit out of place.
