### ISSUE TITLE
Talon Trader on Plantation POI not working

### ISSUE THREAD

**Issue by Ente2k** [RavienGaming/Reforged-Eden-2#200]
### Reforged Eden 2 Build Number

15

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Cannot talk to the trader on the Plantation POI. Just doesn't show up the option to initate dialogue.

### POI Name

BA_TalonPlantation2

### Playfield Class

Strange Temperate

**Comment by VermillionX** [comment]
There's a plantation POI? Is it a vanilla one?

**Comment by Ente2k** [comment]
Well the POI name BA_TalonPlantation2 does imply that it might be a vanilla POI. (Not totally sure about the naming schemes)

**Comment by RavienGaming** [comment]
Thanks! Know what the issue is, will work on getting this fixed. The R2 Talon POIs are sharing group names with the vanilla POIs so they are both spawning.

**Comment by RavienGaming** [comment]
Should be fixed in the next update.
