### ISSUE TITLE
Colonist Deco POI "Communication Array" misses Parts 

### ISSUE THREAD

**Issue by Ente2k** [RavienGaming/Reforged-Eden-2#201]
### Reforged Eden 2 Build Number

15

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

The Communication Array POI (Small deco POI I did for Raviens POI challenge on Anvil) misses the large communication dishes it should have on its 'Arms'

### POI Name

RE2_BA_ColonistDeco04

### Playfield Class

Strange Temperate

**Comment by Ente2k** [comment]
Same issue for R2BA_ColonistDecoMine01, it misses the Autominer model that should sit in there - thats one of Vermillions I think.
I would bet those aren't the only ones. Seems like our old friend, the missing parts bug on POIs from other People, is here.

**Comment by RavienGaming** [comment]
The autominer one is probably due to a different issue and just needs the autominer placed back such that it doesn't overlap one of the deco vents.

The other one I'll have to add the satellite dishes back in. Would you be able to PM me your version if you still have it, and I will just add the dishes back the same way in the scenario copy?

**Comment by RavienGaming** [comment]
![20240708190626_1](https://github.com/RavienGaming/Reforged-Eden-2/assets/151834238/ac4bef0b-ac13-47c9-9029-5dfcb5d8e345)

I added back the dishes. Does this look right?

For the R2BA_ColonistDecoMine01 I checked and it spawns with the autominer deco like it should. That could be caused either by an old POI spawn, the admin didn't update the prefabs, or the server got hit by the block ID bug.

**Comment by Ente2k** [comment]
Thanks! That looks right.
The R2BA_ColonistDecoMine01 was on Anvil, they only started and it should be a pretty new build. I am not familiar with the block ID bug, anything I can tell the server guys to fix or verify that?

**Comment by RavienGaming** [comment]
> Thanks! That looks right. The R2BA_ColonistDecoMine01 was on Anvil, they only started and it should be a pretty new build. I am not familiar with the block ID bug, anything I can tell the server guys to fix or verify that?

I made a report for it here: #10

**Comment by RavienGaming** [comment]
I'll mark this particular one as fixed in next update.
