### ISSUE TITLE
Polaris Mining Quartermaster (Report #56 and #75) still without dialogue

### ISSUE THREAD

**Issue by Trazer-12** [RavienGaming/Reforged-Eden-2#203]
### Reforged Eden 2 Build Number

15

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Issue identified in Report #56 and #75https://github.com/RavienGaming/Reforged-Eden-2/issues/75 not fixed with current Build 15 (I believe build 15 is after the bug report was identified as fixed).

The Mining Quartermaster on the Mining Foreman ship is one of the randomly spawning ones in a planetary space sector. Not one of the Mining Foreman ships found in Polaris Asteroid fields.

I went through both previous issue reports and it appears to be identical, therefore I pasted the text, seems like Mining Fleet spawn is still enabled.

### POI Name

Polaris Mining Foreman

### Playfield Name

Dishalite Orbit

### Playfield Class

Dead World Orbit

### Star Name

Ponti Alpha

### Star Class

M

### Game Seed

1045631213

**Comment by RavienGaming** [comment]
That POI was removed from the playfield, but that fix would have only applied to newly generated star systems so you must have found an old one. However your report did lead me to finding some other old Polaris POIs that did need to be removed from cold orbits.
I will mark this as a duplicate, but if you double click on a star system from the galaxy map you can verify if it's been generated or not. If it's generated it will open the system map. If you find another one of these in a newly generated system please use the di console command and look at the POI and share a screenshot of what that di screen says so I can track it down.

**Comment by Trazer-12** [comment]
This is on a private server that was setup last Sunday on lastest build, I'm 99.99% sure I generated the playfield barely 20 minutes before reporting, here's the di screenshot. 
![di_foreman_polaris](https://github.com/RavienGaming/Reforged-Eden-2/assets/130156180/eb30ff51-6d15-4f7e-b1c1-a6bceec0bc9a)

I will keep looking for other ones and will add them to this thread if I find more.

**Comment by RavienGaming** [comment]
Can you share an uncropped screenshot showing the local map screen when you are in the playfield you found this in? I just searched all playfield files in the scenario and the only one that has it still spawning is an unused space orbit playfield.

**Comment by Trazer-12** [comment]
Just in case it could be of any use, here's the sector and system maps, alongside another uncropped screenshot of di+local envrionnement
![localmap_foreman_polaris](https://github.com/RavienGaming/Reforged-Eden-2/assets/130156180/e4a4c25f-9a45-4585-9ee3-aa4c1fc43334)
![sector_map_foreman_polaris](https://github.com/RavienGaming/Reforged-Eden-2/assets/130156180/a8c51391-30e7-4830-9ac9-f3f33556a3cb)
![uncropped_di_foreman_polaris](https://github.com/RavienGaming/Reforged-Eden-2/assets/130156180/94fa81f9-c354-43d3-b389-0d0f2fe1a504)

**Comment by RavienGaming** [comment]
Yes this was already removed from the RE2 playfield files. If you go to your local copy of the scenario on the server, under Playfields/EdenSpaceD_Orbit, and search for Foreman, you should find an entry that is commented out like so:

`# Polaris Mining Fleet
# Mining Foreman
    # - Type: BA_Alien
      # Name: [Eden_BAO_PolForemanT2]
      # DisplayName: Mining Foreman
      # Faction: Polaris
      # Mode: Survival
      # CountMinMax: [ 1, 1 ]
      # Probability: 0.15
      # InitPower: True
      # Compound:
        # CountMinMax: [8, 25]
        # Probability: 1
        # Name: [CompoundAsteroidFieldPolaris, Eden_BAO_BeaconPolMine, CompoundPolarisMiners, CompoundPolarisMiners, CompoundPolarisMiners, CompoundPolarisMiners, Eden_BAO_PolHaulerT2, Eden_OPV_Polaris1, Eden_Asteroid_GoldT1_1, Eden_AsteroidNeodymium1, Eden_AsteroidNeodymium2, Eden_AsteroidNeodymium3, Eden_AsteroidSathium1, Eden_AsteroidSathium2, Eden_AsteroidSathium3, Eden_AsteroidPromethium1, Eden_AsteroidPromethium2, Eden_AsteroidPromethium3]
        # DistanceMinMax: [500, 1500]
        # Rotate: true
      # Position:
         # PosXZMinMax: [8000, 14000]
         # PosYMax: 8000
      # Properties:
        # - Key: Discovery
          # Value: False
        # - Key: Music
          # Value: NebularClouds  
        # - Key: RegenAfter
          # Value: 720`

If you see anything different then the files on the server are out of date.

**Comment by Trazer-12** [comment]
I ran both texts through a text comparer and there was no discrepancy. In case I missed it, here's the file ripped straight from the running server, last modified on sunday July 7th, before the playfield was generated (converted to txt because github doesn't allow for .yaml upload): 
`# Polaris Mining Fleet
# Mining Foreman
    # - Type: BA_Alien
      # Name: [Eden_BAO_PolForemanT2]
      # DisplayName: Mining Foreman
      # Faction: Polaris
      # Mode: Survival
      # CountMinMax: [ 1, 1 ]
      # Probability: 0.15
      # InitPower: True
      # Compound:
        # CountMinMax: [8, 25]
        # Probability: 1
        # Name: [CompoundAsteroidFieldPolaris, Eden_BAO_BeaconPolMine, CompoundPolarisMiners, CompoundPolarisMiners, CompoundPolarisMiners, CompoundPolarisMiners, Eden_BAO_PolHaulerT2, Eden_OPV_Polaris1, Eden_Asteroid_GoldT1_1, Eden_AsteroidNeodymium1, Eden_AsteroidNeodymium2, Eden_AsteroidNeodymium3, Eden_AsteroidSathium1, Eden_AsteroidSathium2, Eden_AsteroidSathium3, Eden_AsteroidPromethium1, Eden_AsteroidPromethium2, Eden_AsteroidPromethium3]
        # DistanceMinMax: [500, 1500]
        # Rotate: true
      # Position:
         # PosXZMinMax: [8000, 14000]
         # PosYMax: 8000
      # Properties:
        # - Key: Discovery
          # Value: False
        # - Key: Music
          # Value: NebularClouds  
        # - Key: RegenAfter
          # Value: 720`
[space_dynamic.txt](https://github.com/user-attachments/files/16152156/space_dynamic.txt)
![image](https://github.com/RavienGaming/Reforged-Eden-2/assets/130156180/a3acddb9-18a4-4796-8dc8-50ac14d51a19)


I set the server up myself, and unsubscibed and resubscribed on sunday before uploading, leading me to think they should be up to date.

**Comment by RavienGaming** [comment]
Yup that looks correct. So it must have been a star system that had already been generated before the update that removed it.
