### ISSUE TITLE
Abandoned Depot blast door not closed by default. 

### ISSUE THREAD

**Issue by PoorLuckPierre** [RavienGaming/Reforged-Eden-2#205]
### Reforged Eden 2 Build Number

15

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Ran an Abandoned Depot and down in the Infected tunnels one of the three blast doors leading to the Legacy tunnels was already opened before I pulled the lever. 

I assume this is the case for every abandoned depot, but I haven't been able to find another one. 
![AbandonedDepotBlastDoor](https://github.com/user-attachments/assets/1dca95c5-cb69-4dcd-9b35-4374ad295d64)

### Error code from console or log (Optional)

NA

### POI Name

Abandoned Depot

### Playfield Name

Diymon

### Playfield Class

Desert Planet

### Star Name

Vaporba

### Star Class

O

### Mission Name

NA

### Mission Objective

NA

### Game Seed

454841

**Comment by PoorLuckPierre** [comment]
I checked out the POI in creative and there all doors were closed for me.

**Comment by RavienGaming** [comment]
This is likely a game bug and will need to be reproduced and reported using a vanilla save game.
When reproducing a game bug in a vanilla save, make sure you are using the same mode _(singleplayer/co-op/dedicated multiplayer, survival/creative)_ as what you were using when the issue happened in the scenario.
To see a list of known game bugs or to report a new one please see: https://empyriononline.com/forums/bugs.24/
