### ISSUE TITLE
Malformed ECF entries

### ISSUE THREAD

**Issue by NotOats** [RavienGaming/Reforged-Eden-2#207]
### Reforged Eden 2 Build Number

15

### Game mode

Single Player

### Tested in vanilla

Issue does not happen in vanilla

### Description of issue

While working on an ECF parser I found several issues in the current (RE2 B15) scenario files. Some are "officially" supported by eleon's parser but would be good to have uniform with the rest. Other are actual game play issues with dialogue code.

#### Container.ecf
In "official" spec but could be done better, missing/empty params

- Failed to parse line in Container 35 - Group_0: StartingEquipment_NewStart
  Missing param1, minimum documented "requirement" for groups

- Failed to parse line in Container 64 - Name_4: MultiTool, param1: 0.3, param2:
  Empty param2 (count)

- Failed to parse line in Container 77 - Group_0: empty 
  Another missing param1

- Failed to parse line in Container 658 - Name_0: Eden_ShipmentMilitary, param1: 0.1
   Empty param2 (count)

#### ItemsConfig.ecf
- DrillAttachmentWeapon
  Line `3    RadialIcon: Radial_StoneRemoval` the 3 should be a comment `#`

#### BlocksConfig.ecf
These seem to be misspellings, not sure if this affects functionality or not.
- ShowUser vs Showuser
  - Eden_TurretBolterCV
  - Eden_TurretBolterBA
-  RPFactor vs RpFactor
   - TalonChief
- MarketPrice vs Marketprice
  - CrystalsPyramidBlueStage1
 
#### Dialogues.ecf
Actual game breaking bugs, these will presumably stop their attached dialogues from working

- MN_MiningIce_Mission09
		Line - OptionIf_1: `HasItem('PrefabHousing', 5); HasItem('CivilianFurniture', 10)`
		Fix? - OptionIf_1: `HasItem('PrefabHousing', 5) && HasItem('CivilianFurniture', 10)`
- Eden_ExpeditionGeneral_StageSelect
		Line - Execute: `Eden_ExpeditionStage += 1; Eden_ExpeditionMissionSelect = Random(1,5;`
		Fix   - Execute: `Eden_ExpeditionStage += 1; Eden_ExpeditionMissionSelect = Random(1,5)`

**Comment by RavienGaming** [comment]
Thank you!

> Failed to parse line in Container 658 - Name_0: Eden_ShipmentMilitary, param1: 0.1
> Empty param2 (count)

That container ID is removed for next update anyway.

> ShowUser vs Showuser

Fixed for next update.

> Eden_ExpeditionGeneral_StageSelect

This dialogue isn't used and that entire section will need to be removed, but I fixed that specific part for next update.

**Comment by VermillionX** [comment]
Fixed the remaining ones for next update.

"empty" is intended, as that's how eleon does it. I've given it a param1 of 1 because why not?
