### ISSUE TITLE
Polaris Flight Mechanic has mission asking for item he sells

### ISSUE THREAD

**Issue by Garaman-EGS** [RavienGaming/Reforged-Eden-2#208]
### Reforged Eden 2 Build Number

15

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Visited Trade Station CB802N (R2BA_PolTradeStation01) on a Jungle planet. The Flight Mechanic trader (Starship Mechanic) had a mission asking for "5x Large Plasma Thrusters (SV)". He had 21 of them for sale in his inventory for 17k each. Mission reward was 150k for selling him back what you just bought from him.

Trader Inventory:
![20240712012412_1](https://github.com/user-attachments/assets/b9623b00-1d18-47c3-b960-7114a46b9bc4)

Mission:
![20240712012700_1](https://github.com/user-attachments/assets/7480bc94-f8f9-44ae-8d0b-65969f9dd3bd)

### POI Name

Trade Station CB802N

### Playfield Class

Jungle

### Star Class

F5

**Comment by VermillionX** [comment]
Fixed for next update
