### ISSUE TITLE
Crashed Dive 1 Explodes when salvaging 1 block

### ISSUE THREAD

**Issue by Bonedog-DHB** [RavienGaming/Reforged-Eden-2#210]
### Reforged Eden 2 Build Number

Current

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

The structural integrity of this POI is seriously buggered. placed a salvage core on it to loot a turret and half of the ship exploded into pieces. Salvaged a cargo box and the other half blew up. The POI was properly sunk into the ground but it has no supporting truss blocks. Maybe it requires the fake dirt underneath?

**Comment by RavienGaming** [comment]
This blueprint group is still vanilla. It will be fixed once custom wrecks are made to replace them.
