### ISSUE TITLE
Heavy Railgun Schematic - Wont unlock at the Research Computer

### ISSUE THREAD

**Issue by GeodeTheRock** [RavienGaming/Reforged-Eden-2#211]
### Reforged Eden 2 Build Number

15

### Game mode

Single Player

### Tested in vanilla

Issue does not happen in vanilla

### Description of issue

Heavy Railgun - Unable to learn Schematic. I have the Heavy Railgun Schematic. Its a UHC Technology, but I am unable to learn it at the research computer.

I have the schematic in inventory. I have over 2k research points available, and I have unlocked the Medium Railgun in the tree before it. When I use the Schematic computer, I select UHC Technology, but nothing shows up in the list. It is of course greyed out in the Constructor showing I have not learned the schematic yet.

### Error code from console or log (Optional)

Sorry,, I did not check. I will have to drop back by the UHC ship and will update the record if I find an error.

**Comment by RavienGaming** [comment]
I have tested this in SP and it works fine.
Did you try validating files or unsubscribing from the scenario and then resubscribing?

**Comment by GeodeTheRock** [comment]
I will unsubscribe and validate and then let you know.

**Comment by GeodeTheRock** [comment]
All12639 files successfully validated. 
Unsubscribed and Resubscribed

This worked. Sorry to have you spend time looking. I will check this again before listing any bugs.
