### ISSUE TITLE
Kennex Stations got thrusters and have left the galaxy

### ISSUE THREAD

**Issue by TheycallmeBuddy** [RavienGaming/Reforged-Eden-2#213]
### Reforged Eden 2 Build Number

NA

### Game mode

Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Kennex stations seem to be missing outside of starter zones. Talking with other people on discord and they are finding the same thing in MP game too: nothing but basic Trade Station or Trade Station Iota are spawning. I personally spent 2-3 hours last night system hopping and seeing nothing but those 2 trade stations and only those 2. Either Kennex isn't set to spawn in space or the other 2 are "weighted" so much that Kennex is not appearing.

### POI Name

Kennex Station

### Playfield Name

Anything in neutral space at least

### Playfield Class

Space

### Star Name

Space

### Star Class

Space

### Game Seed

Doesn't matter

**Comment by RavienGaming** [comment]
The Polaris POIs need to be updated or built for RE2.
