### ISSUE TITLE
Jungle planet poi's are a mess 

### ISSUE THREAD

**Issue by Tar-egs** [RavienGaming/Reforged-Eden-2#214]
### Reforged Eden 2 Build Number

build 15

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

theres a lot of poi's you cant pick up with radar or even see the name of, unless you get within 100 meters.

Zirax seems to only have 3 that showes up. house Epsilon large drone hangers with close to 10 pr planet. Epsilon commercial starport and the drone base, thats without defences or even zirax area controle.
i found a cluster of zirax poi's pr chance, witch diddent get detected, but got a few names at close range. Epsilon resistor(defence poi) and Epsilon comm center + others i wassent able to get the name off
![Epsilon poi cluster](https://github.com/user-attachments/assets/1df97d62-6373-4589-a95b-325ed98117a4)
![Epsilon resistor jungle](https://github.com/user-attachments/assets/b4798821-cfed-408d-8392-d05b7db0d128)
![house Epsilon comm center jungle planet](https://github.com/user-attachments/assets/c38c9034-8763-440a-9f3a-78dc2cf12357)
![junlge drone base no aera control](https://github.com/user-attachments/assets/9e56d20c-e618-451b-a2be-488b678d14dd)

at the polaris trade station. the oxygen Processor and data center wont show on map, can you can see there names at close range. i havent had this issue on other planets
![polaris jungle 2](https://github.com/user-attachments/assets/374374a5-6620-488e-8ea0-ef39e561feb7)
![polaris jungle](https://github.com/user-attachments/assets/d22d344f-80ae-4d45-be02-30237695c08c)

allso many talon poi's that i could not get the name off + some pyramid 
![talon jungle](https://github.com/user-attachments/assets/c3e3ac82-45c7-4d04-a29b-027c3d4a82ea)
![jungle pyramid cant scan](https://github.com/user-attachments/assets/f47fd736-53ff-4077-82f5-9b69d084a7e9)

### Star Class

A

**Comment by RavienGaming** [comment]
This is working as intended in the scenario.

**Comment by RavienGaming** [comment]
The description of the planet mentions that the thick jungle can interfere with scans.
