### ISSUE TITLE
Cargo Containers (Large): names for several variants mixed up

### ISSUE THREAD

**Issue by MothHunter** [RavienGaming/Reforged-Eden-2#217]
### Reforged Eden 2 Build Number

15

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

The names for several variants of the Cargo Container (Large) block group seem to have been mixed up.
I'm not 100% sure what the correct names for each should be, but my best guess is (variants numbered in order in which they appear in the selection menu):
(1) is: "Industrial Cargo Container"; should be: "Small Storage Box"
(3) is: "Industrial Framed Cargo Container"; should be: ??? (half-height Version of "Industrial Cargo Container)
(4) is: "Large Reinforced Container"; should be: "Industrial Framed Cargo Container"
(6) is: "Small Storage Box"; should be: "Large Reinforced Container"

Also, there might be something wrong with the hit points:
(5) "Reinforced Container" has only 500 hit points, which is the lowest number for all variants
(6) (which I think is meant to be the "Large Reinforced Container") has 1000 hit points, the lowest value for all full sized 2-block variants of this block group

**Comment by VermillionX** [comment]
Fixed for next update
