### ISSUE TITLE
Can not produce Biological Specimen, but dialog says I should be able to

### ISSUE THREAD

**Issue by MothHunter** [RavienGaming/Reforged-Eden-2#218]
### Reforged Eden 2 Build Number

15

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

The trader NPC at Vitalife Pharmaceuticals (Polaris) wants 500 Biological Specimens and tells me "They can be artificially stimulated in any Medical Constructor, or even a food processor if you are desperate enough."
However, neither the Food Processor nor the Universal Constructor give the option to produce them
![image](https://github.com/user-attachments/assets/21f8ce73-2a03-4158-9502-ff1e6920c20f)

### POI Name

Vitalife Pharmaceuticals (R2BA_VitalifeMedical)

**Comment by VermillionX** [comment]
They're crops. You can grow them. They're found in the farming tab of the Food Processor.

**Comment by MothHunter** [comment]
I know you can grow them. But the wording sounds to me like you would be able to craft them directly, so if that is intentionally not an option, it might be good to adjust the dialog.

**Comment by VermillionX** [comment]
You used to be able to craft them, before they could be grown. Will be changed in a future update.

**Comment by VermillionX** [comment]
The latest update should've changed the dialog for this mission.
