### ISSUE TITLE
Hive Nursery & Friends Broken

### ISSUE THREAD

**Issue by Kainne00** [RavienGaming/Reforged-Eden-2#219]
### Reforged Eden 2 Build Number

15

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Nursery flagged Orange for Drone Swarm Faction, while all four Hive Guardians are marked Dark Red, indicating Warlord Faction.  This is likely incorrect.

The nursery was consistently taking damage from..... Something... as it's shield started at 99% and were whittled down to 93% while clearing trash OPVs at a distance away from the nursery.  I suspect the misfactioned hive guardians have a turret that is slowly damaging the nursery.

Lastly, the Nursery Nova turrets are having a fantastic time focusing on destroying the resident Dronite spawns.  While entertaining to watch, over time the nursery is actually destroying those resource nodes.  The targeting values for the nursery turrets needs to be adjusted to prevent this.

### POI Name

Hive Nursery, Hive Guardian

### Playfield Class

Class 6 Combat Site

**Comment by RavienGaming** [comment]
Thank you!

The first is intended, as that is the enemy support faction so they can recharge the nursery shields.
I was not able to see anything shooting the nursery. It's possible it was from stray fire from something else that was hitting it by accident.

And for the last, the drones have reprogrammed their swarm missile launchers to no longer see Dronite asteroids as a threat for next update.

**Comment by Kainne00** [comment]
Fair enough.

I cleared the entire sector, did not see anything else near the nursery, nor did I get close enough to hit it or it hit me. and it's shield was slowly going down. I can only presume it was guardians, but I'll check in SP and see if i can find something
