### ISSUE TITLE
The Side Story: The Dead Chapter 2: The Last Cry - Nothing Spawned in the Ark,

### ISSUE THREAD

**Issue by GeodeTheRock** [RavienGaming/Reforged-Eden-2#220]
### Reforged Eden 2 Build Number

15

### Game mode

Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

I went through the Side Story: The Dead Chapter 2: The Last Cry 
The story proceeded as I would expect, but no mobs ever spawned in the Ark simulation. I never had to fight and the countdown just proceeded. 

At the end, I left the simulation and went to the Grave. I was given a dialogue that the Incendiary Mini Gun Schematic was now unlocked and I got the schematic. 

### Error code from console or log (Optional)

No type found for name 'eden_pda_3_Start'

### POI Name

ARK

### Playfield Name

Maveth

**Comment by RavienGaming** [comment]
This issue has already been reported here: #15
