### ISSUE TITLE
Quest from Cultist Nexus, Freeing Civilian, material is misleading for completion

### ISSUE THREAD

**Issue by Zu-Sushi** [RavienGaming/Reforged-Eden-2#222]
### Reforged Eden 2 Build Number

15

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Issue does not happen in vanilla

### Description of issue

![image](https://github.com/user-attachments/assets/2c2aa8db-322a-47a3-aa79-948aa3339b9d)
AlienCivilian 1 FatStatic
This specific npc asking for high-output capacitors aka advanced capacitor. which mislead for specific materials. which is not existed but can be completed with advanced capacitor instead.

**Comment by Zu-Sushi** [comment]
![image](https://github.com/user-attachments/assets/88cf918e-bea8-4fc9-bf0a-e5e00c079415)

**Comment by Zu-Sushi** [comment]
![image](https://github.com/user-attachments/assets/3d51def6-9831-48e4-9c8d-a9806ade8bea)
cant be completed as well, i have sniper rifle and 12.7mm x25

**Comment by RavienGaming** [comment]
This issue has already been reported here: #196
