### ISSUE TITLE
Destroying Back Thruster on Colonists Freighter and Colonists Mammoth Freighter chains to one of cores

### ISSUE THREAD

**Issue by Mario-Radinovic** [RavienGaming/Reforged-Eden-2#223]
### Reforged Eden 2 Build Number

RE2 Build 15

### Game mode

Survival, Single Player, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Destroying Back Thruster on Colonists Freighter and Colonists Mammoth Freighter chains to one of cores. Which doesn't disable the ship, but counts towards number of cores destroyed causing "1h cooldown" every 2nd ship that gets disabled.

![20240716060111_1](https://github.com/user-attachments/assets/a591e9b9-0f7f-4a18-9d8d-80899a813ff0)

**Comment by Mario-Radinovic** [comment]
Additional note: Did 6 more and didn't encounter that problem again, not sure if it was because only single variation has that problem or if chain explosion doesn't count and it did count that one time so I think it needs more testing to confirm

**Comment by RavienGaming** [comment]
I'll look into it and see if I can fix it so it doesn't happen.

**Comment by RavienGaming** [comment]
I made some changes to hopefully prevent chaining to the cores for next update for those freighters.
