### ISSUE TITLE
Bulldozer blade not showing CPU requirement

### ISSUE THREAD

**Issue by Jivaii** [RavienGaming/Reforged-Eden-2#225]
### Reforged Eden 2 Build Number

RE 2 build 15

### Game mode

Survival, Creative, Single Player, Co-op, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Bulldozer blade shows no CPU cost, however it shows 750 CPU used when installed on a craft in CPU statistics.

Does not show up in the device tab that it needs any CPU.

**Comment by RavienGaming** [comment]
This should be fixed as of the latest Build 16 update.
