### ISSUE TITLE
No maximum health increase from Ziraxian Salad when implant installed

### ISSUE THREAD

**Issue by Gavodir** [RavienGaming/Reforged-Eden-2#227]
### Reforged Eden 2 Build Number

16

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Having an epsilon implant installed which increases my max hp to 575 makes the Ziraxian Salad's max hp increase not take effect. Without an implant it would raise to 700 temporarily.  I haven't tested with other max HP increasing implants.

**Comment by RavienGaming** [comment]
Stat bonuses do not stack unfortunately.
