### ISSUE TITLE
Weapons added to Weapon Locker in build 16 not moddable

### ISSUE THREAD

**Issue by Gavodir** [RavienGaming/Reforged-Eden-2#228]
### Reforged Eden 2 Build Number

16

### Game mode

Single Player, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

When I click on Gauss Shotgun, Light Scout Rifle, or Syndicate Uzi in the Weapon Locker, the dialogue turns blank with no options.

**Comment by VermillionX** [comment]
Fixed in next update
