### ISSUE TITLE
RE2_BAO_SatColT1_11 does not have admin core

### ISSUE THREAD

**Issue by Ishantil** [RavienGaming/Reforged-Eden-2#23]
### Reforged Eden 2 Build Number

Build 1 (April 29)

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

RE2_BAO_SatColT1_11 does not have admin core

### POI Name

RE2_BAO_SatColT1_11

**Comment by RavienGaming** [comment]
Thanks, will get this fixed.

**Comment by RavienGaming** [comment]
And fixed for the next update! Thanks again for letting me know.
