### ISSUE TITLE
Flashing green lines all over the screen

### ISSUE THREAD

**Issue by Jelledan** [RavienGaming/Reforged-Eden-2#231]
### Reforged Eden 2 Build Number

Build 17

### Game mode

Co-op

### Tested in vanilla

Issue does not happen in vanilla

### Description of issue

the game has been playing fine for the last couple of weeks but today half an hour after starting play, green lights started flashing all over the screen
![20240720_173138](https://github.com/user-attachments/assets/5694f4e9-c2f0-457e-97d4-4d8de8588ee4)

### Error code from console or log (Optional)

na

### POI Name

na

### Playfield Name

Everywhere

### Playfield Class

all

### Star Name

all 

### Star Class

all

### Mission Name

na

### Mission Objective

na

**Comment by RavienGaming** [comment]
That looks like some kind of artifact from the game's reflections.
*edit* or you have radiation sickness of some kind. It's hard to tell from your picture.

This is likely a game bug and will need to be reproduced and reported using a vanilla save game.
When reproducing a game bug in a vanilla save, make sure you are using the same mode _(singleplayer/co-op/dedicated multiplayer, survival/creative)_ as what you were using when the issue happened in the scenario.
To see a list of known game bugs or to report a new one please see: https://empyriononline.com/forums/bugs.24/
