### ISSUE TITLE
Tool turrets CV do not have option to select drill turret

### ISSUE THREAD

**Issue by dcrabbe** [RavienGaming/Reforged-Eden-2#232]
### Reforged Eden 2 Build Number

NA

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

When attempting to choose a drill turret from a tool turret, the options are only multi turrets. Drill turrets are not available

**Comment by VermillionX** [comment]
The Tool Turret can now mine, salvage and repair. You don't need to choose or switch between turret types.
This is intended.

**Comment by vixenfoxz** [comment]
odd cause i tried to mine using the other three options and it wouldnt mine till i put it on the top option

**Comment by dcrabbe** [comment]
That’s good to hear, this then raises the question on the option wheel icon, is there already an open defect for the drill icon displaying the ship dampener icon?

**Comment by RavienGaming** [comment]
> That’s good to hear, this then raises the question on the option wheel icon, is there already an open defect for the drill icon displaying the ship dampener icon?

Here: #234
