### ISSUE TITLE
Light Missile Turrets (CV) research tooltip typo

### ISSUE THREAD

**Issue by Tactitocalon** [RavienGaming/Reforged-Eden-2#233]
### Reforged Eden 2 Build Number

16

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Light Missile Turrets (CV) in the tech tree research tooltip says it takes 150mm RAM missiles, but it actually takes 158mm Rolling Airframe Missiles.

**Comment by VermillionX** [comment]
Fixed for next update
