### ISSUE TITLE
New CV Multi-Turret data missing

### ISSUE THREAD

**Issue by vixenfoxz** [RavienGaming/Reforged-Eden-2#234]
### Reforged Eden 2 Build Number

17

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

the drill option on the CV Multi-Turret is missing it just shows CV dampeners while the other 3 have data and descriptions, HV tool turrets display as intended

![20240720175805_1](https://github.com/user-attachments/assets/324b0f8c-9c81-46d4-ba52-635348ce5721)

**Comment by VermillionX** [comment]
Will return the drill turret and remove the function from the tool turret since the tool turret seems to be having compatibility issues.
