### ISSUE TITLE
Zirax Combat Shotgun Weapon Modding

### ISSUE THREAD

**Issue by DarkestWarrior** [RavienGaming/Reforged-Eden-2#235]
### Reforged Eden 2 Build Number

17

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

After exiting from the weapon locker when modifying a Zirax Combat Shotgun, get a CoQ error.

### Error code from console or log (Optional)

Return command found in state GS_WeaponBench_ShotgunZirax but stack is empty! NullReferenceException: Object reference not set to an instance of an object.

**Comment by VermillionX** [comment]
Tested modifying the Zirax Combat Shotgun.
Didn't get any errors.
Looked at the dialog for the weapon locker and there's no errors there. There isn't even a Return function used. There's a button labeled "Return" but it's just a straight link and works.

**Comment by DarkestWarrior** [comment]
I started up a fresh RE2 Beta scenario Build 17 and get the same error. So I am not sure what is going on.
![image](https://github.com/user-attachments/assets/8d1f94e3-8363-4a2b-a73b-7f562f5b4a52)
![image](https://github.com/user-attachments/assets/744b916c-01e3-4b44-85b3-a7e1813ad8fa)

And correction it is the Zirax Heavy Shotgun, not combat shotgun. Apologies for the incorrect name for the shotgun initially.

**Comment by VermillionX** [comment]
I see where the problem is happening now. Will fix it for next update.
