### ISSUE TITLE
Bandit and Raider insignias give opposite rewards

### ISSUE THREAD

**Issue by Garaman-EGS** [RavienGaming/Reforged-Eden-2#236]
### Reforged Eden 2 Build Number

17

### Game mode

Survival, Single Player, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Turning in a bandit insignia at a Colonist Scrapyard gives you the reward for turning in a raider insignia. Conversely, turning in a raider insignia gives you the reward for turning in a bandit insignia.

This is from the "Scrapper" trader in Eden_BAO_ColScrapYard

Bandit Insignia:
![20240720155941_1](https://github.com/user-attachments/assets/208ddc6a-c327-4741-a12f-f645dd320a68)

Trader prompt on accepting bandit insignia:
![20240720155950_1](https://github.com/user-attachments/assets/e8ccdd0b-9d86-4264-8607-b9fd1f50b0c1)

Trader reward for turning in bandit insignia:
![20240720155955_1](https://github.com/user-attachments/assets/d1473796-f5f1-41d3-88c5-d5faaa78131a)

Same 3 images, but for turning in a Raider insignia:
![20240720160029_1](https://github.com/user-attachments/assets/50c48bd6-4a6e-424c-8707-61325027b7f4)
![20240720160039_1](https://github.com/user-attachments/assets/7f025997-9433-4288-b79b-e1ec779a322e)
![20240720160043_1](https://github.com/user-attachments/assets/9c73d5d1-d040-401a-9ce7-0b7db3c12519)

### POI Name

Eden_BAO_ColScrapYard

### Playfield Class

Scrapyard

### Star Class

K6

**Comment by RavienGaming** [comment]
Thanks I know what the issue is and I'll get this fixed.
