### ISSUE TITLE
Dense Ice Harvesting not working

### ISSUE THREAD

**Issue by Grabber48** [RavienGaming/Reforged-Eden-2#237]
### Reforged Eden 2 Build Number

17

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Harvesting dense ice get no free storage capacity on a 0/320,00 harvest controller.

### Playfield Name

Sector Bagexra, playfield Epsilon 22276 V, playfield seed 950863

### Star Name

Bagexra

### Star Class

M5

**Comment by Grabber48** [comment]
Tried a different dense ice field in same sector and it worked ok so specific to playfield Epsilon 22276 v

**Comment by RavienGaming** [comment]
If you're looking in the box while it's trying to mine it can't deposit materials (same as any other drill). I will close this as being a technical issue as it's the way the game works.

**Comment by Grabber48** [comment]
Wasn't looking in the box until after the notification of no free space tried 3 asteroids all failed, warped to other ice field in same sector all dense ice harvested just as it did in all the many other sectors I had done.
-------- Original message --------From: RavienGaming ***@***.***> Date: 2024-07-20  11:05 p.m.  (GMT-05:00) To: RavienGaming/Reforged-Eden-2 ***@***.***> Cc: Grabber48 ***@***.***>, Author ***@***.***> Subject: Re: [RavienGaming/Reforged-Eden-2] Dense Ice Harvesting not working (Issue #237) 
Closed #237 as completed.

**Comment by RavienGaming** [comment]
Weird. Probably just general Empyrion jankiness then. Nothing I could fix on my end either way.
