### ISSUE TITLE
Auxiliary Augment quest typo 

### ISSUE THREAD

**Issue by Grumpy138** [RavienGaming/Reforged-Eden-2#238]
### Reforged Eden 2 Build Number

17

### Game mode

Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

![20240720033301_1](https://github.com/user-attachments/assets/1b5b5239-6c8a-4bec-803d-6a76dda5aebe)

**Comment by VermillionX** [comment]
Already fixed for next update.
