### ISSUE TITLE
Main story (and Polaris) missions cannot start if you spawned on a planet that doesn't give them on spawn

### ISSUE THREAD

**Issue by MattBradock** [RavienGaming/Reforged-Eden-2#240]
### Reforged Eden 2 Build Number

4480

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

The Polaris missions stay locked unless you get there in the story missions, but the story missions do not activate unless you started on a planet that has them enabled. In my case, I started on Uai, and once I completed the "Make contact with Terran forces" mission, I still had no access to the Polaris reputation grind mission (Fuel Delivery) or any POL mission for that matter. I tried to activate the story missions by entering multiple planets that have them (Akua, Haven, Omicron) but they stay locked.

### Mission Name

Prologue: Journey Into The Unknown, Chapter 1: Human Debris

### Game Seed

123344

**Comment by RavienGaming** [comment]
This is working as intended in the scenario.
