### ISSUE TITLE
Vendor not taking items

### ISSUE THREAD

**Issue by Ascii14** [RavienGaming/Reforged-Eden-2#241]
### Reforged Eden 2 Build Number

17

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Issue recently fixed with Polaris Flight Mechanic requesting items he sold.  Item request now changed to Small Plasma Jet Thruster.  On returning with these items he acknowledges quest completion pays sum of 250k but does not actually take to 5 SPJT's out of player inventory.  Reloaded till I got the same quest and same result.  Took items to another PFM who had issued this quest - same result.

### POI Name

CB802N

### Playfield Class

Multiple

### Star Name

Alpha

### Star Class

g

### Mission Name

N/A

### Mission Objective

Deliver 5 Small Plasma Jet Thrusters

### Game Seed

100013

**Comment by VermillionX** [comment]
Fixed in next update.
