### ISSUE TITLE
Getting an immense amount of errors on logging in

### ISSUE THREAD

**Issue by danielsolaro** [RavienGaming/Reforged-Eden-2#242]
### Reforged Eden 2 Build Number

17

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Logged in today on Anvil, an error message and console showing a list of errors adding new lines non- stop for a while... then it finished loading everything I guess (?) and stopped. Quit the game, restart everything, same on login. I can't move my view, can't change camera, I CAN change weapons on toolbar but they don't appear on the screen.. after errors stop I can finally see my ship and do any actions correctly.
It seems to be while things are loading, I'm on a polaris trade sector parked a meter away from a lambda station. Have a CV, multiple SVs, 1 HV.
![20240722040712_1](https://github.com/user-attachments/assets/d74fd400-cdbf-483a-b7b5-ad063f8f433f)
![20240722040726_1](https://github.com/user-attachments/assets/1bc9d9b7-05cc-41af-b094-f3b0fad10d5a)
![20240722043054_1](https://github.com/user-attachments/assets/e856d29f-3d6a-4628-8762-ed3ce7223166)
![20240722043100_1](https://github.com/user-attachments/assets/ce149af3-9fb3-41d9-bfa5-264095b198b4)

PS. One of the screenshots also show a line about Explore T3 playfield, thats another ticket I'm about to send :P

### Error code from console or log (Optional)

Formatting is all messed up, can I upload the file? Its basically the entire log, **line 240 onwards.**
[Client_240722-042219-56.log](https://github.com/user-attachments/files/16329645/Client_240722-042219-56.log)

### Playfield Name

Epsilon 10451 V

### Playfield Class

Polaris Trade Hub

### Star Name

Sabnebe

### Star Class

M4

**Comment by RavienGaming** [comment]
This is most likely a game bug, but I will leave it open in case anyone else experiences it so they can report it here since that POI is new. Not much I can do yet though as I've visited that station several times on a server and nothing like that has happened.

**Comment by danielsolaro** [comment]
Ì did visit it before too, and yesterday I used its teleporter to go around and come back. Had no issues. 
On the same line have been using my cv for a while , no new devices or new vessels attached.
Maybe some item is interfering? Or its the mission pda actually the cause of both issues?

I relogged to leave the system now that I got ur answer, but got stuck in an error loop I can't even move. Even the errors act a little different every time I log 🥴
I will try one more time and maybe ask an admin to move me somewhere else. Will return if error persists in another playfield.
![20240722054058_1](https://github.com/user-attachments/assets/ab29f7b7-a386-4c50-abf8-0cf6c31427d3)

**Comment by RavienGaming** [comment]
Shouldn't be anything with the PDA. That stage doesn't have any special PDA functions that aren't used in other missions.
Hope an admin can help you out.

**Comment by danielsolaro** [comment]
back, admin helped, apparently all I needed was to uncheck the "open on exceptions" and I could move again 🤡
It just threw the key error on console but no NRE, No error dialogs. 

Does that key number at the message help for anything?
![20240722094418_1](https://github.com/user-attachments/assets/b9b2c3c2-12fb-4c86-8bee-e3c70933efcb)

**Comment by RavienGaming** [comment]
That key is usually about a trader that has a duplicate item. It might be something unrelated to the other errors you experienced.

**Comment by RavienGaming** [comment]
I will go ahead and close this issue as I have not seen anyone else with the same issue so far.
If it happens again please feel free to open a new issue.
