### ISSUE TITLE
Game breaking : SV gatling cannons create a looping error when placing in your hot bar in creative and survival.

### ISSUE THREAD

**Issue by Helioflux77** [RavienGaming/Reforged-Eden-2#244]
### Reforged Eden 2 Build Number

18

### Game mode

Creative

### Tested in vanilla

Issue does not happen in vanilla

### Description of issue

On a new RE2 creative game, as well as an existing survival RE2 game, I load SV light, medium, heavy gatling weapons into my hot bar (no vehicle spawned in yet). I immediately get a looping error. Recreated every time. Does not happen with laser or plasma weapons.

### Error code from console or log (Optional)

![Screenshot 2024-07-23 001046](https://github.com/user-attachments/assets/454be28b-7add-44e3-b38b-623e8e3ef52f)

**Comment by RavienGaming** [comment]
This had already been fixed as of the hotfix about 5 hours ago.
Validate files in Steam and/or unsub/resub to the scenario to get the update.

**Comment by Helioflux77** [comment]
I will have to verify/ resub before posting if I ever find a big bug again. Just in case I am missing a file. Thanks.
