### ISSUE TITLE
Bugged Micro-Warp 

### ISSUE THREAD

**Issue by GSMonroe** [RavienGaming/Reforged-Eden-2#245]
### Reforged Eden 2 Build Number

1.11.7 4880

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

In Spanj Broken Eden RE2 Server, I tried the Micro-Warp mission. I put 1 refined pentaxid in my personal inventory and activated the mission. There was a 10 sec countdown, and then a popup message telling me I needed to have 1 refined pentaxid in my personal inventory. I've lost 3 refined pentaxid so far, yet I have not warped.

**Comment by RavienGaming** [comment]
As a work around for now as long as you have more than 1 refined pentaxid in your inventory when you start the warp it should work.
Fixed for next update.

**Comment by RavienGaming** [comment]
As of the latest scenario update Build 19 the process of using the micro jump drive has changed so this is now fixed.
