### ISSUE TITLE
Some SV/HV Cockpits have wrong CPU cost

### ISSUE THREAD

**Issue by Garaman-EGS** [RavienGaming/Reforged-Eden-2#246]
### Reforged Eden 2 Build Number

18

### Game mode

Survival, Creative, Single Player, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

- "Cockpit 2" and "Cockpit 2 (Armored)" have a 0 CPU cost, whereas the others have a 25-point cost (tooltip + installed).
- "Cockpit 2 (open)" does not list a CPU cost on the tooltip, but results in a 24-point cost when installed.
- "Cockpit 1 (open)" only costs 20 CPU points (tooltip + installed).

Cockpit 2:
![20240724002715_1](https://github.com/user-attachments/assets/d1dce7ad-dc89-40d4-817b-7f70907f8253)

Cockpit 2 (Armored):
![20240724002809_1](https://github.com/user-attachments/assets/1f5268fa-e9dc-4093-a555-ce2df20c2899)

Cockpit 2 (Open):
![20240724002750_1](https://github.com/user-attachments/assets/0dc868ef-432d-4b88-9c5f-596cecd92edb)

Cockpit 1 (Open):
![20240724003815_1](https://github.com/user-attachments/assets/9e6f7880-d4ea-46d0-9a00-811948385a97)

**Comment by VermillionX** [comment]
Fixed for next update
