### ISSUE TITLE
Ammo controler explosivity

### ISSUE THREAD

**Issue by Shandril79** [RavienGaming/Reforged-Eden-2#247]
### Reforged Eden 2 Build Number

18

### Game mode

Creative, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

While testing devices I discovered the ammunition controller when exploding is doing enough damage to destroy full steel blocks, around 6100 damage to hardened steel blocks. When queried on forums, Vermillion stated it should be doing 4500 damage to full steel blocks.

**Comment by VermillionX** [comment]
Fixed for next update
