### ISSUE TITLE
Crossbow not showed on weapon locker to mod

### ISSUE THREAD

**Issue by danielsolaro** [RavienGaming/Reforged-Eden-2#249]
### Reforged Eden 2 Build Number

18

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Talon trapper trader sells crossbow and crossbow specific mod, but talking to weapon locker I don't see the crossbow on any category of weapon. I have it in hands.

**Comment by VermillionX** [comment]
Fixed for next update
