### ISSUE TITLE
Error when reinforcements arrive

### ISSUE THREAD

**Issue by Dadrick42** [RavienGaming/Reforged-Eden-2#25]
### Reforged Eden 2 Build Number

1.11.6 4471 RE2 Build 1

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Continuous error dialogue box occurs when a poi calls in reinforcements.

### POI Name

[Zirax] Orbital Outpost

**Comment by RavienGaming** [comment]
Thanks for the report, going to need the RE2 build number as well as the POI and playfield and star info if you could either respond with that here in a comment or start a new report if that's easier for you.

**Comment by RavienGaming** [comment]
Also what faction it is (I assume Zirax).

**Comment by Dadrick42** [comment]
RE2 Build 1 and it's a Zirax Orbital Outpost

**Comment by RavienGaming** [comment]
> RE2 Build 1 and it's a Zirax Orbital Outpost

What playfield type and star type? I looked through the standard orbits and couldn't find anything wrong with the configs in them so it would help narrow down the issue.

**Comment by Dadrick42** [comment]
Sorry but I deleted the save because it would go into an error loop when loaded into. I've tried reproducing the issue this evening. I wasn't able to find a Zirax station that would call in reinforcements.

**Comment by RavienGaming** [comment]
Thanks for trying to check. I'll keep this open and if you find it happen again just let me know.
I'll try to test it myself as well.

**Comment by RavienGaming** [comment]
I'm going to close this. If it happens again please feel free to open a new ticket.
