### ISSUE TITLE
CV Multitool Drill mode doesn't mine Tungsten asteroids

### ISSUE THREAD

**Issue by StHotPants** [RavienGaming/Reforged-Eden-2#253]
### Reforged Eden 2 Build Number

RE2 Beta Build 19

### Game mode

Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Attempting to mine a Tungsten Asteroid with a CV Multitool while in Drill mode (top selection) and get error that this mode is unable to mine the resource:
![image](https://github.com/user-attachments/assets/ca299ec8-de46-4caa-b37e-5e71a193be93)

I can switch to Retrieve Blocks mode and it will "take" the Tungsten nodules off the asteroid but they do not appear as harvested resources in my harvest controller

### POI Name

Tungsten Asteroid

**Comment by RavienGaming** [comment]
This issue has already been reported here: #22
