### ISSUE TITLE
CV Multitool Drill mode missing labeling and description in menu

### ISSUE THREAD

**Issue by StHotPants** [RavienGaming/Reforged-Eden-2#254]
### Reforged Eden 2 Build Number

RE2 Beta Build 19

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

When using a CV Multitool the right click menu top option does not list any details and is not labeled as the "drill" mode:
![image](https://github.com/user-attachments/assets/c6d4ca25-d387-4eef-8d98-dec4893ae593)

Compared to other right click modes which have labels and details:
![image](https://github.com/user-attachments/assets/2659cdcc-bfaa-422c-abb6-4b1e39769682)

**Comment by RavienGaming** [comment]
Which exact turret type? Do you mind using the di command and looking at the block so I can see which one it is since there are 4 different ones and I thought I had fixed them all.

**Comment by StHotPants** [comment]
Sorry it's so small, I don't know how to increase the size
![image](https://github.com/user-attachments/assets/81ec7dd1-fc87-4a0b-b97c-5a68f1448f3e)

**Comment by RavienGaming** [comment]
I was not able to reproduce. Shows fine on my end in both my internal and the workshop version of RE2.
