### ISSUE TITLE
Micro Jump Drive

### ISSUE THREAD

**Issue by Grumpy138** [RavienGaming/Reforged-Eden-2#256]
### Reforged Eden 2 Build Number

19

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Unable to use jump drive.
![20240729223148_1](https://github.com/user-attachments/assets/8d5606b9-6d50-4641-b1ba-4df0370d1cb6)
![20240729223256_1](https://github.com/user-attachments/assets/d3727560-09c4-4800-9024-9e7a6ab5fd40)

**Comment by RavienGaming** [comment]
Try this console command:
**pda readdata**

Then restart your game completely, then load the game and immediately attempt to jump again **without changing playfields**.

And just to double check you are:

1. In the pilot seat of a CV or SV.
2. The ship has power.
3. The ship is not docked to anything else.
4. In a space playfield.

One more thing to check: is your Core renamed in the control panel by chance? Or is it still called Core.
Sorry, just trying to think of different reasons why.

**Comment by RavienGaming** [comment]
If you've checked all those things and it's still not working can you share a blueprint of the current ship you're trying to use on the Steam workshop and post a link to it here please so I can try using your exact same ship?

**Comment by Grumpy138** [comment]
I logged in today and it let me jump until I changed playfields, then I relogged and it let me jump again.  Don't know why it wouldn't let me do it yesterday after relogging.

**Comment by RavienGaming** [comment]
Glad it's working now! Probably just general Empyrion wonkiness. I will go ahead and close the issue then.
