### ISSUE TITLE
Zirax Bunker shutter doors wont stay open

### ISSUE THREAD

**Issue by Tar-egs** [RavienGaming/Reforged-Eden-2#257]
### Reforged Eden 2 Build Number

build 19

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

on the floor where the core is located, you get a code to open some shutter doors. but when flipping the lever, the shutters are instantly opened and starts closing again, and the distance seems too far to be intended(signal is set to toggle).
![20240730223129_1](https://github.com/user-attachments/assets/7560943c-3388-46d0-9499-874900883d3d)
![20240730223140_1](https://github.com/user-attachments/assets/c0424833-f01c-401c-99e2-caf6448be365)

### POI Name

[Zirax] Bunker

### Playfield Class

Fungal planet

### Star Name

Belpho

### Star Class

F

**Comment by VermillionX** [comment]
You might need to toggle the switch a couple of times because signal logic is unreliable in MP sometimes.

**Comment by Tar-egs** [comment]
it would seem that its the Toggle signal logic thats broken on anvil server. sorry for wasting your time
