### ISSUE TITLE
Real Rock 10, Unnamed rock formation.

### ISSUE THREAD

**Issue by Bufficorn** [RavienGaming/Reforged-Eden-2#258]
### Reforged Eden 2 Build Number

19

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Real Rock 10 hasn't been renamed like the other Basalt and granite stones nearby. This stone matches the texture on the granite rocks when finding them next to each other so I assume it is just an overlooked name change. Not a big issue just figured id post it as I don't see a report for it yet. I've broken around 25 or so to test drop rates and they only seem to drop stone if the formations have different loot tables to consider.

![image_2024-08-02_183907047](https://github.com/user-attachments/assets/06f11df3-c6bc-435c-964d-32c56eb0e169)

*The rock formation behind Real Rock 10 is Granite Extrusion for comparing their textures. Coordinates -2617, 226, 707 on the attached seed if it is needed*

### Game Seed

3143225812

**Comment by VermillionX** [comment]
Name added for next update.
