### ISSUE TITLE
Harvest controller maximum capacity does not match the maximum capacity of cargo containers.

### ISSUE THREAD

**Issue by 8836290** [RavienGaming/Reforged-Eden-2#259]
### Reforged Eden 2 Build Number

Reforged Eden 2 Beta: (Build 19)

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

The maximum capacity of harvest controllers remains on 32k and 320k respectively no matter the number of container extensions installed. If for example, a cargo container controller with maximum capacity of 640k , is replaced with a harvest controller the player finds out the harvest container capacity drops to 320k. Same applies for SV controllers.

**Comment by treker-ed** [comment]
Harvest controllers are 32k for SV/HV and 320k max for CV/BA within RE2 (and exactly the same within RE1). They have never been anything larger. Similarly, Ammo controllers are the same sizes. Container Controllers are 64k and 640k max respectively. If you have a container array at 64k on an SV/HV or 640k on a CV/BA and replace them with a harvest controller, they will not use the amount that was there for the container controller, they will drop down to the max size for the harvest or ammo controller ie 32k (SV/HV) or 320k (CV/BA) no matter how many cargo extensions there are.

**Comment by 8836290** [comment]
Ok I thought it was a bug or something neglected.
