### ISSUE TITLE
R2BAO_AsteroidMine02, R2BAO_AsteroidMine04, R2BAO_AsteroidMine04 access door is not player accessible

### ISSUE THREAD

**Issue by Ishantil** [RavienGaming/Reforged-Eden-2#26]
### Reforged Eden 2 Build Number

RE2 Build 1 (April 29)

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

R2BAO_AsteroidMine02, 03, 04 access door is not player accessible.  Recommend checking -01 as well.  Although we cannot confirmm

**Comment by RavienGaming** [comment]
Thanks will take a look. It's possible those should be locked as they aren't trading stations.

**Comment by Ishantil** [comment]
We thought they should be open since the stations themselves have vendors.

--------------------------------
Matthew D. Cleveland

**Comment by RavienGaming** [comment]
Thanks. Yup this design was taken from vanilla and it's broken there too.
We'll get this fixed for RE2.
