### ISSUE TITLE
Can't pass mission after accidentally destroyed quest object by NPC's

### ISSUE THREAD

**Issue by kisame1313** [RavienGaming/Reforged-Eden-2#261]
### Reforged Eden 2 Build Number

19

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Hello. Me and my friend playing this Scenario on private dedicated server. We started on Alpha -> Akua. He's ran some main quests before me. On the quest "Recent History" Zirak empire soldiers were ambushed him. One of the rocket launcher enemies destroyed 
wall with the red terminal. Now I can't pass this quest further. Is there some ways to respawn new Ancient Tower or add this possibility to the game? If there are some solutions, I didn't found them in PDA or Scenario info on Workshop. Thank you 

### POI Name

Ancient Tower

### Playfield Name

Akua

### Playfield Class

Temperate Starter

### Star Name

Alpha

### Star Class

GStartingSystem

### Mission Name

Recent History

### Mission Objective

Access the Red Console

### Game Seed

7600566

**Comment by VermillionX** [comment]
You should be able to open your PDA (f1), select the mission and the current objective and click the checkbox to manually complete the task.

**Comment by kisame1313** [comment]
> You should be able to open your PDA (f1), select the mission and the current objective and click the checkbox to manually complete the task.

Yes, It works. Thank you. 
But anyway I missed interesting part of the story. So I'd prefer to add possibility to fix and restart current task with it's POI's. In the future, of course. 
Thank you again
