### ISSUE TITLE
Legacy Matter Converters do not have shields

### ISSUE THREAD

**Issue by Garaman-EGS** [RavienGaming/Reforged-Eden-2#263]
### Reforged Eden 2 Build Number

19

### Game mode

Survival, Single Player, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

The Legacy Matter Converter POI (R2BAO_MatterConverter01) spawns without a shield generator. I have observed this in Alien Asteroid Field sectors around BH and R stars. I assume as they were shielded in RE1 that they would also be shielded in RE2.

![20240805020517_1](https://github.com/user-attachments/assets/c524d315-d7c5-4e4f-8936-f81fdbf9b30c)

### POI Name

Matter Converter

### Playfield Class

Alien Asteroid Field

### Star Class

BH

**Comment by VermillionX** [comment]
Fixed in next update with new weapon arrangements that aren't stuck to the inside of the shell.
