### ISSUE TITLE
Drone Sector: Drone Assembly POI Stations

### ISSUE THREAD

**Issue by Chumsickle** [RavienGaming/Reforged-Eden-2#264]
### Reforged Eden 2 Build Number

19

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

When attacking Drone Stations, specifically the Assembler, it appears that the rock that forms its outer shell is invincible.  Over 5k missiles were used to attack ones generators and no dent was made.

### POI Name

Drone Assembly

**Comment by RavienGaming** [comment]
This is to prevent people from drilling into it with drills to bypass its armor. For some of them you may need to destroy the turrets and then go in on foot to take out the core (they have a few, but weak, interior defenses).

**Comment by Chumsickle** [comment]
Thank you for the response.  Not what I hoped, but makes sense.
