### ISSUE TITLE
Solaris AMP Vendor

### ISSUE THREAD

**Issue by BloodAngel099** [RavienGaming/Reforged-Eden-2#266]
### Reforged Eden 2 Build Number

19

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

I posted awhile back on the workshop page about not being able to find the Solaris AMP vendor. I never did find him I just moved on and got my reactor cores from somewhere else. I need this vendor now and cant find them. I eventually went into GM IV and was able to set him to show on hud local and thats when I found out that the vendor isnt rendering at all. All I see is a Trade Federation word floating in mid air. This has happened at two different Solaris AMP Factories for me.

### POI Name

Solaris AMP Factory

**Comment by BloodAngel099** [comment]
I did just figure out how to regenerate the poi which seems to have fixed the problem. Leaving this here just in can anyone else has this problem.

**Comment by RavienGaming** [comment]
This is likely a game bug and will need to be reproduced and reported using a vanilla save game.
When reproducing a game bug in a vanilla save, make sure you are using the same mode _(singleplayer/co-op/dedicated multiplayer, survival/creative)_ as what you were using when the issue happened in the scenario.
To see a list of known game bugs or to report a new one please see: https://empyriononline.com/forums/bugs.24/
