### ISSUE TITLE
Temporary Drone Base on Omicron approach crashes

### ISSUE THREAD

**Issue by catequilsrl** [RavienGaming/Reforged-Eden-2#267]
### Reforged Eden 2 Build Number

19

### Game mode

Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

When I approach the Temporary Drone Base on omicron I get an error message.
![RE2 - Omicron_2024-08-09_21-57-11](https://github.com/user-attachments/assets/172235a0-9745-4f40-82bb-fe63e2adc040)

### Error code from console or log (Optional)

See uploaded image for console error

### POI Name

Temporary Drone Base

### Playfield Name

Omicron

**Comment by RavienGaming** [comment]
Does this still happen to you or anyone else? I was not able to reproduce the issue.

**Comment by RavienGaming** [comment]
I will close this issue for now.
If it happens to you again please feel free to re-open the issue, but this may be fixed in an upcoming game update.
