### ISSUE TITLE
Mining Promethium on Akua Moon looks like graphite

### ISSUE THREAD

**Issue by mgwrites** [RavienGaming/Reforged-Eden-2#269]
### Reforged Eden 2 Build Number

19

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

When I mine Promethium on Akua moon it looks like graphite. Tried to mine multiple locations of Promethium. Same issue in all cases. The other ores appear as expected. 

![akua moon mining](https://github.com/user-attachments/assets/40e4fc26-ac5f-49fd-896c-2612878e6516)

### Playfield Name

Akua Moon

### Game Seed

578227

**Comment by mgwrites** [comment]
Instead of graphite, the promethium may look like Aluminum or the aluminum looks like graphite too. Still on Akua Moon

![20240812125413_1](https://github.com/user-attachments/assets/830b74d8-c9d6-41f0-bf8d-3adfcd1e87be)

**Comment by RavienGaming** [comment]
Technical visual issue due to running out of texture slots.
