### ISSUE TITLE
"Light Shotgun Receiver" Mod Lacking Accuracy Bonus

### ISSUE THREAD

**Issue by Lithoboli** [RavienGaming/Reforged-Eden-2#27]
### Reforged Eden 2 Build Number

1

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

"Light Shotgun Receiver" mod (Token 53) does not apply the listed accuracy bonus to weapons.
Tested on all four RG2 shotguns.

**Comment by VermillionX** [comment]
Shotguns have two accuracy statistics. One for bulletspread and one for rayspread. Shotguns display rayspread on their tool tip, while all other weapons use and display BulletSpread. The accuracy bonus applied by weapon mods affects the BulletSpread.
This will probably be changed in the next update.
