### ISSUE TITLE
Salvage Operation POI spawns with sentries under terrain

### ISSUE THREAD

**Issue by suntrip76** [RavienGaming/Reforged-Eden-2#271]
### Reforged Eden 2 Build Number

B19

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Salvage Operation POI sometimes spawns with three of the outer sentry turrets hidden just below terrain meaning that they can shoot you, but not the other way around.

### POI Name

Eden_BA_ZrxSalvageOp

### Playfield Name

Eviian

### Playfield Class

Mire

### Star Name

Balamath

### Game Seed

World 489834 - Playfield 720372

**Comment by RavienGaming** [comment]
Thanks, old POI. Removed for next update.
