### ISSUE TITLE
Savegame will not load

### ISSUE THREAD

**Issue by FUsIon80** [RavienGaming/Reforged-Eden-2#272]
### Reforged Eden 2 Build Number

Reforged Eden 2 Beta (build 19)

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

After loading structures, game don´t react anymore ... have to kill the task (but Empyrion.exe still taking system ressources like 6% cpu)

### Error code from console or log (Optional)

13-15:56:50.630 17_56 -ERR- Error when reading biome data file 'C:\Program Files (x86)\Steam\steamapps\common\Empyrion - Galactic Survival\Client/../Saves/Cache/Eden 2 - Akua/Playfields/Akua/biomes.dat'. Biome with id 0 not found (index=2097151). Only first error is reported!
Shader 'MicroSplat/Planet': dependency 'BaseMapShader' shader 'Hidden/MicroSplat/Planet_Base1207366470' not found
[Decoration] Start Loading Deco Presets None
Lakes:79, Shores:38194/1,122551
13-15:56:59.509 17_56 -ERR- 64 Losing data when packing (5060, -2147483648, 9) (PA)
...

**Comment by RavienGaming** [comment]
This is likely a game bug and will need to be reproduced and reported using a vanilla save game.
When reproducing a game bug in a vanilla save, make sure you are using the same mode _(singleplayer/co-op/dedicated multiplayer, survival/creative)_ as what you were using when the issue happened in the scenario.
To see a list of known game bugs or to report a new one please see: https://empyriononline.com/forums/bugs.24/

**Comment by FUsIon80** [comment]
Save Games with the same Mode don't have a Problem to Launch...

**Comment by RavienGaming** [comment]
> Save Games with the same Mode don't have a Problem to Launch...

Unfortunately it would need to be reproduced in vanilla before it could be reported to the developers.
Errors with game files such as .dat files would likely be due to a game bug, not a scenario issue.

There is nothing I can do about this I am afraid.

**Comment by FUsIon80** [comment]
***@***.***

Von: RavienGaming ***@***.***>
Gesendet: Dienstag, 13. August 2024 23:21
An: RavienGaming/Reforged-Eden-2 ***@***.***>
Cc: FUsIon80 ***@***.***>; Author ***@***.***>
Betreff: Re: [RavienGaming/Reforged-Eden-2] Savegame will not load (Issue #272)


Save Games with the same Mode don't have a Problem to Launch...

Unfortunately it would need to be reproduced in vanilla before it could be reported to the developers.
Errors with game files such as .dat files would likely be due to a game bug, not a scenario issue.

There is nothing I can do about this I am afraid.
