### ISSUE TITLE
Probe scanning and server ban

### ISSUE THREAD

**Issue by Deadzone006** [RavienGaming/Reforged-Eden-2#273]
### Reforged Eden 2 Build Number

7.77.7 4480 14-04:06

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

I was in a tier 3 exploration site, the one where you find the Polaris freighter adrift. You have to find the crew and their escape pods. I was doing the fine scanning using the system probes. I did not realize I was linked to a cargo container. After the scan, the coordinates ended up in the cargo. I moved them to my hotbar, seeing if I could use them. Nothing happened.  I then dropped the coords into my personal inventory. I heard the audio cue that the mission had been updated with a "ding", but the game them immediately booted me and got a message that I had been banned for 1 year. I was not running anything else in the background. Just the game. 
Member of "SDGamers" said he had heard of that happening before.

### Error code from console or log (Optional)

No error code was given. Just a message that I had been banned from the server.

### POI Name

Polari Freighter

### Playfield Name

Heeron Chi

### Playfield Class

Exploration site-space

### Star Name

Malera

### Star Class

K4

### Mission Name

Eden Space_POI_3_explore_T3

### Mission Objective

Recover the crew in their escape pods

### Game Seed

3527951

**Comment by RavienGaming** [comment]
This is a server configuration issue. The admins need to make exceptions to the item ban list in EAH or whatever server management system they use to exclude items from the ban list. The item in question is a vanilla item however called Token so not sure why that would ban you.

Or if you attempted to use console commands that would ban you too.

Could be a weird game bug too of course.

Either way this is a server issue and you'd need to contact the server admins of the server you play on to get yourself unbanned.
