### ISSUE TITLE
CV control stations have odd unlisted CPU costs

### ISSUE THREAD

**Issue by Garaman-EGS** [RavienGaming/Reforged-Eden-2#274]
### Reforged Eden 2 Build Number

19

### Game mode

Survival, Creative

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

CV control stations do not list a CPU point cost, but show the following odd costs on the CPU statistics page:
- Captain's chair: 17
- Cockpit 1: 27
- Cockpit 2: 0
- Cockpit 3: 27

**Comment by VermillionX** [comment]
Fixed for next update
