### ISSUE TITLE
Black Cult Temple of Rebirth Core Issue

### ISSUE THREAD

**Issue by mkarbowski-quilt** [RavienGaming/Reforged-Eden-2#275]
### Reforged Eden 2 Build Number

19

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Flipping both overdrive switches triggers the explosive blocks to destroy the core, however there is no prior mechanic to remove the shield generator, so the cores remain intact.

### POI Name

Black Cult Temple of Rebirt

**Comment by RavienGaming** [comment]
What planet type was this on?

**Comment by heyitsmk** [comment]
Swamp

**Comment by RavienGaming** [comment]
I just verified all playfields. All black cultist POIs are configured to not recharge their shields once it is brought down.
You will need to contact your server admins for this issue as it would either be due to a playfield that had been generated before the update that fixed this issue, or the server is using outdated playfield files.

**Comment by heyitsmk** [comment]
Ok so its intended that if you do the POI without taking down the shields it cannot be completed without manually blowing stuff up.

**Comment by RavienGaming** [comment]
Yes, like any other POI you need to take down the shields first using some kind of ship mounted weapon. Once you bring the shields to 0% they will no longer recharge on the black cultist POIs specifically.
I will go ahead and close this issue now.

**Comment by RedScourge** [comment]
I just experienced this on my server, which was wiped on Nov 21 using the latest playfield files. It was an Alien planet, I did not see any signal logic indicating that the shields needed to be down in order to flip the switches.

**Comment by CarlosAmericano** [comment]
This is still broken, I just had this issue on a swamp planet (Cianualia planet, Voralech System)
The POI had no outside shield to drain and after flipping the core switches they wouldnt blow up.

This was on a single player, RE2 build 45, base game v1.16

**Comment by RavienGaming** [comment]
> This is still broken, I just had this issue on a swamp planet (Cianualia planet, Voralech System) The POI had no outside shield to drain and after flipping the core switches they wouldnt blow up.
> 
> This was on a single player, RE2 build 45, base game v1.16

You need to take down the shields before you go inside. If you don't fully deplete the shield, then it will begin to recharge after not taking damage for a period of time.

This POI might let you go inside without first draining the shields, but you're going to have a bad time. You have to first attack it and take down the shields, then once the shields are down they won't recharge themselves and you're free to raid the interior of the POI.
