### ISSUE TITLE
Unique weapon repair dialog error

### ISSUE THREAD

**Issue by AlexS-empyrion** [RavienGaming/Reforged-Eden-2#276]
### Reforged Eden 2 Build Number

19

### Game mode

Single Player, Dedicated Server

### Tested in vanilla

Issue does not happen in vanilla

### Description of issue

Error in unique weapon repairing dialog causing weapon not repaired:
Dialogue cannot find item with name 'RepairTarget'

### Error code from console or log (Optional)

15-21:00:08.633 00_00 -ERR- Dialogue cannot find item with name 'RepairTarget'
15-21:00:11.420 00_00 -ERR- Dialogue cannot find item with name 'RepairTarget'

**Comment by RavienGaming** [comment]
What exact weapon are you trying to repair?

**Comment by AlexS-empyrion** [comment]
I've tried with Assault Shotgun and Pulse Rifle.
Seems dialog system doesn't read variable value and think of it's name as item name.

**Comment by RavienGaming** [comment]
Can you also include the exact POI name please as that will help narrow down which trader has the issue.

**Comment by VermillionX** [comment]
Fixed for next update.

**Comment by AlexS-empyrion** [comment]
> Can you also include the exact POI name please as that will help narrow down which trader has the issue.
[Polaris]Trade Station Iota.
Trader is: Auxiliary Augments.
And I think second one have same issue.



> Fixed for next update.
Thanks!
