### ISSUE TITLE
Sector Command Shield

### ISSUE THREAD

**Issue by Achannii** [RavienGaming/Reforged-Eden-2#277]
### Reforged Eden 2 Build Number

19

### Game mode

Single Player, Co-op

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Sector Command console in shield generator room labeled "Shield Generator" does not disable shield. Went into God mode to view signals. Signal assigned to console is "LockdownTop" and is only assigned to a few spawners but not the shield generator itself. Shield continues to regen unless a turret is set to auto shoot at the base for the entire duration of the raid.

### POI Name

Sector Command.

### Playfield Name

XDUO 27767 III

### Playfield Class

White Desert

### Star Name

Duvago

### Star Class

K

### Game Seed

621941

**Comment by VermillionX** [comment]
Already fixed for next update
