### ISSUE TITLE
Found RE1 Imerat Class Destroyer In RE2 Trade Sector

### ISSUE THREAD

**Issue by CrazyGamer9191** [RavienGaming/Reforged-Eden-2#278]
### Reforged Eden 2 Build Number

19

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

I went to  Zrax Trading Station Sector in the Nectric Expanse region it had a Imerat ship that looked odd and only had one core.

### POI Name

Trading Station Pharos

### Playfield Name

Aevae

### Playfield Class

Trading Sector Zrax

### Star Name

Caimi Beta

### Star Class

D

### Game Seed

919

**Comment by RavienGaming** [comment]
Thanks. Fixed this and the Polaris one for next update.
