### ISSUE TITLE
Polaris Reputation may not be working as intended

### ISSUE THREAD

**Issue by StHotPants** [RavienGaming/Reforged-Eden-2#280]
### Reforged Eden 2 Build Number

RE2 Beta Build 20

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Reviewed Polaris Reputation guidance in FACTIONS tab:
![image](https://github.com/user-attachments/assets/d12c2b57-7518-4132-a04d-fac72fcdb87a)

Went to Polaris space in a White Satellite zone and went to one of the Polaris Secure Supply Cache POI's. Saw that the external door was damaged but gave me "Access Denied". I put an Explosive Charge on the door to blow it open. When the charge went off my Polaris reputation dropped over 12,000 points instead of the -300 associated with destroying a block or device (could have multiple blocks destroyed but I couldn't stick around and check because of the massive reputation loss that dropped me 575 points below Neutral into Hostile. 

Also, the "get to neutral" reputation quest has been removed from game because of the "lessening" of the reputation impacts which do not appear to be working as intended.

**Comment by RavienGaming** [comment]
Intended. Different blocks have different reputation penalties. Doors protect core-override systems or other vital parts of a POI so they give a large penalty for destruction.
See the PDA for details on reputation.
