### ISSUE TITLE
T3 exploration site freighter has all doors set to private

### ISSUE THREAD

**Issue by Ente2k** [RavienGaming/Reforged-Eden-2#283]
### Reforged Eden 2 Build Number

20

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

T3 exploration site freighter has all doors set to private, should be set to public (is just annoying otherwise)

**Comment by RavienGaming** [comment]
Will get this fixed for the next update. Thanks!
