### ISSUE TITLE
Crash to desktop

### ISSUE THREAD

**Issue by Orric** [RavienGaming/Reforged-Eden-2#284]
### Reforged Eden 2 Build Number

Beta Build 20

### Game mode

Survival, Single Player

### Tested in vanilla

Issue does not happen in vanilla

### Description of issue

On an intermittent basis I'm seeing a crash to desktop - it "feels" like it's when something is being spawned in - but even happens when the game is paused - which is odd. I've added some of the data from the crash report below. Doesn't seem to matter which playfield, what's going on etc. sometimes in POIs sometimes just flying along, one time just sat next to one of the UCH ships doing nothing

### Error code from console or log (Optional)

C:\Windows\SYSTEM32\CoreUIComponents.dll:CoreUIComponents.dll (00007FF808C00000), size: 3592192 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\CoreUIComponents.dll', fileVersion: 10.0.22621.3672
C:\Windows\SYSTEM32\dbghelp.dll:dbghelp.dll (00007FF80E480000), size: 2301952 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\dbghelp.dll', fileVersion: 10.0.22621.3593
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFFA46B718C)
0x00007FFFA46B718C (UnityPlayer) (function-name not available)
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFFA46B22CD)
0x00007FFFA46B22CD (UnityPlayer) (function-name not available)
0x00007FFFA498FCFA (UnityPlayer) UnityMain
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFFA4617D26)
0x00007FFFA4617D26 (UnityPlayer) (function-name not available)
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFFA460DD7E)
0x00007FFFA460DD7E (UnityPlayer) (function-name not available)
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFFA45BAFBC)
0x00007FFFA45BAFBC (UnityPlayer) (function-name not available)
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFFA43D35AE)
0x00007FFFA43D35AE (UnityPlayer) (function-name not available)
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFFA433E7EC)
0x00007FFFA433E7EC (UnityPlayer) (function-name not available)
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFFA433EDC1)
0x00007FFFA433EDC1 (UnityPlayer) (function-name not available)
0x00007FFFA49A3B26 (UnityPlayer) UnityMain
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFFA45270E4)
0x00007FFFA45270E4 (UnityPlayer) (function-name not available)
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFFA4527591)
0x00007FFFA4527591 (UnityPlayer) (function-name not available)
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFFA4527614)
0x00007FFFA4527614 (UnityPlayer) (function-name not available)
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFFA4668AA3)
0x00007FFFA4668AA3 (UnityPlayer) (function-name not available)
0x00007FF81251257D (KERNEL32) BaseThreadInitThunk
0x00007FF81396AF28 (ntdll) RtlUserThreadStart

### POI Name

Everywhere

### Playfield Name

Everywhere

**Comment by RavienGaming** [comment]
This is likely a game bug and will need to be reproduced and reported using a vanilla save game.
When reproducing a game bug in a vanilla save, make sure you are using the same mode _(singleplayer/co-op/dedicated multiplayer, survival/creative)_ as what you were using when the issue happened in the scenario.
To see a list of known game bugs or to report a new one please see: https://empyriononline.com/forums/bugs.24/
