### ISSUE TITLE
Bandits not showing up for tripped alarms

### ISSUE THREAD

**Issue by Boyled10** [RavienGaming/Reforged-Eden-2#286]
### Reforged Eden 2 Build Number

20

### Game mode

Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

I am not getting bandit ships when I trip an alarm at space wreckage. I get the alarm warning and can hear the radio chatter but the ships never show up.

### POI Name

any space wreckage with a trip alarm.

### Game Seed

166662

**Comment by RavienGaming** [comment]
Which trap? Is it the emergency beacon where IDA warns you of an trap and you have the option to go through with it to spawn patrol vessels or cancel, or the trap that happens automatically that spawns bandit drones?

**Comment by Boyled10** [comment]
It's the traps that happen automatically that spawn bandit drones.  The trigger warning happens and also some text from the bandits but the drones never spawn.
________________________________

**Comment by Boyled10** [comment]
Has happened to me every time specifically on POI Eden_BAOJ_JunkT2_26   Wrecked Naginata DDG.
________________________________

**Comment by RavienGaming** [comment]
If the AI is turned off the drones will not spawn.

See #15

**Comment by Boyled10** [comment]
I don't think the AI is off.  Enemy ships and drones in the playfield are moving and attack normally.  Also, this type of encounter requires no manual response to the dialogue, as described in #15.
________________________________

**Comment by RavienGaming** [comment]
Oh I bet you just didn't notice they spawned then. Drones spawned via the PDA do not attack due to a game bug so if they fly off you wouldn't notice them. I'll go ahead and close this as it's a game bug either way. Thanks for reporting it though.
