### ISSUE TITLE
FYI Omicron start allows unplayable Seige Drone Gunship situation to develope

### ISSUE THREAD

**Issue by zombienumber9** [RavienGaming/Reforged-Eden-2#287]
### Reforged Eden 2 Build Number

20

### Game mode

Survival

### Tested in vanilla

Issue does not happen in vanilla

### Description of issue

Why bug report? no biggie just FYI / feedback so you know, as its a gamestopper. Maybe solution is simply specific text warning of advanced weapon attacks on Omicron in the start description, in RE2, so players know to be ready, will also add glamour! Omicron is unbreathable, which I like but current description appears to be about that.

This is probably happening because Eleon made Omicron not a starter planet any more so its base attack spawns are advanced and not like a lazy ol' starter world. Doesn't happen in vanilla because you cannot start there any more, regrettably. 

Problem was Seige Drone Gunship (SDG) base attack in starter area (plyr lvl 7) was unplayable without base weapons (just a start camp and base block charging a capacitor) and ends the game because all respawn points are in the same place i.e. restart planet spawn is also aimed at the starter area, so there is no escape as SDG is 100% accurate, plenty range, TTK player without vehicle is a few seconds, rinse repeat ad nauseam.

My lesson is I will have to reload an earlier save and build base cannons (or disable base attacks maybe!)

Situation was I had just landed, completed first crash investigation mission on hover bike with a looted sniper rifle and killed a mission scripted gattling drone np, village had been marked on HUD and was expecting similar gat drones etc but then the SDG turned up from what I assume was a base attack, not mission script, no IDA warning and game over. Just thought I should mention it :)

### POI Name

Omicron starter area

### Playfield Name

Omicron

### Mission Name

Base Attack

### Game Seed

753894

**Comment by RavienGaming** [comment]
Closing because this isn't a bug.
