### ISSUE TITLE
Secure storage facility: after a 3 codebreakers, the dialog for them stops showing up

### ISSUE THREAD

**Issue by Ishantil** [RavienGaming/Reforged-Eden-2#289]
### Reforged Eden 2 Build Number

20

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Secure storage facility: after using 3 codebreakers, the dialog for them stops showing up.  Event though I had three more, I could not use them.

### POI Name

Secure storage facility

**Comment by RavienGaming** [comment]
You can only use them when you shrink the code range far enough.
