### ISSUE TITLE
Stuttering. 

### ISSUE THREAD

**Issue by troger01** [RavienGaming/Reforged-Eden-2#290]
### Reforged Eden 2 Build Number

Build 20

### Game mode

Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

I'm having some suttering issues. When I was looking at the constructor, it would pause for a couple of seconds and then continue. I also tried using a mounted turret and had some pauses when turning the turret. I verified the files and tried it again and still the same issue.

**Comment by RavienGaming** [comment]
This is likely a game bug and will need to be reproduced and reported using a vanilla save game.
When reproducing a game bug in a vanilla save, make sure you are using the same mode _(singleplayer/co-op/dedicated multiplayer, survival/creative)_ as what you were using when the issue happened in the scenario.
To see a list of known game bugs or to report a new one please see: https://empyriononline.com/forums/bugs.24/

**Comment by troger01** [comment]
I figured out the stuttering. I didn't have any fuel in the tanks
