### ISSUE TITLE
Hive Guardians Damaging Drone Nursery

### ISSUE THREAD

**Issue by Kainne00** [RavienGaming/Reforged-Eden-2#291]
### Reforged Eden 2 Build Number

20

### Game mode

Survival, Single Player, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Severity: Non-Critical / Annoyance / Broken Mechanic

Hive Guardians on the Eden_EnemySupport faction are slowly damaging the Hive Nursery's shields. This has happened repeatedly in MP and happens in SP as well.  MP it is difficult to test without admin functions. Basically if the nursery is damaged, its shield should recharge on its own and/or the hive guardians should be "healing" the nursery shield so it rapidly tops off. That is the opposite of what happens.

The HGs with remote shield boosters are effectively 'pinging' the nursery frequently enough to prevent the nurserys shield from ever recharging. Similar to how a play parked a minigun on a recharging POI to keep the shield always down while inside (a la sector command).

the di damage command shows HGs 'hitting' the nursery for zero damage, however you can observe the nursery shield % dropping slowly so it is in fact taking damage somewhere.  In theory with a lot of patience, a player could wait for the HGs to kill the shield entirely, but it'd take a while.

in SP, with GM IV set,  this was tested and observed in a default spawn the nursery took damage slowly from "something".  using GM IV to power off turrets on all 4 HGs, the nursery stopped taking damage and shields recharged normally.  With HG shield boosters only (no laser/missile enabled) the nursery again began taking invisible damage and preventing its shield from recharging.

Something with the remote booster is causing damage to the nursery in part due to different factions or the booster itself. 

  

### POI Name

Class 6 Combat Site - Drone Nursery

**Comment by RavienGaming** [comment]
Thanks I see the issue and will fix it. For some reason I had given them the railgun damage profile instead of the shield booster one.

**Comment by RavienGaming** [comment]
Thanks. Fixed for next update.
