### ISSUE TITLE
Empty Trade Sectors

### ISSUE THREAD

**Issue by CrazyGamer9191** [RavienGaming/Reforged-Eden-2#292]
### Reforged Eden 2 Build Number

20

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

I have found a sector in Trade Federation space that has the white Icon but traveling there it is empty nothing there. No asteroids or pois

### POI Name

UXIN 4622 II

### Playfield Name

UXIN 4622 II Sector

### Playfield Class

Trading Sector Trade Federation

### Star Name

Raki Beta

### Star Class

O

### Game Seed

919

**Comment by RavienGaming** [comment]
Duplicate of #16
