### ISSUE TITLE
RE2_BAO_ProgHackT1_01

### ISSUE THREAD

**Issue by Dr-doom914** [RavienGaming/Reforged-Eden-2#296]
### Reforged Eden 2 Build Number

20

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

 i beat the new puzzle and the doors dont blow up doesnt happen on all of them just a few of them of the same type 
![Screenshot 2024-09-05 135000](https://github.com/user-attachments/assets/d43f236a-2025-4645-9e90-b03297c1a957)

### POI Name

RE2_BAO_ProgHackT1_01

### Playfield Class

barren planet orbit

### Star Class

M4

**Comment by Dr-doom914** [comment]
another thing it might be the ones that spawn in a group next to a unknown signal thats broken BP=Eden_BAO_Antenna2

**Comment by RavienGaming** [comment]
This is likely a game bug and will need to be reproduced and reported using a vanilla save game.
When reproducing a game bug in a vanilla save, make sure you are using the same mode _(singleplayer/co-op/dedicated multiplayer, survival/creative)_ as what you were using when the issue happened in the scenario.
To see a list of known game bugs or to report a new one please see: https://empyriononline.com/forums/bugs.24/
