### ISSUE TITLE
CV Weapon Software Functioning Incorrectly

### ISSUE THREAD

**Issue by Kainne00** [RavienGaming/Reforged-Eden-2#298]
### Reforged Eden 2 Build Number

21

### Game mode

Survival, Creative, Single Player, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Weapon Software installed during Build 20 does not correctly update in the upgrade table. Items in the upgrade console will continue to report0/50 and did not save upgrades transitioning from Build 20 to Build 21.  This is minor and not the purpose of this report.

Tested with: Heavy Positron Cannon, Heavy Plasma Cannon, Heavy Railgun Cannons, Light Railgun, Light Laser, and Light Plasma cannons. All situations respond int he same fashion.

Problem 1: Device Information (P Menu) incorrectly displays most recent and not cumulative weapon software reload% reduction.

Problem 2: (Suspected) Weapons with full 50% reload install per upgrade table do not experience reduced reload time.

Repro:

1 - Install a heavy manual weapon of choice. Note: Plasma, Positron, Rail all have default reload time of 10sec
2 - Use upgrade table to install Military Software (5%) to chosen weapon
3 - Observe P Menu device reload time now 9.5sec.  Observe (On next upgrade) chosen weapon at 5/50 upgrade cycle.
4 - So far, all correct.
5 - Use Upgrade Table to install Imperial Software (10% reload)
6 - Observe P menu reload time of chosen weapon now 9.0 sec (this should be 8.5).  Note upgrade table reporting 15/50.
7 - This is potentially incorrect.
8 - Install Classified Upgrade (20%) to same weapon.  Table will report (on revisit) 35/50.  Also correct.
9 - Observe P menu now showing 8.0sec reload.
10 - This would be correct for a 20% (2 sec off of 10) for first install. But this should be a 35% reduction. Incorrect.
11 - Install a Military Software (5%) to the same weapon.  The upgrade table will report 40/50 (still correct).
12 - Observe chosen heavy weapon reload time displayed as 9.5, up from 8.0sec.  This is very incorrect.

Conclusion:  While the upgrade table itself correctly adds (and locks out) weapon software to allow a user to reach 50/50 reload status, the device menu reload time is utilizing the most recently installed weapon software to display reload times.  A 50/50 should display a 5sec reload time, but will at most display 8 sec, at worst display 9.5sec,. assuming heavy weapons.  Light weapons will display 4.8 (5%), 4.5 (10%) and 4.0sec (20%) pending their most recent install.

Problem 2:  With a 50/50 software install, we must assume a 50% reload time would be 5 seconds.  Using a phone based stopwatch, a heavy weapon reload (manual reload - hit R same time as start on phone) generates approximately a 9.75 to 10.3 second reload time. This is in accordance with a standard 10 second reload with variance for human error pushing the start/stop button.

The 50/50 software should give a 5second reload.  With a phone timer and manual reload, this still approximately takes 9.75 to 10.2 sec on reloads suggesting the actual weapons are not taking the 50% reload into effect.  If the 50/50 is bugged and the most that is received is a 20 (Classified) reduction for single shot reduction, we expect an 8 second reload time. UNfortunately with handheld timer this is still shown at 9.73 to 9.9 seconds to reload.  Light weapons were not timed as their reload is tighter and human error is more likely to skew the result.

Conclusion:  Weapon software is not correctly applying to physical reload times either.

**Comment by VermillionX** [comment]
Problem identified. It's setting the bonus value to a fixed amount instead of increasing it by a fixed amount. Will be fixed in next update, but won't fix the problem in existing savegames which have already used mods.

**Comment by RavienGaming** [comment]
This still an issue?

**Comment by Kainne00** [comment]
I believe the actual reload is still functioning incorrectly, however the stacking works correctly in the device menu and upgrade table.

I'll get a video with an onscreen timer later depicting.

**Comment by RavienGaming** [comment]
Sounds like a game bug where the game is not actually taking the player skills into account when reloading the weapon. Ugh.

**Comment by Kainne00** [comment]
Please view the following video. It's converting to HD from SD as of posting this.

The reload tests begin at roughly the 3:23 mark.

https://www.youtube.com/watch?v=vZpWKzJrDvo

**Comment by VermillionX** [comment]
It's a game bug that eleon needs to fix.
Since you've done a video with all the relevant information, I suggest make an official bug report.

**Comment by 8836290** [comment]
Video is useless if it is not done in vanilla to reproduce the bug. I suggest before make any report @Kainne00 should make a new one in vanilla game. Other than that it is an outstanding video reproducing the bug.

**Comment by RavienGaming** [comment]
Game bugs can be reported using custom scenarios, if the underlying issue is a game bug. Now it's possible this is not a game bug in that the player skill system may not have ever been intended to be used on ship weapons, but it can still be reported to the devs and they can mark it as appropriate.

**Comment by Kainne00** [comment]
Yeah.  I'll work up a game bug and a cleaner video for this for the officials.

There's no option for reduced weapon reload in vanilla, so there is no way to repro it except for custom scenario.  I'll touch base with Ravien/Vermillion offline to get their technical details to properly report this to Eleon.
