### ISSUE TITLE
Polaris NPC Ships merging due to AI pathing

### ISSUE THREAD

**Issue by minkoti** [RavienGaming/Reforged-Eden-2#299]
### Reforged Eden 2 Build Number

21

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Inside faction owned asteroid fields such as Polaris asteroid field in this example, the "Light mining vessels" follow a certain AI pathing, but eventually will always end up merging into the exact same path and fusing together causing Massive FPS drop. 

This is an issue only if you build a base there like I have within render distance 1-3 km away.
Spanj wanted me to report this, but I find this not to be a major issue, as you just have to not base there.
Suggested solution: Write a warning in the asteroid field information tab

### POI Name

Light mining vessel

### Playfield Name

Keh

### Playfield Class

Asteroid Field Faction owned(Polaris)

### Star Name

Xanosia

### Star Class

D5

### Game Seed

 123344

**Comment by RavienGaming** [comment]
This is likely a game bug and will need to be reproduced and reported using a vanilla save game.
When reproducing a game bug in a vanilla save, make sure you are using the same mode _(singleplayer/co-op/dedicated multiplayer, survival/creative)_ as what you were using when the issue happened in the scenario.
To see a list of known game bugs or to report a new one please see: https://empyriononline.com/forums/bugs.24/
