### ISSUE TITLE
Legacy Asteroid fields not spawning in Zirax space

### ISSUE THREAD

**Issue by zelbov** [RavienGaming/Reforged-Eden-2#30]
### Reforged Eden 2 Build Number

1

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

I've ran through around 15-20 N and BH systems, which i was able to find Legacy asteroid fields in even in Zirax territory back in RE1, and very often, but i'm having a hard time to find them in RE2 now. Were they removed at all or is it just a bad luck?

### Star Class

N, N2, BH, BH2

### Game Seed

521287

**Comment by RavienGaming** [comment]
Legacy asteroid fields no longer appear in other faction territories for the most part. Zirax would never allow such an infestation to occur inside their own borders, though in the future new combat sites featuring Legacy may show up in Zirax territory.
