### ISSUE TITLE
R2ColonistAux floating above ground

### ISSUE THREAD

**Issue by suntrip76** [RavienGaming/Reforged-Eden-2#300]
### Reforged Eden 2 Build Number

B21

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

POI is floating well above ground. 
![billede](https://github.com/user-attachments/assets/5b01d038-3179-4d63-bd12-d1a403fadd7f)

### POI Name

PLaceholder R2ColonistAux

### Playfield Name

Delta 17737 II

### Playfield Class

Snow

### Star Name

Zohek

### Game Seed

World 489834 - Playfield 303636

**Comment by RavienGaming** [comment]
Duplicate of #134
