### ISSUE TITLE
[Colonists] Asteroid Station missing windows blocks

### ISSUE THREAD

**Issue by AlexS-empyrion** [RavienGaming/Reforged-Eden-2#304]
### Reforged Eden 2 Build Number

21

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Station Administration room missing two heavy glass blocks.
![RE2-1 11-Omicron_2024-09-06_16-28-23](https://github.com/user-attachments/assets/8320e115-2012-4566-b6a8-cb46f82a730a)
![RE2-1 11-Omicron_2024-09-06_16-28-53](https://github.com/user-attachments/assets/90c54110-a374-4aa5-b05d-7057b388c599)

### POI Name

R2BAO_AsteroidStation02

**Comment by VermillionX** [comment]
Fixed for next update.
