### ISSUE TITLE
no reforged eden 2

### ISSUE THREAD

**Issue by tscottbean** [RavienGaming/Reforged-Eden-2#305]
### Reforged Eden 2 Build Number

i dont have one because all my saves are gone and steam work shop says i an subscribed but i have no reforged eden in the scenario tab

### Game mode

Survival, Creative, Single Player, Co-op

### Tested in vanilla

Reproduced in vanilla

### Description of issue

Steam work shop say`s i am subscribed but i have no reforged eden 2 in the scenario tab. also All my saves are gone, regular saves and reforged

### Error code from console or log (Optional)

startup

### POI Name

start up

### Playfield Name

startup

### Playfield Class

startup

### Star Name

startup

### Star Class

startup

### Mission Name

startup

### Mission Objective

startup

### Game Seed

startup

**Comment by RavienGaming** [comment]
This could be due to Steam not being connected, a Steam side issue, or you might need to validate files.

So try validating files in Steam and also restarting your PC and see if that fixes it. Otherwise just wait for steam to reconnect.

Probably same issue as  #6

**Comment by tscottbean** [comment]
Ok so if i open the game in the steam library it works, all my saved games are there and the reforged eden 2 scenario work. but if i start the game from the desk top icon it is all missing. do i need to reinstall empyrion or just leave it and start the dame with steam. By the way thanks for replying to my post.

**Comment by RavienGaming** [comment]
> Ok so if i open the game in the steam library it works, all my saved games are there and the reforged eden 2 scenario work. but if i start the game from the desk top icon it is all missing. do i need to reinstall empyrion or just leave it and start the dame with steam. By the way thanks for replying to my post.

This is due to a change in a more recent game update. There's a setting you have to change but this is a game side issue so I don't have it handy. You can try asking elsewhere though.
