### ISSUE TITLE
Pirate Outpost

### ISSUE THREAD

**Issue by Grumpy138** [RavienGaming/Reforged-Eden-2#306]
### Reforged Eden 2 Build Number

21

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Every Pirate Outpost I come across is floating 1 block above ground.

![20240908020623_1](https://github.com/user-attachments/assets/aefbfed7-c329-4a80-af30-e49150091e4b)
![20240908021018_1](https://github.com/user-attachments/assets/dd68db66-6f26-42c1-ba0e-ce3740708b26)

**Comment by VermillionX** [comment]
Weird.
There must be an invisible block in the blueprint that's giving it an extra 1-block height underneath. Will investigate.

**Comment by VermillionX** [comment]
Couldn't find anything, but there's definitely a block in there giving it an extra height. Filled and wiped the whole underside to fix.
So fixed for next update.
