### ISSUE TITLE
Claimable Asteroid RockAsteroids blocks take up CPU

### ISSUE THREAD

**Issue by Ishantil** [RavienGaming/Reforged-Eden-2#31]
### Reforged Eden 2 Build Number

RE2 Build 1 (April 29)

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Claimable asteroid bases use the RockAsteroids block which still have left over vanilla costs associated with it.  About 38CPU per block.

### POI Name

Eden_Asteroid1

### Playfield Class

Habitable Orbit

**Comment by VermillionX** [comment]
Fixed in the next RG2 Update
