### ISSUE TITLE
Ablative Spray still in Medic mission reward dialog

### ISSUE THREAD

**Issue by AlexS-empyrion** [RavienGaming/Reforged-Eden-2#310]
### Reforged Eden 2 Build Number

21

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

By completing Medics Mission it tries to Reward me with Ablative Spray sometimes.
![image](https://github.com/user-attachments/assets/a442a566-7fbb-4a19-ae9d-aa4339e76719)

### POI Name

Various

### Mission Name

AndroMedic trader missions

### Mission Objective

Bring 25 boxes of narcotics.

**Comment by VermillionX** [comment]
Already fixed in next update.
