### ISSUE TITLE
Gold Standard Warehouse Vendor Unlock asking for Pumpkin Cookies

### ISSUE THREAD

**Issue by StHotPants** [RavienGaming/Reforged-Eden-2#311]
### Reforged Eden 2 Build Number

RE2 Beta Build 21

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

The Gold Standard Warehouse unlock vendor can still ask for:
![image](https://github.com/user-attachments/assets/9878beee-7766-4627-a08c-51c67ccce5ed)

Pumpkin Cookies are not creatable anylonger (yes, I recognize you can do the vendor unlock via the GIN console) and maybe should be updated to be just Cookies?

### POI Name

Gold Standard Warehouse

**Comment by VermillionX** [comment]
They are craftable. Cookies and Pumpkin Cookies are the same thing. "Pumpkin Cookie" is the internal name.
Will change the displayed name in the mission for next update.
