### ISSUE TITLE
[Polaris]Communication Satellite have Research Console

### ISSUE THREAD

**Issue by AlexS-empyrion** [RavienGaming/Reforged-Eden-2#312]
### Reforged Eden 2 Build Number

21

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

[Polaris]Communication Satellite have Research Console instead of System Console
![RE2-1 11-Omicron_2024-09-11_18-14-45](https://github.com/user-attachments/assets/35ddfb5a-01ad-4ac8-9324-20e080e2f853)

### POI Name

R2BAO_PolarisSatellite03

**Comment by RavienGaming** [comment]
This is working as intended in the scenario.
