### ISSUE TITLE
Error spam

### ISSUE THREAD

**Issue by DontBaitMe** [RavienGaming/Reforged-Eden-2#314]
### Reforged Eden 2 Build Number

21

### Game mode

Survival, Single Player

### Tested in vanilla

Issue does not happen in vanilla

### Description of issue

Anyone else getting the Internal Error when loading up the game?? Just started up after stopping last night without issues and keep getting the error

### Playfield Name

Muw

### Playfield Class

Frozen Inferno

**Comment by RavienGaming** [comment]
Does this still happen if you start a new save game after the latest Empyrion update?

**Comment by DontBaitMe** [comment]
Hey Ravien. Apologies for not closing the thread. Thank you for your amazing work on RE2. 

Solution is already solved. YouTube and Google helped alot here haha. Took over 6 hours to figure out 
In case future similarities occur.

The game wouldn't load my playgrounds after the new update from Eleon.

The cause was my anti-virus to not recognize the game anymore in wich it refused to load the games playgrounds.

Solution is to go to the AV and allow Empyrion map be allowed to read and make changes.

**Comment by RavienGaming** [comment]
Ah okay, glad you found the solution. Sorry it took so much time. :( I will go ahead and close this then!
