### ISSUE TITLE
Colonist Science Outpost missing some blocks?

### ISSUE THREAD

**Issue by suntrip76** [RavienGaming/Reforged-Eden-2#315]
### Reforged Eden 2 Build Number

B22

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Colonist Science station has some funny looking stairs with a gap, as if some blocks are missing. See below. 
![billede](https://github.com/user-attachments/assets/51da8188-75b6-4e93-be18-9eecdb1d3b65)

### POI Name

R2BA_ColonistSciOutpost1

**Comment by VermillionX** [comment]
Looks like the new rock blocks are missing.
You can thank eleon for not having a functional blockmapping system.

**Comment by VermillionX** [comment]
This is actually really weird. I just spawned the POI in SP and it's the first version with filler blocks instead of rocks. A version that I saved over.
Will be fixed in the next update. I have no idea what's going on with this game...

**Comment by suntrip76** [comment]
It must be so frustrating trying to develop stuff for a game that keeps acting up like this. But it makes sense now as to why there was that gap. Thanks for all the work you put into this!
