### ISSUE TITLE
Crew Stations are not calculating power consumption correctly. 

### ISSUE THREAD

**Issue by Keoke-san** [RavienGaming/Reforged-Eden-2#319]
### Reforged Eden 2 Build Number

Build 22

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Spawned in Enti's Warlord CV, at stock everything runs fine, I can fill it with O2, Fuel, and Pentaxid, start up shields and fly and my Generator will cap at 65%. As soon as I add 16 Crew stations (max), which only take 15W each, 240W total, My generator starts going haywire and i reach 212% while charging and flying, and while not charging and just flying it still goes to 184% peak. 

All testing was done in Space. 

### Playfield Name

In Space

**Comment by Keoke-san** [comment]
https://youtu.be/zNBSPdAdPGU

I recorded what is happening and posted it on youtube because it wouldn't let me attach it here. I think I forgot to fly with my shield charging at the start, so after i fly with the crew, i take them out and fly again this time charging shields as well.

**Comment by VermillionX** [comment]
It's probably the helmsman since he's the only one related to movement (he's literally just a human-shaped RCS)
If you place an RCS, do you get the same problem?
If you place JUST the helmsman, do you get the problem?

**Comment by Keoke-san** [comment]
Thanks for getting back to me. I tried it with just 2x helmsman, and i immediately shot up to 120% with out shields, with shields it would jump up to about 220% peak, but hover about 180%
Tried it with 2x T1 RCS and got 90% spike with out shields, with shields was about the same, neither of which went over 100% 
Tried it again with 2x T2 RCS and had the same outcome i think it was like 87% was the peak, and that was both with charging shields and with out charging shields never going over 90%.

**Comment by Keoke-san** [comment]
just to be thorough, i tried it with 1x helmsman and even with out shields i still jumped up 150%, even spiked to 211%.

**Comment by VermillionX** [comment]
Fixed for next update, probably.
Switched the helmsman's energy dynamic grouping to just be a flat power drain instead of dynamic.
Seems to be a vanilla bug with RCS power draw.

**Comment by Keoke-san** [comment]
Cool! Glad I was able to help find and fix a bug with the beta! Love what you guys do! Keep it up!
