### ISSUE TITLE
RTG description text is incorrect

### ISSUE THREAD

**Issue by Garaman-EGS** [RavienGaming/Reforged-Eden-2#32]
### Reforged Eden 2 Build Number

1

### Game mode

Survival, Creative

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

RTG specs are inconsistent with description text. Text lists 2kW/500W as values, looks like they are actually 3kW / 1kW.

**Comment by VermillionX** [comment]
Fixed in next RG2 Update
