### ISSUE TITLE
asteroid regeneration not working

### ISSUE THREAD

**Issue by Malercme** [RavienGaming/Reforged-Eden-2#322]
### Reforged Eden 2 Build Number

22

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

I play on one of the bigger Empyrion RE servers, called HWS (Homeworld server) we just very recently upgraded the server into RE2 , and i have noticed that asteroids (not rich fields) are not regenerating what so ever, I've had some for 48h now not regenerated, i went too a fresh asteroid belt sector and mined it out fully, have not regenerated in close to 24h as of me typing this issue. Someone checked the RE2 config and they are suppose to regen every 6 hours (?) that seems to not be the case, if any can replicate  this do let me know , this has been noticed by multiple players playing, I talked to the admins and they said they didn't change anything and to write an issue about it to the developers. Personally think this is a server issue, since I could not find a single report of this on the github itself. 

### Playfield Name

Epsilon 16263 I

### Playfield Class

Poor Quality Asteroid Field

### Star Name

Lamakore

### Star Class

M5

**Comment by Malercme** [comment]
Just as a side note, this is just one of many playfields where we have this issue on the server i play on , same issue have happened to at least four other players aside from me that i know off, all in different locations / playfields.

**Comment by RavienGaming** [comment]
Most asteroid fields are on a 72h timer.

**Comment by Malercme** [comment]
> Most asteroid fields are on a 72h timer.

Even normal asteroids? i thought the 72h was only for rich fields in RE? At least that's how it's always been in RE1 , but maybe that was a change that happened in RE2? Normal roids where on a 6-12h regen timer before.
