### ISSUE TITLE
Issue completing the project eden missions

### ISSUE THREAD

**Issue by spicybraveheart** [RavienGaming/Reforged-Eden-2#323]
### Reforged Eden 2 Build Number

V1.11.8  4531

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

When trying to complete the contact Terran Forces, the last bit where you Go up the elevator, I received a check,  Upon approach the captain and talk neither completed.  I was unable to complete this mission and earn the next step (the forge)  .  I heard that it might be possible to do it via going to another sector (in my case beta) and trying that mission from the captain.  Trying it to see if it will then complete the mission.

### Playfield Name

Alpha Sector

### Playfield Class

UHC

### Mission Name

Project Eden, Contact Terran Force

### Mission Objective

Last bit when meeting the captain and talking.  Neither complete

**Comment by spicybraveheart** [comment]
![mission issue](https://github.com/user-attachments/assets/84a00be0-12d1-4216-9f1d-e706695e182f)

**Comment by spicybraveheart** [comment]
I have turned in the beta and i still get that it hasn't been done.

**Comment by RavienGaming** [comment]
Can you share screen shots while talking to the captain please so I can see what the captain is saying?

**Comment by spicybraveheart** [comment]
sure getting them now.  She sent me on the survey mission, i turned
![20240924113840_1](https://github.com/user-attachments/assets/b90ddf96-0e07-4043-bc55-60b902c64d44)
 it in and got the goodies but it's failing to complee the mission
![20240924113832_1](https://github.com/user-attachments/assets/bafdcda7-d994-4eb0-916f-f87cf2b69457)
![20240924113849_1](https://github.com/user-attachments/assets/ef6ef312-c70c-49ec-ae64-301f63b895e5)

**Comment by spicybraveheart** [comment]
![20240924114047_1](https://github.com/user-attachments/assets/890c7706-c0e8-459a-bb7b-a888390fbf63)

**Comment by spicybraveheart** [comment]
Headed to delta to see if I can get it there

**Comment by RavienGaming** [comment]
And just to double check, you have the mission currently active when you talk to them?
I will test in SP to see if it happens to me.

**Comment by spicybraveheart** [comment]
Yes and I'll screen shot evrything this time around.  I can stream it for you if you'd like on twitch or in discord let me know if either work for you

**Comment by spicybraveheart** [comment]
mission is active, when i approach the captain nothing is checked off

**Comment by spicybraveheart** [comment]
![20240924115405_1](https://github.com/user-attachments/assets/b78a0db8-c241-4dea-a823-3d8811c9cafe)
![20240924115452_1](https://github.com/user-attachments/assets/1a8754e3-41cd-47c4-bfb4-ed88feb2c2ab)
![20240924115543_1](https://github.com/user-attachments/assets/d143a0e7-4c60-49f3-8067-b587da408f40)
![20240924115452_1](https://github.com/user-attachments/assets/77fb76f0-a8d3-40de-9c30-da5566daf41c)
![20240924115543_1](https://github.com/user-attachments/assets/55129865-b233-4c36-995a-68ac64017d6b)
![20240924115628_1](https://github.com/user-attachments/assets/a00c96de-a6c2-4a76-994a-3f08c1868460)
![20240924115741_1](https://github.com/user-attachments/assets/71c64b09-ae51-46ad-8924-f2df4f8a8146)
![202409
![20240924115801_1](https://github.com/user-attachments/assets/86a5fc9d-2fb7-444f-8c33-2c1b57423c6f)
24115752_1](https://github.com/user-attachments/assets/d679f61e-92dd-4d43-bc24-e40a16b2ebbb)

**Comment by RavienGaming** [comment]
It worked in SP when I tested it.

Try this:

1. Deactivate the mission in the PDA.
2. Fully exit the game all the way back to Windows desktop.
3. Relaunch the game and reconnect to the server.
4. Resume the prologue mission in the PDA.
5. Try speaking with the captain again. They should ask you if you need a refresher on the services available at research vessels, or that you are ready to continue (option in green). That option will complete the mission.

If this does not work ask on the server to see if anyone else has had trouble completing it. If so it's likely a server issue. If it's a server issue the server admins would need to troubleshoot on their end to make sure nothing got messed up with the dialogue or PDA files on their end.
If not then it would likely be a game bug.

FYI you can complete the mission at any UCH research vessel in any system, starter OR non-starter.
I'll leave this open in case anyone else has the same issue on other servers.

**Comment by spicybraveheart** [comment]
Ok doing that now

**Comment by spicybraveheart** [comment]
That fixed it!  Thank you so much I was able to complete the mission

**Comment by RavienGaming** [comment]
Glad that worked.

**Comment by spicybraveheart** [comment]
Thank you for your help on this.  I'll make sure to pass it onto our server admins as well.
