### ISSUE TITLE
Chapter 5 Titan ship missing, Roggery Sector, Can't manually skip

### ISSUE THREAD

**Issue by DigitalKitteh** [RavienGaming/Reforged-Eden-2#325]
### Reforged Eden 2 Build Number

22

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

It all started when I went to do the quest "Crash of the Titans". There is no sections of the ship on Roggery Moon at all- ie M.S Titan front, middle and or rear is all missing. SO I manually skipped the quests 'Crash of the Titans' and then 'Point of Interest' and I also had to then skip 'Drive Failure' which is where I am now stuck. It will not allow me to manually skip the step 'Find the Warp Drive Console'. My friend is also in the same predicament. 

As a side note, I am brand new to the game and RE2 and playing on a server I am not sure if the ship has been dismantled.. if that is even possible? I had asked on the servers discord itself but I have yet to get any reply from admin and was told by a user to report to RE2 modders as it sounded like an issue with the quest system? So, while this may not be helpful.. I thought no harm in letting you know regardless.

### POI Name

M.S Titan

### Playfield Name

Roggery Moon

### Playfield Class

Barren Moon

### Star Name

Beta

### Star Class

F Starting System

### Mission Name

Crash of the Titans 

### Mission Objective

Locating M.S Titan

**Comment by RavienGaming** [comment]
Story mission POIs have indestructible admin cores so they cannot be removed by players.

It's possible, but extremely unlikely, that the POIs weren't able to spawn.
In order for me to check this I would need the **global game seed** used for the save game to verify if the POIs did not spawn due to placement issues. You'd have to get the seed from the server admins, if they are willing to give it out.
Alternatively, I can check with the **playfield seed** for the Roggery moon in question. Both seeds would probably be best so I can check both ways.

Otherwise this would likely be an issue with the server.

You should be able to complete the missions on another starter planet moon that shows it has the RG story missions, such as Omicron.

**Comment by DigitalKitteh** [comment]
Thanks Raven! I will ask the admin if they can provide the seed. I will also check for the seed for the moon, get back to you ASAP with that! 

I will also try getting to another moon, I wondered if that would work.

**Comment by DigitalKitteh** [comment]
Oh I misread.. I'm at the moon looking for a seed >.< .. but I have requested the server seed but I will have to wait and see fi they even reply at all :(  Is there any other information I as a player can provide you?

**Comment by RavienGaming** [comment]
No sorry, would need the admin to get the global game seed for the save, and the playfield seed for the Roggery moon playfield for me to check that it's an issue with the scenario or not.

**Comment by DigitalKitteh** [comment]
OK I got a seed! I'm not sure if its the game or the moon, they didn't say but I also only got the 1 number. 

**3527591**

The admin did also say (copy and pasted) 

"Kitteh, more info.  I went around to what I think are all the starter moons in Beta that should have the Titan wrecks (front, mid, rear) and they should be Admin Cores.  There are none.  These do exist in Alpha system.  So you could move there and continue the missions...

I also checked on our test server, which has a different seed and the Titan POIs DO exist on roggery moon etc.  Not really sure whats up but the main server has been up for several months now and I dont know if we can fix it without a wipe."

**Comment by RavienGaming** [comment]
Okay if you're able to ask the admin if that's the global seed for the save game, or the seed for the Roggery moon that would be helpful. Would stop me from having to check both. Thanks for getting back to me!

They could try a playfield wipe of the moons via console command or EAH, which may or may not fix the issue, but would also remove all player structures from those playfields.

**Comment by DigitalKitteh** [comment]
That was the game save seed, which I have since been told you and the admin (Sketchy) have been discussing this issue. So old news haha (time zones!!) Thanks for taking the time to see to the issues promptly!
