### ISSUE TITLE
Unable to Launch Journey to the Stars Prologue mission

### ISSUE THREAD

**Issue by BoatAnkor** [RavienGaming/Reforged-Eden-2#330]
### Reforged Eden 2 Build Number

v1.11.8

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

I started on PX-37 which is the prison break planet. After I left the planet and reached UCH vessel. that storyline started down the main story scenario. That worked just fine. However, I also wanted to complete the main story scenario that includes Human debris as chapter one. I could not do this because I could not get the "journey into the unknown to trigger.

### POI Name

NA

### Playfield Name

Starter Planets

### Playfield Class

NA

### Star Name

NA

### Star Class

NA

### Mission Name

Journey into the unknown - Prologue Main Story Mission

### Mission Objective

Starting the Prologue

### Game Seed

1011345

**Comment by RavienGaming** [comment]
Check the Empyriopedia, it lists the planets you need to start on to start the RG2 story missions.
