### ISSUE TITLE
DEAD WORLDS 4

### ISSUE THREAD

**Issue by Oldbob123** [RavienGaming/Reforged-Eden-2#332]
### Reforged Eden 2 Build Number

NA

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

dead worlds mission 4 console/tower/beacon not there doesn't spawn..... cant complete mission .......checked various dead worlds 4 planets all the same ......

### Error code from console or log (Optional)

none

### POI Name

dead worlds 4 

### Playfield Name

dead worlds 4

### Playfield Class

dead worlds 4 beacon

### Star Name

all

### Star Class

dead worlds

### Mission Name

dead worlds

### Mission Objective

dead 4 not there

### Game Seed

6

**Comment by RavienGaming** [comment]
Dig down.
