### ISSUE TITLE
Polaris "Trade Station" appears to not be spawning in MP as of Build 22

### ISSUE THREAD

**Issue by StHotPants** [RavienGaming/Reforged-Eden-2#333]
### Reforged Eden 2 Build Number

RE2 Beta Build 22

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

The ASH server restarted with RE2 Beta Build 22 after September 12th. Since the restart, multiple hundreds of Polaris Trade Station <xyz> instances have been discovered in normal orbital playfields, Polaris gold satellite playfields, and white satellite playfields within the Polaris faction bubble. Ashenator, the server admin, has used the EAH tool to search and has confirmed that not a single Polaris "Trade Station" (i.e. not Trade Station Iota, or Trade Station Lambda, or Trade Station CB802N, etc..) has been found.
![image](https://github.com/user-attachments/assets/cc156463-8206-4906-a2ac-6bc98a6bd6ca)

As this specific Polaris POI has a vendor that sells Raw Diamonds (the only other vendor that sells them is at a Talon Quarry in much lesser quantities when you can find them) that are required for higher end weapons (often 16 or more diamonds required per turret) and the Specialized Crew quest, having it missing is a fairly sizeable impact to gameplay

### POI Name

Trade Station

**Comment by RavienGaming** [comment]
The list shown in EAH in that screenshot is showing planetary trading stations, not orbital ones.

The Polaris orbital trading stations I think are called Trading Station Lambda or Trading Station Iota. If they search EAH for "Trade" it won't find "Trading Station".

If the POIs are not showing up in space sectors where they should, then that would likely be a server configuration issue.

**Comment by StHotPants** [comment]
You may be right on the screenshot, I will check with Ash and request an updated search and results

Polaris is supposed to have 3 different orbital trading statons:
![image](https://github.com/user-attachments/assets/bcbca525-f239-481f-94bc-47544f483fb4)
![image](https://github.com/user-attachments/assets/a23c1364-aa7d-43b5-8014-f980a6f4a766)
![image](https://github.com/user-attachments/assets/a234d1a6-e284-4d58-9c58-7e6288065067)

The diamond vendor only exists in the "Trading Station" version, not in Iota or Lambda. 

All the above screenshots are from the Anvil server, not the Ash server (and all were found prior to Beta 22 release on 9/12/2024. 

As for server configuration. When I talked to Ash he indicated he only did the base default installation and configuration to support As-Is Beta testing.

**Comment by StHotPants** [comment]
No "Trading Station" instances per Ashenator

![image](https://github.com/user-attachments/assets/4a39b060-392c-4f79-85cd-51832588462a)

**Comment by StHotPants** [comment]
Have the seed # if you want to try checking it out

**Comment by RavienGaming** [comment]
I'm not sure what you think the issue is. That list in your screenshot shows Polaris trading stations spawning. Those are all correct and the only two types of Polaris orbital trading station that exist currently.

The "trading station" without the Greek alphabet identifier is an old one that should not appear anymore.
