### ISSUE TITLE
Doors to Talon Farms, and some other buildings sometime not open.

### ISSUE THREAD

**Issue by HisShad0w** [RavienGaming/Reforged-Eden-2#336]
### Reforged Eden 2 Build Number

22

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Doors to Talon Farms and for ex. Mills can't be opened, so i can't reach trader in some cases. Sometimes i can open them, but mostly can't.

### POI Name

Talon Farm

### Playfield Name

Alpha VI

### Playfield Class

Snow

### Star Name

Alpha

### Game Seed

295144

**Comment by VermillionX** [comment]
Known. Seems to be an issue with trapdoors in unpowered structures. They don't open when they should.

**Comment by VermillionX** [comment]
Fixed for next update.
