### ISSUE TITLE
Trade frequency not working

### ISSUE THREAD

**Issue by Ente2k** [RavienGaming/Reforged-Eden-2#338]
### Reforged Eden 2 Build Number

21

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Got a trade fequency for hostile robotics apparatus running, but it doesn't seem to work. Stumbled across one on a planet, but don't get a notification when I enter that playfield

![20241005153535_1](https://github.com/user-attachments/assets/7925b269-2e3e-4e59-ad0b-3dc1c46d2a84)

**Comment by RavienGaming** [comment]
Thanks this should be fixed next update. There may be others that also need fixing so I'll keep this open until I go through and verify them all.

**Comment by RavienGaming** [comment]
Should have all the trading frequencies updated for the next update. Will require the **pda readdata** console command to apply to existing saves in SP once the update is live.
