### ISSUE TITLE
POI spawn causes playfield crash if contains blocks with no ID's

### ISSUE THREAD

**Issue by Neimoh** [RavienGaming/Reforged-Eden-2#339]
### Reforged Eden 2 Build Number

22

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Modify or create a POI Blueprint containing in our case Quantum extenders and Industrial Floodlights. Saved the blueprint with R2AbandonedPOI groupname and added blueprint to prefabs folder. On a DS any Playfield containing that POI will crash due to missing block errors. In SP the POI will spawn in with missing QuantumExtenders and Floodlights. 

I did verify those 2 particular blocks do not have BlockID's assigned. It may not be fixable being low on BlockID's but maybe to flag those blocks as illegal in Blueprints.

**Comment by RavienGaming** [comment]
Sorry I can't support any modification to the scenario. This sounds like a corruption of the save though.
