### ISSUE TITLE
Patrol Vessel stuck in the ground in a vertical position

### ISSUE THREAD

**Issue by danielsolaro** [RavienGaming/Reforged-Eden-2#34]
### Reforged Eden 2 Build Number

2

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

found a patrol vessel (initially flying normally), went home to drop loot, came back the ship was stuck in the ground
![20240506111500_1](https://github.com/RavienGaming/Reforged-Eden-2/assets/8516353/736c0676-9df7-40c1-80ef-bf482a1c1615)
![20240506113938_1](https://github.com/RavienGaming/Reforged-Eden-2/assets/8516353/6fd22f11-feb6-4929-89d6-2905be0d883a)

### POI Name

PV_RadosPatrolVessel3

### Playfield Name

Epsilon II

### Playfield Class

Desert Planet

### Star Name

Epsilon

### Star Class

MStartingSystem

### Game Seed

347484

**Comment by VermillionX** [comment]
That ship shouldn't exist. It's not even an RE prefab.

**Comment by RavienGaming** [comment]
Thanks for the report. Fixed the incorrect patrol vessels in the starting systems for next update. This may or may not fix ships getting stuck like that as it uses a new AI as well but that part would be a game bug.
Going to mark this as fixed as I assume this will fix it, but if you see the AI do the same flippy flippy with the new patrol vessels or still see an old patrol vessel after the update (in a new save) please feel free to report again.
