### ISSUE TITLE
Bad geometry on Titan Wreck Front POI

### ISSUE THREAD

**Issue by thelyric27** [RavienGaming/Reforged-Eden-2#340]
### Reforged Eden 2 Build Number

22

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

![image](https://github.com/user-attachments/assets/246c35c9-c163-4606-8eef-989d7274d27b)

This bunk room on the Titan Wreck front has an alien pod beckoning you inside. You can get in by crouching but no matter how I fling-crouch myself into the door I can't get back out, which sucks. Going to die of radiation poisoning if I don't cheat out of it :/

### POI Name

Crashed Titan (Front)

### Playfield Name

Akua Moon

### Playfield Class

Barren Moon

### Star Name

Alpha

### Star Class

GStartingSystem

### Mission Name

Crash of the Titans

### Game Seed

93600 (Global) 47742 (Local)

**Comment by VermillionX** [comment]
Fixed for next update.
The bed behind you will be destructible.
