### ISSUE TITLE
Zirax Bunker Turret is not killable 

### ISSUE THREAD

**Issue by Merica4200** [RavienGaming/Reforged-Eden-2#341]
### Reforged Eden 2 Build Number

v1.11.9 4536 09-00:59

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

The Gat turret on the tank at the entrance is unkillable so unable to do POI

### POI Name

Zirax Military bunker

### Playfield Name

Miron moon 3

### Playfield Class

Crystalline moon

### Star Name

Grine Beta

### Game Seed

89203

**Comment by VermillionX** [comment]
Already fixed for next update
