### ISSUE TITLE
Misclassified POI

### ISSUE THREAD

**Issue by thelyric27** [RavienGaming/Reforged-Eden-2#344]
### Reforged Eden 2 Build Number

22

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

I found a few wrecks in space around Akua and this one called the Rockhopper looked like an easy, compact CV to restore and use in early game. But after placing down a salvage core I tried to place a CV ion thruster and it told me the structure was a base even though it spawned with CV blocks on it. I don't know of any way to change structure types so I'm not going to be able to restore it unless I take it apart and build it from scratch :/

![image](https://github.com/user-attachments/assets/775c612a-924f-4121-bacb-1414d89b5bf1)
![image](https://github.com/user-attachments/assets/cb86df03-dc33-49a4-ab90-0bbb845ae2b7)

### POI Name

Rockhopper Wreck

### Playfield Name

Akua Sector

### Playfield Class

Orbit

### Star Name

Alpha

### Star Class

GStartingSystem

### Game Seed

93600 (Global) 47742 (Local)

**Comment by RavienGaming** [comment]
Intended. Some wrecks in space will be actual CVs, but most will be bases even if they are a "ship wreck". You can look at the icon on the map to see if it's an actual CV or not.

**Comment by thelyric27** [comment]
Then what's the purpose of these wrecks even being here besides having some blocks to salvage? It's got thrusters, a command chair, and a decent frame, and there's extra container extensions, 2 medium thrusters, and hardened steel blocks. Good game design would be to put these wrecks there for the player to stumble across and let them put the pieces together for their first CV, but instead if you want to use the salvage on a CV, you have to take all these blocks, figure out how to store them, waste all of your oxygen and multitool durability disassembling the "ship wreck", and build one from scratch instead of restoring this perfectly good hull that has literally 0 blocks on it that you wouldn't be able to put on a CV.

**Comment by RavienGaming** [comment]
The actual CV and SV wrecks have not been updated yet for the scenario and are still using vanilla designs, hence their limited availability.
