### ISSUE TITLE
Told to report this bug

### ISSUE THREAD

**Issue by freer4** [RavienGaming/Reforged-Eden-2#345]
### Reforged Eden 2 Build Number

22

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Get a red warning message saying to report this to RE2 devs if I see it. So I'm reporting it. 2 NPCs, the 2 in the hangar of a mining foreman ship, "Commanding Officer" and "Merchant". It's a "Polaris Mining Operation" sector, there's an ocean planet here, it's on the HWS RE NA server, System Malphivna, Sector Delta 4757 I if you want to check it out. 

### POI Name

Lvl 7 [Polaris] Mining Foreman

**Comment by RavienGaming** [comment]
If you're able, could you share a screenshot of the solar system map, with the sector in question selected and the info window open (so the description is shown) please? That will help me find it. Uncropped if possible. You can drag and drop screenshots into here.
You can double click on the system on the galaxy map to view the solar system without having to warp back to it.

**Comment by RavienGaming** [comment]
I cannot find any playfield with the type "Polaris Mining Operation" in the files, so a screenshot will be needed for me to look into this when you get a chance. Thank you.

**Comment by RavienGaming** [comment]
Are you able to provide a screenshot? I will close this in a few days unless someone else has more info to report. Thank you.
