### ISSUE TITLE
entire Base blew up

### ISSUE THREAD

**Issue by Duke-Engi** [RavienGaming/Reforged-Eden-2#351]
### Reforged Eden 2 Build Number

4541

### Game mode

Dedicated Server

### Tested in vanilla

Issue does not happen in vanilla

### Description of issue

My entire base exploded, the core is not damaged, everything else is gone, no enemy attack or animals were there, the generator was on but no fuel in the tanks, powered only by wind and solar energy. Players at level 22, also the base. Normally emergency containers are left behind when the main container and its contents are gone - this wasn't the case either.
I hadn't accessed the base myself, but I was right there.

(The other problem I had was that I was missing data - fixed)

### Error code from console or log (Optional)

Akua

### Playfield Name

Akua

**Comment by RavienGaming** [comment]
Most likely same issue as #10 if the replaced blocks caused your base to go over on power usage and blow up your generators.

**Comment by RavienGaming** [comment]
I will close this in a few days unless anyone else has new info to report as it's probably due to the block ID bug.

**Comment by Duke-Engi** [comment]
I had no clue, guess youre right, thx! Close this one pls. Keep up the good work mate! TY!
