### ISSUE TITLE
Never ending load screen on server

### ISSUE THREAD

**Issue by CrazyGamer9191** [RavienGaming/Reforged-Eden-2#352]
### Reforged Eden 2 Build Number

23

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

I have a server for my own use. Been playing for months (900 hours) started a new game on server and right after I can pick my planet to start game it get stuck on load screen. I saw other post about SP similar issues but not server one. I do have custom settings but did not change difficulty. 

### Error code from console or log (Optional)

Mono path[0] = 'C:/TCAFiles/Users/jason19/181514/DedicatedServer/EmpyrionDedicated_Data/Managed'
Mono config path = 'C:/TCAFiles/Users/jason19/181514/DedicatedServer/MonoBleedingEdge/etc'
[Physics::Module] Initialized MultithreadedJobDispatcher with 23 workers.
Initialize engine version: 2022.3.22f1 (887be4894c44)
[Subsystems] Discovering subsystems at path C:/TCAFiles/Users/jason19/181514/DedicatedServer/EmpyrionDedicated_Data/UnitySubsystems
Forcing GfxDevice: Null
GfxDevice: creating device client; threaded=0; jobified=0
NullGfxDevice:
    Version:  NULL 1.0 [1.0]
    Renderer: Null Device
    Vendor:   Unity Technologies
Begin MonoManager ReloadAssembly
- Loaded All Assemblies, in  0.150 seconds
- Finished resetting the current domain, in  0.002 seconds
ERROR: Shader Sprites/Default shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
Microsoft Media Foundation video decoding to texture disabled: graphics device is Null, only Direct3D 11 and Direct3D 12 (only on desktop) are supported for hardware-accelerated video decoding.
ERROR: Shader Sprites/Mask shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
UnloadTime: 0.724800 ms
20-08:19:20.843 01_19 -LOG- AppPath: C:\TCAFiles\Users\jason19\181514
20-08:19:20.883 01_19 -LOG- Args: C:\TCAFiles\Users\jason19\181514\DedicatedServer\EmpyrionDedicated.exe -batchmode -nographics -logFile ..\Logs\Dedicated.log -dedicated dedicated_config.yaml
20-08:19:20.884 01_19 -LOG- Dedi log path = C:\TCAFiles\Users\jason19\181514\DedicatedServer\EmpyrionDedicated_Data\..\..\Logs
20-08:19:20.886 01_19 -LOG- IEAC available: True
20-08:19:20.957 01_19 -LOG- *************************************************************************
20-08:19:20.957 01_19 -LOG- Dedicated Server Empyrion - Galactic Survival
20-08:19:20.957 01_19 -LOG- Version: v1.11.9
20-08:19:20.958 01_19 -LOG- Build: 4536
20-08:19:20.958 01_19 -LOG- Platform: Win, 64 Bit
20-08:19:20.958 01_19 -LOG- OS: Windows 10  (10.0.17763) 64bit
20-08:19:20.958 01_19 -LOG- DRAM: 130996
20-08:19:20.959 01_19 -LOG- CPU: AMD Ryzen 9 5900X 12-Core Processor 
20-08:19:20.959 01_19 -LOG- Freq: 3693
20-08:19:20.959 01_19 -LOG- Cores: 24
20-08:19:20.959 01_19 -LOG- Gfx: Null Device
20-08:19:20.959 01_19 -LOG- VRAM: 128
20-08:19:20.960 01_19 -LOG- SL: 3
20-08:19:20.960 01_19 -LOG- Force DX9: False
20-08:19:20.960 01_19 -LOG- Instancing: False
20-08:19:20.963 01_19 -LOG- TimeZone: -07:00
20-08:19:20.963 01_19 -LOG- Culture: en-US
20-08:19:20.963 01_19 -LOG- Last build: 4536
20-08:19:20.963 01_19 -LOG- Dedicated server build
20-08:19:20.965 01_19 -LOG- Build: Release (activeManager)
20-08:19:20.966 01_19 -LOG- MainThreadId: 134408
20-08:19:20.966 01_19 -LOG- *************************************************************************
20-08:19:20.966 01_19 -LOG- Limiting the number of worker threads on a dedicated server to 8
20-08:19:21.234 01_19 -LOG- Loading file 'C:\TCAFiles\Users\jason19\181514/dedicated_config.yaml'
20-08:19:22.381 01_19 -LOG- Spreading: Instantiate (DA)
20-08:19:22.437 01_19 -LOG- Save game version v1.11.9, Build 4536
20-08:19:24.988 01_19 -LOG- Loading 5687 BP headers took 1646ms
20-08:19:24.988 01_19 -LOG- Game dat file loaded
20-08:19:26.933 01_19 -LOG- Loaded sector file C:\TCAFiles\Users\jason19\181514/Saves/Games/build23/Sectors/Sectors.yaml with 700 playfields, needed 1738ms
20-08:19:27.271 01_19 -LOG- Generating stars=29670 took 335
20-08:19:27.271 01_19 -LOG- Faction statistics enabled
20-08:19:27.272 01_19 -LOG- Mode=keywordsCache, GameSeed=919, UniqueId=71581548, EntityId=1001
20-08:19:27.277 01_19 -LOG- Task Type=childWindow ThreadId=138676 ManagedId=7
Network driver created, max unsplit packet sizes: 1373 / 42501
[UC  ] Starting connection to server... (OSM)
Setting breakpad minidump AppID = 383120
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561197960265728 [API loaded no]
20-08:19:27.454 01_19 -LOG- EAC2: Session started
20-08:19:27.454 01_19 -LOG- Telnet server started on port 30004
20-08:19:27.478 01_19 -LOG- STCP: Now listening for PfServers on port 30003
20-08:19:27.478 01_19 -LOG- Thread 'ExitStream1' ThreadId=89820 ManagedId=9
20-08:19:27.483 01_19 -LOG- SectorDb: SetMode to childWindow
[UC  ] Client is now connected to the server.
20-08:19:28.758 01_19 -LOG- Start Game
20-08:19:28.758 01_19 -LOG- Server started listening on port 30000
20-08:19:28.762 01_19 -LOG- Zero IP Address replaced by a7a05daa
20-08:19:30.758 01_19 -LOG- Started process 'EmpyrionPlayfieldServer.exe' (PID 124056) with args: -batchmode -nographics -logFile ../Logs/4536/Playfield_241020-011930-71.log "configFile=dedicated_config.yaml"
20-08:19:33.884 01_19 -LOG- New playfield server
20-08:19:33.886 01_19 -LOG- Thread 'Reader_127.0.0.1:51071' ThreadId=10660 ManagedId=17
20-08:19:33.886 01_19 -LOG- Thread 'Writer_127.0.0.1:51071' ThreadId=137312 ManagedId=18
20-08:19:37.557 01_19 -LOG- Booting PfServer (PID 124056) starts preparation after 6.9 seconds...
20-08:20:21.239 01_20 -LOG- INFO: Uptime=00h00m 60.292 2136 heap= 357MB fps=40.0 players= 0 pfs=r1/i0/a0 ticks=1398745 nwqueue=
20-08:20:22.324 01_20 -LOG- NET: Raknet player connected CId=1/8960381730959461101
20-08:20:22.325 01_20 -LOG- Task Type=keywordsCache ThreadId=119264 ManagedId=23
20-08:20:22.453 01_20 -LOG- [PA] Player 76561199273859331/'CrazyGamer919' asking for login
20-08:20:22.455 01_20 -LOG- Steam: BeginAuthSession for player CId=1, EId=-1, 76561199273859331//'CrazyGamer919', result: k_EBeginAuthSessionResultOK
20-08:20:22.457 01_20 -LOG- [PA] Player 76561199273859331/'CrazyGamer919' login ok (LID: '0', JC: )
20-08:20:22.603 01_20 -LOG- EAC2: Registered CId=1, EId=-1, 76561199273859331//'CrazyGamer919'
20-08:20:22.652 01_20 -LOG- Client CId=1, EId=-1, 76561199273859331//'CrazyGamer919' asks to enter game BEFORE EAC decided on kick
20-08:20:29.877 01_20 -LOG- EAC2 ClientAuthStatus 'OK' called for CId=1, EId=-1, 76561199273859331/=/'CrazyGamer919' AFTER client asked to enter the game -> take player
20-08:20:30.206 01_20 -LOG- Task Type=nodeHandle ThreadId=132268 ManagedId=24
20-08:20:38.463 01_20 -LOG- Could not load player file or no last playfield for player CId=1, EId=-1, 76561199273859331/=/'CrazyGamer919' found, asking player for his last playfield
20-08:20:51.462 01_20 -LOG- Player CId=1, EId=-1, 76561199273859331/=/'CrazyGamer919' chose 'Omicron' as start planet
20-08:20:51.464 01_20 -LOG- Sending solar system (21000000, 1500000, 5000000) playfields to client CId=1, EId=-1, 76561199273859331/=/'CrazyGamer919'
20-08:20:51.465 01_20 -LOG- Player CId=1, EId=-1, 76561199273859331/=/'CrazyGamer919' connecting now to playfield 'Omicron'
20-08:20:51.466 01_20 -LOG- No server with playfield 'Omicron' available at the moment, will try loading soon...
20-08:21:00.989 01_21 -WRN- Killing booting server PID 124056 since it took longer than 90 seconds to report 'ready'
20-08:21:00.990 01_21 -LOG- Killed process with PID 124056
20-08:21:01.012 01_21 -LOG- Connection closed while reading (Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.

20-08:21:01.014 01_21 -LOG- PfServer (PID 124056) disconnected, no playfield loaded
20-08:21:04.026 01_21 -LOG- Started process 'EmpyrionPlayfieldServer.exe' (PID 137260) with args: -batchmode -nographics -logFile ../Logs/4536/Playfield_241020-012104-01.log "configFile=dedicated_config.yaml"
20-08:21:07.228 01_21 -LOG- New playfield server
20-08:21:07.228 01_21 -LOG- Thread 'Reader_127.0.0.1:51206' ThreadId=139676 ManagedId=28
20-08:21:07.228 01_21 -LOG- Thread 'Writer_127.0.0.1:51206' ThreadId=50264 ManagedId=29
20-08:21:10.429 01_21 -LOG- Booting PfServer (PID 137260) starts preparation after 6.4 seconds...
20-08:21:21.256 01_21 -LOG- INFO: Uptime=00h01m 60.016 2355 heap= 438MB fps=40.0 players= 0 pfs=r1/i0/a0 ticks=1399945 nwqueue=Net:0/1
20-08:22:21.260 01_22 -LOG- INFO: Uptime=00h02m 60.004 2389 heap= 439MB fps=40.0 players= 0 pfs=r1/i0/a0 ticks=1401145 nwqueue=Net:0/1
20-08:22:34.107 01_22 -WRN- Killing booting server PID 137260 since it took longer than 90 seconds to report 'ready'
20-08:22:34.107 01_22 -LOG- Killed process with PID 137260
20-08:22:34.109 01_22 -LOG- Connection closed while reading (Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.

20-08:22:34.132 01_22 -LOG- PfServer (PID 137260) disconnected, no playfield loaded
20-08:22:37.149 01_22 -LOG- Started process 'EmpyrionPlayfieldServer.exe' (PID 136104) with args: -batchmode -nographics -logFile ../Logs/4536/Playfield_241020-012237-13.log "configFile=dedicated_config.yaml"
20-08:22:40.334 01_22 -LOG- New playfield server
20-08:22:40.335 01_22 -LOG- Thread 'Reader_127.0.0.1:51340' ThreadId=134980 ManagedId=34
20-08:22:40.335 01_22 -LOG- Thread 'Writer_127.0.0.1:51340' ThreadId=134840 ManagedId=35
20-08:22:43.911 01_22 -LOG- Booting PfServer (PID 136104) starts preparation after 6.8 seconds...
20-08:23:21.279 01_23 -LOG- INFO: Uptime=00h03m 60.018 2387 heap= 439MB fps=40.0 players= 0 pfs=r1/i0/a0 ticks=1402345 nwqueue=Net:0/1
20-08:23:47.015 01_23 -LOG- EAC2: Unregistered CId=1, EId=-1, 76561199273859331/=/'CrazyGamer919' C
20-08:23:55.674 01_23 -LOG- [Steamworks.NET] Kicking player CId=1, EId=-1, 76561199273859331/=/'CrazyGamer919' with invalid login. Response: k_EAuthSessionResponseAuthTicketCanceled
20-08:23:55.675 01_23 -LOG- Server kicking player CId=1, EId=-1, 76561199273859331/=/'CrazyGamer919': Kicked by STEAM (AuthTicketCanceled). Please check your login data. (Maybe a Family Sharing problem?)
20-08:23:58.675 01_23 -WRN- Disconnect player: PfServer for client 1 not found (B)!
20-08:23:58.676 01_23 -LOG- Client CId=1, EId=-1, 76561199273859331/=/'CrazyGamer919' disconnected (was waiting for playfield)
20-08:23:58.677 01_23 -LOG- [CM] Player CId=1, EId=-1, 76561199273859331/=/'CrazyGamer919' disconnected
20-08:23:58.678 01_23 -LOG- Steam: EndAuthSession for SteamID 76561199273859331
20-08:24:07.194 01_24 -WRN- Killing booting server PID 136104 since it took longer than 90 seconds to report 'ready'
20-08:24:07.195 01_24 -LOG- Killed process with PID 136104
20-08:24:07.197 01_24 -LOG- Connection closed while reading (Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.

20-08:24:07.219 01_24 -LOG- PfServer (PID 136104) disconnected, no playfield loaded
20-08:24:10.239 01_24 -LOG- Started process 'EmpyrionPlayfieldServer.exe' (PID 134680) with args: -batchmode -nographics -logFile ../Logs/4536/Playfield_241020-012410-21.log "configFile=dedicated_config.yaml"
20-08:24:13.772 01_24 -LOG- New playfield server
20-08:24:13.772 01_24 -LOG- Thread 'Reader_127.0.0.1:51485' ThreadId=130024 ManagedId=40
20-08:24:13.772 01_24 -LOG- Thread 'Writer_127.0.0.1:51485' ThreadId=140296 ManagedId=41
20-08:24:17.345 01_24 -LOG- Booting PfServer (PID 134680) starts preparation after 7.2 seconds...
20-08:24:21.295 01_24 -LOG- INFO: Uptime=00h04m 60.015 2386 heap= 436MB fps=40.0 players= 0 pfs=r1/i0/a0 ticks=1403546 nwqueue=
20-08:25:21.301 01_25 -LOG- INFO: Uptime=00h05m 60.005 2389 heap= 434MB fps=40.0 players= 0 pfs=r1/i0/a0 ticks=1404746 nwqueue=
20-08:25:40.307 01_25 -WRN- Killing booting server PID 134680 since it took longer than 90 seconds to report 'ready'
20-08:25:40.307 01_25 -LOG- Killed process with PID 134680
20-08:25:40.310 01_25 -LOG- Connection closed while reading (Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.

20-08:25:40.332 01_25 -LOG- PfServer (PID 134680) disconnected, no playfield loaded
20-08:25:43.347 01_25 -LOG- Started process 'EmpyrionPlayfieldServer.exe' (PID 124076) with args: -batchmode -nographics -logFile ../Logs/4536/Playfield_241020-012543-33.log "configFile=dedicated_config.yaml"
20-08:25:46.832 01_25 -LOG- New playfield server
20-08:25:46.833 01_25 -LOG- Thread 'Reader_127.0.0.1:51627' ThreadId=111228 ManagedId=46
20-08:25:46.833 01_25 -LOG- Thread 'Writer_127.0.0.1:51627' ThreadId=128664 ManagedId=47
20-08:25:50.658 01_25 -LOG- Booting PfServer (PID 124076) starts preparation after 7.4 seconds...
20-08:26:21.323 01_26 -LOG- INFO: Uptime=00h06m 60.022 2389 heap= 434MB fps=40.0 players= 0 pfs=r1/i0/a0 ticks=1405946 nwqueue=
20-08:27:13.395 01_27 -WRN- Killing booting server PID 124076 since it took longer than 90 seconds to report 'ready'
20-08:27:13.395 01_27 -LOG- Killed process with PID 124076
20-08:27:13.398 01_27 -LOG- Connection closed while reading (Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.

20-08:27:13.420 01_27 -LOG- PfServer (PID 124076) disconnected, no playfield loaded
20-08:27:16.447 01_27 -LOG- Started process 'EmpyrionPlayfieldServer.exe' (PID 135068) with args: -batchmode -nographics -logFile ../Logs/4536/Playfield_241020-012716-42.log "configFile=dedicated_config.yaml"
20-08:27:20.075 01_27 -LOG- New playfield server
20-08:27:20.075 01_27 -LOG- Thread 'Reader_127.0.0.1:51744' ThreadId=142268 ManagedId=55
20-08:27:20.075 01_27 -LOG- Thread 'Writer_127.0.0.1:51744' ThreadId=127424 ManagedId=56
20-08:27:21.323 01_27 -LOG- INFO: Uptime=00h07m 59.999 2387 heap= 434MB fps=40.0 players= 0 pfs=r1/i0/a0 ticks=1407146 nwqueue=
20-08:27:23.722 01_27 -LOG- Booting PfServer (PID 135068) starts preparation after 7.3 seconds...
20-08:28:21.333 01_28 -LOG- INFO: Uptime=00h08m 60.009 2387 heap= 434MB fps=40.0 players= 0 pfs=r1/i0/a0 ticks=1408346 nwqueue=
20-08:28:46.509 01_28 -WRN- Killing booting server PID 135068 since it took longer than 90 seconds to report 'ready'
20-08:28:46.509 01_28 -LOG- Killed process with PID 135068
20-08:28:46.511 01_28 -LOG- Connection closed while reading (Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.

20-08:28:46.534 01_28 -LOG- PfServer (PID 135068) disconnected, no playfield loaded
20-08:28:49.546 01_28 -LOG- Started process 'EmpyrionPlayfieldServer.exe' (PID 123316) with args: -batchmode -nographics -logFile ../Logs/4536/Playfield_241020-012849-53.log "configFile=dedicated_config.yaml"
20-08:28:53.281 01_28 -LOG- New playfield server
20-08:28:53.282 01_28 -LOG- Thread 'Reader_127.0.0.1:51893' ThreadId=59852 ManagedId=63
20-08:28:53.282 01_28 -LOG- Thread 'Writer_127.0.0.1:51893' ThreadId=66128 ManagedId=64
20-08:28:57.408 01_28 -LOG- Booting PfServer (PID 123316) starts preparation after 7.9 seconds...
20-08:29:21.351 01_29 -LOG- INFO: Uptime=00h09m 60.017 2387 heap= 434MB fps=40.0 players= 0 pfs=r1/i0/a0 ticks=1409547 nwqueue=

### Game Seed

919

**Comment by CrazyGamer9191** [comment]
Forgot the part about it doesn`t load with default setting either

**Comment by CrazyGamer9191** [comment]
So far, I validated the server files twice, my files twice, uninstalled and reinstalled, then started brand new save with default settings and still get stuck at the loading screen after planet selection

**Comment by CrazyGamer9191** [comment]
My server company got it fixed

**Comment by RavienGaming** [comment]
Ah glad you were able to get it working!
