### ISSUE TITLE
Problem with door closing in pois when dying on server

### ISSUE THREAD

**Issue by nikelnac** [RavienGaming/Reforged-Eden-2#355]
### Reforged Eden 2 Build Number

23

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Playing on a server, Inside of the Ghyst Military Base, we ran into a problem, that after we died, the B2 Acces door closed for some Reason and was not opend by the sensor again. The Problem seems to be a bug, that once one input of the 2xOr is on but the door shuts, the second input does not open the B2Acces Door. I tried the last 3 Hours to find a circuit setup to resolve the issue, was not succesfull. The simplest way to solve this in my opinion would be to install a second sensor, which turns on with the access terminal and replaces the acces terminal as input in the 2xOr.
Greetings, Nikelnac

### POI Name

Ghyst Military Base

**Comment by RavienGaming** [comment]
Did you try restarting your game back to windows desktop? If you die or leave an area, doors will appear close to you due to desync.

**Comment by nikelnac** [comment]
I am playing on a server, admin opend the door for me, so problem resolved. Just wanted to mention the Problem

**Comment by RavienGaming** [comment]
> I am playing on a server, admin opend the door for me, so problem resolved. Just wanted to mention the Problem

Glad you were able to get it fixed. If it happens again try relogging as doors can often become desync (it's actually open but on your screen it appears closed). It's a game bug.
I will go ahead and close this report though.
