### ISSUE TITLE
Deconstructors automatically break down items like autominer cores

### ISSUE THREAD

**Issue by Garaman-EGS** [RavienGaming/Reforged-Eden-2#358]
### Reforged Eden 2 Build Number

23

### Game mode

Survival, Creative, Single Player

### Tested in vanilla

Issue does not happen in vanilla

### Description of issue

Due to a change in the way vanilla deconstructors work a while ago, all items that can be deconstructed in a chain are fully broken down regardless of where the output of the decon is being sent. Deconstructing items like autominers ends up breaking down the autominer cores automatically, meaning you can't rebuild them.

The PDA now incorrectly states that autominer cores can be preserved by changing the output box, which they cannot.

This also affects things like computers, which always break down into parts when deconning items like antennas (this is confirmed to be a vanilla issue).

T1 (basic) autominer: Note the separate output box, and the decon list showing the parts for the autominer core:
![20241026145101_1](https://github.com/user-attachments/assets/6159ecac-2b6d-4bfe-9e16-c7de3bf3d945)

Full output of the decon run:
![20241026145205_1](https://github.com/user-attachments/assets/eeba1633-ab18-430f-8e83-a77501caa5df)

**Comment by suntrip76** [comment]
Can confirm this. I just tried with a T1 autominer as well and got the same. Looking at aMusic's Empyrionbuddy that pulls data from the game, it should give you what you put into building it - but alas the deconstructor does seem to have a mind of it's own.

![billede](https://github.com/user-attachments/assets/4fbf060f-b667-4903-b479-1dd876ab201e)

**Comment by VermillionX** [comment]
Blocked the deconstruction of Autominer cores and all crafting components that break down into ingots for next update.
Computers don't break down into ingots though. So should they decon into their component parts or remain whole?

**Comment by suntrip76** [comment]
For me personally it doesn't matter if computers break down or not. It's a craftable item so the only thing you would lose is crafting time if you break them down, On the other hand the ingredients are pretty basic so I would probably never decon any for that. Probably just leave them whole, imo.

**Comment by 8836290** [comment]
> Blocked the deconstruction of Autominer cores and all crafting components that break down into ingots for next update. Computers don't break down into ingots though. So should they decon into their component parts or remain whole?

Some of us need those bridges from CPUs and those cores from auto miners to build the bigger/advanced versions. Same goes for many other devices. So please consider our option. Thank you.

**Comment by RavienGaming** [comment]
> > Blocked the deconstruction of Autominer cores and all crafting components that break down into ingots for next update. Computers don't break down into ingots though. So should they decon into their component parts or remain whole?
> 
> Some of us need those bridges from CPUs and those cores from auto miners to build the bigger/advanced versions. Same goes for many other devices. So please consider our option. Thank you.

I believe this prevents autominer cores themselves from being broken down, NOT prevents automining devices or CPU extenders from being deconstructed. I think.

**Comment by VermillionX** [comment]
The change stops crafting components like Energy Regulators, Advanced Electronics, Flux Coils and Autominer Cores from being deconstructed into raw materials.
It does not stop you from deconstructing autominer devices, CPU extenders or any other block/weapon/device.
