### ISSUE TITLE
Can´t Create new Gamestate. Testet on 2 PC with Costum and Default Game Settings

### ISSUE THREAD

**Issue by MrBons4i** [RavienGaming/Reforged-Eden-2#359]
### Reforged Eden 2 Build Number

23

### Game mode

Survival

### Tested in vanilla

Issue does not happen in vanilla

### Description of issue

I can't create a new world. I only get to the loading planet and then it ends. Then I only have the blue loading screen

**Comment by RavienGaming** [comment]
If you fully restart the game back to windows desktop, and then go to start new game > scenarios > Reforged Eden 2 > and then without changing any of the settings at all, click start game, does it load okay?

And did you get the scenario from Steam or Nexus Mods?

**Comment by MrBons4i** [comment]
okay it works
