### ISSUE TITLE
Rock'n & Rolling

### ISSUE THREAD

**Issue by BJStryker** [RavienGaming/Reforged-Eden-2#361]
### Reforged Eden 2 Build Number

23

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Hi Folks, I am flying Omicron's Promise and I'm on Akua Moon. Just Been mining Aluminum and made my way to the surface to takeoff into the air and I find myself stuck in the center of the hole, level with the ground and stuck rocking back and forward, I can do nothing with control as they don't really respond. does this mean I have to restart my game?
Regards
BJ

**Comment by RavienGaming** [comment]
Most likely not a scenario bug. Your ship is probably too heavy to take off, your thrusters are off, etc.

**Comment by BJStryker** [comment]
Thanks for the msg Ravien, the thrusters were off so that the fuel didn't run out as fast as it would leaving them on. I will check when I get home to see if it has resolved itself. I restarted the game several times and it made no difference I was still stuck. Regards bj

Yahoo Mail: Search, organise, conquer 
 
  On Sun, 27 Oct 2024 at 18:47, ***@***.***> wrote:   


Most likely not a scenario bug. Your ship is probably too heavy to take off, your thrusters are off, etc.
