### ISSUE TITLE
Akua Sparkling wine, color code error in tooltip

### ISSUE THREAD

**Issue by suntrip76** [RavienGaming/Reforged-Eden-2#362]
### Reforged Eden 2 Build Number

B23

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Looks like the color code before the applied status effect is missing a digit:

![billede](https://github.com/user-attachments/assets/8d7b420a-b7e5-4361-804e-245f28996400)

**Comment by VermillionX** [comment]
Fixed for next update. Also applies to beer.
