### ISSUE TITLE
Akua ancient tower

### ISSUE THREAD

**Issue by Duke-Engi** [RavienGaming/Reforged-Eden-2#363]
### Reforged Eden 2 Build Number

4541

### Game mode

Co-op

### Tested in vanilla

Issue does not happen in vanilla

### Description of issue

Ancient Tower on Akua - climbing up the Pyramide-like Tower - in the middle i felt down (due to game switch) and now i am stuck - cant get out of that. worst escape room ever -.-

### Error code from console or log (Optional)

no error code

### POI Name

Ancient Tower

### Star Name

Akua

### Mission Name

no mission, just exploring

### Mission Objective

no mission, just exploring

**Comment by VermillionX** [comment]
That is a story POI. You should only enter if if you're doing the story missions.
There is only an exit when performing the missions and this will not be changed in order to prevent players from leaving the POI through any other exit than the story-based one (where the wall explodes).
