### ISSUE TITLE
IDA gone rogue on Rogue

### ISSUE THREAD

**Issue by BillySuggers** [RavienGaming/Reforged-Eden-2#364]
### Reforged Eden 2 Build Number

Build 23

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Main story IDA message keeps repeating after that a step of the mission has yet to be completed.
 I'm now tasked with the next one....'Escape the Planet: Reach Space' but her prior message has been popping up repeatedly. Not constantly but something seems to keep triggering it quite often. Dozen or so times so far.

![20241028120415_1](https://github.com/user-attachments/assets/b71ad279-60cb-41c3-9a04-5efcf10c7871)

![20241028121533_1](https://github.com/user-attachments/assets/fab00862-a3b5-463a-911c-022f791b815e)

### POI Name

n/a

### Playfield Name

Rogue 

### Playfield Class

Rogue Starter Planet

### Star Name

Epsilon

### Star Class

Rogue Starter M

### Mission Name

Rogue starter planet mission

### Mission Objective

Escaping the crashed zirax ship was completed but IDA keeps prompting that it is yet to happen me

### Game Seed

197980

**Comment by RavienGaming** [comment]
If another PDA event triggers such as a tutorial popup this will cause the message to re-display when the mission is automatically resumed. This is normal and nothing I can do about it anyway. For example the first time you would open the solar system map there's a popup message, that would have caused the IDA message to also popup.
