### ISSUE TITLE
Many Systems are unable to warp to - error reported

### ISSUE THREAD

**Issue by dgladbac** [RavienGaming/Reforged-Eden-2#365]
### Reforged Eden 2 Build Number

23

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

When trying to warp to man various systems, an error is received and you can not go to that system.  Error is reported on dedicated server.
Using AMP deployment on Debian 12 linux.  (all fresh installed and latest versions)

Log excerpt when player tries to go an affected system.
28-03:09:20.608 03_09 -LOG- Generating solar system Bushob-ae/(11300000, 1900000, 11800000) in Z:\AMP\empyrion-galactic-survival\530870/HNYBSaves/Games/HNYBGame/Sectors
Generating solar system Bushob-ae/(11300000, 1900000, 11800000) in Z:\AMP\empyrion-galactic-survival\530870/HNYBSaves/Games/HNYBGame/Sectors
28-03:09:20.638 03_09 -ERR- No config found for 'AsteroidFieldPolaris'
No config found for 'AsteroidFieldPolaris'
NullReferenceException: Object reference not set to an instance of an object
  at Assembly-CSharp.AddinSerializer.SortGroup (Assembly-CSharp.PageConverter , System.String ) [0x00000] in <590d704a9ea84db8b1e5fec8e7b1f2c2>:0 
  at Assembly-CSharp.AddinSerializer.SelectDockingPane (System.Collections.Generic.List`1[T] , System.String , System.Random ) [0x00033] in <590d704a9ea84db8b1e5fec8e7b1f2c2>:0 
  at Assembly-CSharp.AddinSerializer.ShowCondition (Assembly-CSharp.AddinSerializer+SymbolTree , System.Collections.Generic.List`1[T] , System.Random , System.Int32 ) [0x001bb] in <590d704a9ea84db8b1e5fec8e7b1f2c2>:0 
  at Assembly-CSharp.AddinSerializer.SplitDatabase (System.String , System.Int32 ) [0x00020] in <590d704a9ea84db8b1e5fec8e7b1f2c2>:0 
  at Assembly-CSharp.LineHelper.AttachReference (Vector3i ) [0x000e7] in <590d704a9ea84db8b1e5fec8e7b1f2c2>:0 
  at Assembly-CSharp.MemoryInvoker+MethodService.MoveNext () [0x00047] in <590d704a9ea84db8b1e5fec8e7b1f2c2>:0 
  at Assembly-CSharp.MemoryInvoker+AspectSet.MoveNext () [0x00065] in <590d704a9ea84db8b1e5fec8e7b1f2c2>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00026] in <02010b5490ff415d9ed82c30dd975ea6>:0 
  

In testing, so far all these systems give this error. (number occurances over 2hours of trying to travel around)
	Line  822: 28-03:09:20.638 03_09 -ERR- No config found for 'AsteroidFieldPolaris'
	Line  846: 28-03:10:01.809 03_10 -ERR- No config found for 'AsteroidFieldPolaris'
	Line  886: 28-03:13:28.909 03_13 -ERR- No config found for 'AsteroidFieldPolaris'
	Line  910: 28-03:14:47.837 03_14 -ERR- No config found for 'AsteroidFieldPirate'
	Line 1066: 28-03:30:07.810 03_30 -ERR- No config found for 'AsteroidFieldPirate'
	Line 1091: 28-03:32:24.607 03_32 -ERR- No config found for 'AsteroidFieldPolaris'
	Line 1116: 28-03:33:43.832 03_33 -ERR- No config found for 'AsteroidFieldPolaris'
	Line 1241: 28-04:02:55.907 04_02 -ERR- No config found for 'AsteroidFieldPolaris'
	Line 1268: 28-04:04:39.408 04_04 -ERR- No config found for 'AsteroidFieldPolaris'
	Line 1294: 28-04:06:12.808 04_06 -ERR- No config found for 'AsteroidFieldPolaris'
	Line 1315: 28-04:06:59.233 04_06 -ERR- No config found for 'AsteroidFieldPolaris'
	Line 1341: 28-04:08:28.858 04_08 -ERR- No config found for 'AsteroidFieldPolaris'
	Line 1366: 28-04:09:49.659 04_09 -ERR- No config found for 'AsteroidFieldPirate'
	Line 1393: 28-04:12:40.757 04_12 -ERR- No config found for 'AsteroidFieldPirate'
	Line 1417: 28-04:13:38.832 04_13 -ERR- No config found for 'AsteroidFieldPolaris'
	Line 1444: 28-04:15:27.233 04_15 -ERR- No config found for 'AsteroidFieldPolaris'
	Line 1504: 28-04:23:49.509 04_23 -ERR- No config found for 'AsteroidFieldPirate'
	Line 1528: 28-04:24:40.312 04_24 -ERR- No config found for 'AsteroidFieldPolaris'
	
[AMPLOG 2024-10-28 00-00-00.log](https://github.com/user-attachments/files/17548489/AMPLOG.2024-10-28.00-00-00.log)

### Playfield Name

many different playfields don't open and allow to transfer in

### Playfield Class

listed in log file attached

### Game Seed

1011345

**Comment by RavienGaming** [comment]
This sounds like a server configuration issue. The asteroid fields it cannot find are not used anywhere in the scenario anymore.


> Using AMP deployment on Debian 12 linux.

I am not familiar with AMP. Also the developers do not support using Linux at all (I know it's silly but they don't) either.
Not sure if either or both of those are the cause of your issues but this is something either with the server config or something went wrong when you copied the scenario to the server.

**Comment by dgladbac** [comment]
Okay,  Did more playing around when trying not to actually do work today and there seemed to be something not right when the playfields/etc were built.   We decided to start from a clean wipe and let it rebuilt.   So much different now and I think that was underlying problem.
Please close this out as I think that might have solved whatever happened in initial server setup.  Will address any new issues separately, but I think we have a much better setup this time.
thanks for checking .
