### ISSUE TITLE
CV manual Weapons damage output changed?

### ISSUE THREAD

**Issue by X2return** [RavienGaming/Reforged-Eden-2#367]
### Reforged Eden 2 Build Number

22

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Game Version: 1.11.9, RE2 Build 22 (online MP) and 23 (offline SP)
Subject: Weapon damage of Laser- and Plasma Cannons for CV (Dual, Triple).
Reason / Problem:  Extremely hard to fight legacy Ships online only.
Can be reproduced: SP Savegame

I testet every manual CV weapon on every armored Block type (Shield offline) and wrote everything in a sheet for calculations.
I stopped the time for every weapon until break through 3 layers and Core or max 30 seconds and fed the sheet.
Sheet is calculating Sum of killed Blocks HP + Core HP + Damage done on the left Block.
- Result is devided by the recorded seconds (to get Single Weapon DPS).
- Result is devided by number of Cannons used (always 1 but prepared formula ... just in Case), and multiplied with max placeable number of Cannons (wich is 16 für Dual Cannons and 8 für Triple Cannons).

Average DPS with 16 Cannons installed. Target Single Xeno Block / Alien Block
- Dual Laser Cannons (approx: 49k / 37k dps)
- Dual Plasma Cannons (approx: 10k / 31k dps)

Average DPS with 8 Cannons installed.
- Triple Laser Cannons (approx: 74k / 63k dps)
- Triple Plasma Cannons (approx: 7,8k / 6,9k dps) I tested twice because of THAT low value compared to others
The Plasma Cannons also did some minor damage on the surrounding Blocks but doesen't really matter for this topic as it's been meassured with static objects.

My problem here: the SP dps doesn't match the MP dps at all when solo fighting a hostile Legacy CV.
Dependend on the Values above I keep useing Laser Cannons even when the shield is down but it takes ages to kill 1 single Block. Still hard but way faster with Plasma and because of the values above i wonder why.

RE2 Info: SP-build is 23, Server Build is 22.
I can't find something in the Changelog wich could explain the difference.
I'm playing on Rexxxus HWS RE2 EU and have been promised that no Server-configs related to specific weapon damage been changed.

Hope this is everything relevant.
Any ideas?

**Comment by VermillionX** [comment]
Are you shooting at a moving ship in both instances? And from which direction?
There's a long-term game bug with shooting moving ships where hits on the rear will only be calculated half the time.

**Comment by RavienGaming** [comment]
Probably one of the issues in #12

**Comment by X2return** [comment]
You're right, in SP both objects are not moving - just spawned in therefore created Builds wich means a smal CV to mount a weapon and another CV without thrusters - just a wall of 3 layers in front of the Core.
Because i couldn't belive the results i spawned in an eradicator as it is. Angle is 90 degrees directly from above in core direction.

I got a bit experience in aiming last years (not only face2face wich doesn't work anymore) and been successful useing the LX-2. But due to its size i want to try other Cannons. I'm not shooting from behind - straight from above and after first 2-3 Shots i see where the Latency puts my Bullets to compensate that. Also that slow rolling of em makes it hard to aim but these effects aren't new.
First i take down enemys shields and reload mine. After that I move in again os i only have to shoot the generated 10-15%.
And I think something must be wrong when my 170k shields are down before the first hostile Block disappears but thats another thing. Back to topic.

The Lasers Tooltip shows a damage boost to Xeno Blocks and in SP i confirmed that bonus seems also counting on Alien Blocks.
In SP the Plasmas do less damage on single block because we have to add the Blast damage done to surrounding Blocks.
Well in SP the Xeno Blocks melt like Butter under Fire with lasers even on Dual-Cannons.
But Online it seems to be the opposite. I'm not able to aim accurate with Plasmas because they just damage the hole area a bit. I just can't see wich exact Block i actually hit. But the Xeno Blocks still disappear faster using 10 Dual-Plasma as they to with 8x Triple Lasers.

**Comment by X2return** [comment]
Thank you Ravien but none of these - i'm not shooting from behind.

**Comment by RavienGaming** [comment]
This would be a game bug then. I will attach the steps to properly report it to the game developers below:

This is likely a game bug and will need to be reproduced and reported using a vanilla save game.
When reproducing a game bug in a vanilla save, make sure you are using the same mode _(singleplayer/co-op/dedicated multiplayer, survival/creative)_ as what you were using when the issue happened in the scenario.
To see a list of known game bugs or to report a new one please see: https://empyriononline.com/forums/bugs.24/

**Comment by X2return** [comment]
I tried to follow but
this problem cannot be reproduced in vanilla because none of the used weapons are existing in a vanilla game. I wonder how it can even be a game bug as such.

**Comment by RavienGaming** [comment]
You would need to test with a similar vanilla weapon.

**Comment by X2return** [comment]
There is no similar weapons like Plasma Cannon to compare in vanilla.
There's just a Rocket Launcher and a Pulse Laser.

**Comment by RavienGaming** [comment]
Yes, you'd have to use those weapons to reproduce the issue. Or use the SV plasma cannon.

**Comment by X2return** [comment]
I really can imagine, that u got a lot of work to do at the moment so please don't get me wrong but what are you actually trying to do here?
You want to force it just NOT to be your problem by comparing the problem with ... it seems like any other device wich has nothing to do with the actual case. If i found a way to follow here next you tell me i have to try bandages and mining drill to reproduce the major problem here.

The problem exists only between Online B22 and Offline B23 RE2 experience. It appears within RE2 only content and Devices.
I have to take a vanilla SV-weapon to reproduce an error wich only appears at a difference between RE2-only devices?
What do you think will Eleon tell me then and what happens except your saved time here when i make a bug report?

If you don't have the time to take care about my poor little troubleshooting here you just should have told me but what's happening here is just ... ridiculous! We all know about that unfinished and not at all optimized base game design.
Well, for me it looks like RE2 is a great idea but far too big and overdid to be realized properly and with your kind of attitute ... there are enough other games to play out there!

You can close and forget or even delete this ticket - under that circumstances i won't bother you guys again and waste more of your time by reporting or feedback anything.

**Comment by VermillionX** [comment]
We can set the projectile speed, damage, blast radius values of a weapon.
We can set the hardness, block hp and material modifiers of a block.
That is the extent of what we can change. The numbers have _not_ been changed, nor can they be changed between SP and MP, or between a static object or a moving ship.

The values we set are just the numerical values that the game code uses for the calculations. If the output of those calculations are different between a multiplayer and singleplayer environment, or against a moving object vs a static one then those are aspects that are completely outside our ability to change, alter, fix or even examine.
It is a bug. It is not OUR bug. We did not cause it and we are not able to fix it.

**Comment by X2return** [comment]
You're telling me you only playing with some already existing numberic values. So i have to assume that bunch of about 20 new Cannons (in addition of twice the Turrets and many other RE/RE2 only objects) within CV Cannons category appeared by some magic hands between my display and my face. Understood

I wonder what Eleon will answer when i'd start telling them about a problem within some strange, unknown devices, not existing in a vanilla game, not developed from THE ONLY Mod i use but it can only be their fault somehow ... They'll be glad to hear about magically appearing new content in EGS mostly working sometimes.

Well, making it anyone others problem is not the only way to handle this situation but possibly the fastest and easiest.
Guys, i really love your Mod all the years and didn't want to play without because it actually is a positive gamechanger, even if it totally overloads some servers and overwhelmes some server owners.
But the only thing i can agree here is the possible assumption "we are not able to fix".

Please excuse the inconvinience, we're really done here.

**Comment by RavienGaming** [comment]
This issue has already been reported here: #12

**Comment by 8836290** [comment]
> You're telling me you only playing with some already existing numberic values. So i have to assume that bunch of about 20 new Cannons (in addition of twice the Turrets and many other RE/RE2 only objects) within CV Cannons category appeared by some magic hands between my display and my face. Understood
> 
> I wonder what Eleon will answer when i'd start telling them about a problem within some strange, unknown devices, not existing in a vanilla game, not developed from THE ONLY Mod i use but it can only be their fault somehow ... They'll be glad to hear about magically appearing new content in EGS mostly working sometimes.
> 
> Well, making it anyone others problem is not the only way to handle this situation but possibly the fastest and easiest. Guys, i really love your Mod all the years and didn't want to play without because it actually is a positive gamechanger, even if it totally overloads some servers and overwhelms some server owners. But the only thing i can agree here is the possible assumption "we are not able to fix".
> 
> Please excuse the inconvenience, we're really done here.

If you open the files of RE2 configuration like blocks.ecf devices.ecf etc you will see for various game entities the designation "Class" i.e. for the plasma weapons there is designation :"Class: weapon" for rocket launchers the same etc. The "Class" type is a reference of what type the device or item is. This reference is coded/described in part of the game code that the scenario creators do not have access but need to define in RE and RE2 for example, in order to give the block or item its characteristics of the class. 

The classes are defined in part of the code of the game by the Empyrion developers. Scenario creators know this by looking on the original files of Test scenario and asking questions the developers on how to define a new weapon for example and which characteristics to give it to what extend.

As it is said hit points, damage, projectile speed, blast radius etc are values the developers have open to be defined by scenario creators. The Classes are not. Classes are only available to the part of the code of the game only the developers can change. Classes have to be "hidden" because in programming it is how programmers create stuff and is considered IP (Intellectual Property), when for example the games are sold, like it happens with Empyrion. 

This is how I understand it. There are parts that are open for editing so the scenario creators can use those values and define them as they want, in order to create a new scenario. But they can not create something really new a new item or device. Everything new we see in RE2 and all scenarios are in fact modified versions of devices items etc already defined in the code of the game by the developers. This is essence how modification works in games and RE2 scenario is a modification (mod).

If we understand the above we can not be mad at Ravien or Vermilion. 

Correct me if I am wrong please. Thank you.

**Comment by RavienGaming** [comment]
That's a pretty good explanation of things, yes. Everything "new" we add is just clever use of an existing game mechanic to use in a new way. The OP's issue was already reported to the game developers using tests in vanilla by multiple players, including myself, and is linked in #12 .

The bug report for this exact issue was filed 2 and a half years ago and all we can do is wait for a fix from the game developers.
I even submitted multiple videos and additional information on that bug report, so it's a bit frustrating to have been accused of being lazy over this.
