### ISSUE TITLE
Deco Sattelite Dishes Colliders extend below the dish base

### ISSUE THREAD

**Issue by Ente2k** [RavienGaming/Reforged-Eden-2#368]
### Reforged Eden 2 Build Number

23

### Game mode

Creative

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

The Collider for the Sattelite Dishes DecoDish9x9, DecoDish5x5 and DecoDish9x9V2 extend below their bases. If you build a ramp with the dish directly below, you cannot use the ramp as you will collide with the dish. See picture.

![grafik](https://github.com/user-attachments/assets/9a7da1d4-424f-43c3-a52b-e2a202813209)

**Comment by Ente2k** [comment]
Also affects the CV Long Range Radar Array.

**Comment by VermillionX** [comment]
Uses a box collider because Eleon's system doesn't allow mesh colliders without causing invincibility and the only other default collider shapes that unity has are spherical. So... not a bug.
It's a satellite dish, not a ramp.

**Comment by Ente2k** [comment]
Yeah the ramp is the red thing in the white circle in my screen, above the dish. The box collider extends into it, thats what I wanted to report. I did add some boxes to the image to show what I mean:
![grafik](https://github.com/user-attachments/assets/9a516b4d-e4d9-4a1b-a09f-3f536431442c)
(probably slightly exggerated for visibility)

**Comment by VermillionX** [comment]
OH, you mean that the collider is in the way. My bad.
I can probably fix that.

**Comment by VermillionX** [comment]
Fixed for next update.
