### ISSUE TITLE
Colonists, Traders and Farr faction start as Hostile by default

### ISSUE THREAD

**Issue by Mario-Radinovic** [RavienGaming/Reforged-Eden-2#37]
### Reforged Eden 2 Build Number

RE2 Build 3

### Game mode

Survival

### Tested in vanilla

Issue does not happen in vanilla

### Description of issue

Starting new survival game without having any interaction with any factions (using sector command in god mode to discover the factions) has Colonists, Trade Federation and Farr default as hostile (displaying 12000/12000 reputation)

![20240509101625_1](https://github.com/RavienGaming/Reforged-Eden-2/assets/65545773/186afdc5-5912-4a18-9b7c-2ffb714ce996)

**Comment by RavienGaming** [comment]
Thanks. Fixed for the next update.
