### ISSUE TITLE
Project Eden 2 Mission Trigger:Bandit Alarm T2 doesn't stop logging

### ISSUE THREAD

**Issue by Powermonkey00** [RavienGaming/Reforged-Eden-2#371]
### Reforged Eden 2 Build Number

23

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

The Bandit Alarm triggered by wreckage both doesn't spawn bandits AND will log dialogue infinitely after being triggered.
![image](https://github.com/user-attachments/assets/f79f2f2d-5951-468d-b233-bc4e86931e19)
![image](https://github.com/user-attachments/assets/bb2a3fb7-9ef1-44b9-99fb-8152507c05fe)

**Comment by RavienGaming** [comment]
Seems like ships spawned via the PDA respect faction territory, so bandits won't show up inside of a faction's galactic territory that doesn't allow the Warlord faction. I added a note on the bandit trap that they won't show up if you're inside of a territory, about the best I can do. So I will mark this as "fixed".

Please feel free to post again if you notice it happening in a playfield in neutral territory, however.
