### ISSUE TITLE
My rifle is attached to the back of my head clipping into my character

### ISSUE THREAD

**Issue by iflogic** [RavienGaming/Reforged-Eden-2#372]
### Reforged Eden 2 Build Number

23

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

This is only a problem with some of the special weapons found in loot boxes. At least that's the only place I've ever found them.
I tend to play in first person except when flying ships and occasionally when exiting my ship (SV/HV) for a moment to pick something up.

The following handheld weapons included in this issue are:

Light Railgun Rifle. When turning left or crouching I can't see much except my left shoulder and part of the weapon.
I think this also happens when running, but I couldn't get a screenshot while running for any of the weapon, (Steam Issue?).

MLS-78 Laser Minigun. When standing or crouching it's hard to see past the arms and weapon as they fill most of the screen. Also, no screen shot when running.

X-Corp LR-47 Thunderbolt. When standing I can't see anything other then the weapon, my left forearm/hand and the back of my head. When crouching I can see better. When running it's worse.

Gauss Shotgun. When running I can't see past my left shoulder. Otherwise it appears to be fine.

MAK-223 Light Scout Rifle. When crouching can't see past my left shoulder, barely see the weapon, otherwise really can't see where I'm going at all. This came to light when trying to crouch/crawl through some passage way to get to a core.

So far these are the only one's I've had issue with. Of course they are the only one's I've found so far in the game. There are no error codes with these, just the graphical issues is all. The only one I took the time to try and fix was the Thunderbolt which all I did was edit the ItemsConfig.ecf file in the area for this weapon. Specifically I just removed the # in front of the Standingposition that had it in front of it, and added the # in front of the next line for Standingposition that didn't have it.

![Thunderbolt - When standing](https://github.com/user-attachments/assets/e7e0df97-84b0-4acd-b7e6-98a4ea6006b7)
![MAK-223 Light Scout - When Crouching](https://github.com/user-attachments/assets/9bfc7fcf-c51d-49ed-b68a-9abfe2679f6e)
![Laser Minigun - When standing](https://github.com/user-attachments/assets/4aa1d0c3-618d-4af6-aaf5-a1f6259f5b63)
![Gauss Shotgun - When crouching](https://github.com/user-attachments/assets/ba4c8a82-063f-4dc8-a498-6bc1116bdccf)
![Thunderbolt - when crouching](https://github.com/user-attachments/assets/b5224b11-844a-4996-ad36-48403b5f82df)
![Light Railgun - When Crouching](https://github.com/user-attachments/assets/f35d4497-e563-4fe2-9ef1-628d37f0c968)
![Laser Minigun - When Turning Left](https://github.com/user-attachments/assets/e99375d3-f61c-496a-ae4c-fb206c6a6883)
![Light Railgun Rifle - when crouching](https://github.com/user-attachments/assets/dc124425-0b42-46d7-a107-e97906223955)

**Comment by RavienGaming** [comment]
Are you using the workshop version of the scenario or a modded, local version? I ask because the models were changed in the last update, which required updates to the Movements so that they don't clip into the player's views which we did.

**Comment by iflogic** [comment]
I'm using the workshop version as far as I know. I can try again to download it and re-run. But I when I updated from build 22 to 23 I just went in and started playing. I'll redo the files by unsubbing and resubbing to see if that fixes it. Thanks.

**Comment by iflogic** [comment]
Ok then. I just un-subbed and re-subbed and that seems to have fixed it. I've just went through all the weapons I have (handheld) and there are no longer any issues so far with them. Thanks. Sorry for the difficulty. If this happens again with something else. I'll do the subbing thing first before submitting a bug.

**Comment by RavienGaming** [comment]
I am glad that fixed it! It's so weird though because normally if the scenario is showing Build 23 in-game then it should have updated all the files but sometimes Steam is Steam. I will go ahead and close this then. Thanks again for reporting it though.
