### ISSUE TITLE
Menu mistake in start mission

### ISSUE THREAD

**Issue by differential-faw** [RavienGaming/Reforged-Eden-2#374]
### Reforged Eden 2 Build Number

Na

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Told by prompt to manually hit box to left to complete a broken mission. That box doesn't work.... It should say hit box "above"
![Uploading 17312116750792215514266464301266.jpg…]()

**Comment by VermillionX** [comment]
That is not a screenshot. It's a link to this page.

**Comment by RavienGaming** [comment]
You can add screenshots by just dragging and dropping the image file into your message. Without a picture can't really see what you're talking about.
