### ISSUE TITLE
NPC POI teleporters getting people stuck

### ISSUE THREAD

**Issue by Neimoh** [RavienGaming/Reforged-Eden-2#376]
### Reforged Eden 2 Build Number

23

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

With the new tiered teleporters players have access to their range can exceed existing npc vanilla type trapping them in the station and they can't return to their base. This may be intentional or an oversight, but it's been a big issue on our server. Perhaps the tech tree can be reversed so the base teleporter can be edited as the top tier with max range and player crafted teleporters start at the reduced range, so all existing prefabs don't need modified and npc stations can have max range.

**Comment by RavienGaming** [comment]
This is working as intended in the scenario.

**Comment by RavienGaming** [comment]
I'll see about adding some type of popup or something to communicate to players that they use teleporters at their own risk and they should make sure they can return from where ever they are teleporting to. But in my experience nobody reads.
