### ISSUE TITLE
Zirax Missile Base Freight elevator door signal logic seems to be broken

### ISSUE THREAD

**Issue by suntrip76** [RavienGaming/Reforged-Eden-2#379]
### Reforged Eden 2 Build Number

B23

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

The signal logic to open the freight elevator door in the missile base seems to be broken. I have ran the POI several times without problems, but lately it has stopped working. I go to the B1 security office, I go to B2 security office. First Core + reactor have been blown up.
It was mentioned in the discord a few days ago that someone else had the problem and I have had it with two bases now.

Playfield info:
![billede](https://github.com/user-attachments/assets/6a786e90-7700-486a-a5b9-7efa8cf192b4)

### POI Name

R2BA_RadosMissileBaseT3S

**Comment by VermillionX** [comment]
Yes. It was reported days ago and already fixed for the next update.

**Comment by suntrip76** [comment]
Ah, I searched for it here but didn't find it so I posted it. Sorry for the duplicate.
