### ISSUE TITLE
Rogue start bridge info not up to date with changes to start

### ISSUE THREAD

**Issue by bld** [RavienGaming/Reforged-Eden-2#38]
### Reforged Eden 2 Build Number

3

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

It looks like the bridge information on the planet is from RE1, and isn't consistent with the changes for RE2. This includes:

Planetary Scan and Biological Report: 
- Cave worms are listed as hostile. They are passive, but the Argos are hostile (and as I recall were called Cave Worms in RE1). Argos are not listed.
- Gigas are not listed, though I did encounter them.

Damage report:
- Says "Interior weapon systems online", when the sentry turrets from RE1 have been removed.

![planetary_scan_lcd](https://github.com/RavienGaming/Reforged-Eden-2/assets/169479/d046313b-7580-4df7-bf70-c35e0c720d18)

![biological_report_lcd](https://github.com/RavienGaming/Reforged-Eden-2/assets/169479/acdea928-bdcf-4386-aea7-d3402fd639b7)

![damage_report_lcd](https://github.com/RavienGaming/Reforged-Eden-2/assets/169479/139f1889-f5ca-4a3a-8a69-8f31e2dc92cc)

### POI Name

Crshed Transport Front

### Playfield Name

Rogue PX-37

### Playfield Class

Dark Rogue Starter

### Star Name

Rogue System

### Star Class

RStartingSystem

### Game Seed

836262

**Comment by RavienGaming** [comment]
Thanks! Will fix this.

**Comment by RavienGaming** [comment]
Fixed in next update.
