### ISSUE TITLE
NullReferenceException When Entering Planet For The First Time

### ISSUE THREAD

**Issue by byo13** [RavienGaming/Reforged-Eden-2#381]
### Reforged Eden 2 Build Number

23

### Game mode

Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Sometimes, I get an error popup when entering a planet for the first time with a red NullReferenceException error. I will paste the relevant log messages in the next section.

### Error code from console or log (Optional)

13-15:02:55.829 12_02 -LOG- Loading playfield 'Dambup'
13-15:02:55.847 12_02 -LOG- RandomPlacer: StartBiome center: 0, 0, planet size class: 5
13-15:02:56.027 12_02 -LOG- [SSGUIPoi] RandomPlacer PlacePois: 44 of 274 POIs could not be placed: R2BA_RadosFuelDepotT1S (R2RadosAuxT1Snow), R2BA_RadosDefenseT1S (R2RadosDefenseT1Snow), R2BA_RadosDefenseT1S (R2RadosDefenseT1Snow), R2BA_RadosDefenseT1S (R2RadosDefenseT1Snow), R2BA_RadosDefenseT1S (R2RadosDefenseT1Snow), RE2_BA_RadosDecoMine07 (R2RadosDecoMining), RE2_BA_RadosDeco03 (R2RadosDecoMining), RE2_BA_RadosDeco03 (R2RadosDecoMining), RE2_BA_RadosDeco04 (R2RadosDeco), RE2_BA_RadosDeco04 (R2RadosDeco), R2BA_TalonMill03 (R2TalonSnow), R2BA_TalonStoragePit03 (R2TalonSnow), R2BA_TalonLumberCamp03 (R2TalonSnow), R2BA_TalonStoragePit03 (R2TalonSnow), R2BA_TalonMill03 (R2TalonSnow), R2BA_TalonFarmhouse12 (R2TalonSnowFarm), R2BA_TalonFarmhouse11 (R2TalonSnowFarm), R2BA_TalonFarmhouse13 (R2TalonSnowFarm), R2BA_TalonFarmhouse12 (R2TalonSnowFarm), R2BA_TalonFarmhouse13 (R2TalonSnowFarm), R2BA_TalonGuardTower03 (R2TalonDefenseSnow), R2BA_TalonGuardTower03 (R2TalonDefenseSnow), R2BA_TalonGuardTower03 (R2TalonDefenseSnow), R2BA_TalonGuardTower03 (R2TalonDefenseSnow), R2BA_TalonGuardTower03 (R2TalonDefenseSnow), R2BA_TalonGuardTower03 (R2TalonDefenseSnow), R2BA_TalonGuardTower03 (R2TalonDefenseSnow), R2BA_TalonMill03 (R2TalonSnow), R2BA_TalonStoragePit03 (R2TalonSnow), R2BA_TalonArcheryRange03 (R2TalonSnow), R2BA_TalonMarket03 (R2TalonSnow), R2BA_TalonLumberCamp03 (R2TalonSnow), R2BA_TalonRuinedHouse01 (R2TalonWoodRuin), R2BA_TalonRuinedHouse03 (R2TalonWoodRuin), R2BA_TalonRuinedHouse03 (R2TalonWoodRuin), R2BA_TalonRuinedHouse02 (R2TalonWoodRuin), R2BA_TalonRuinedHouse03 (R2TalonWoodRuin), R2BA_TalonRuinedHouse03 (R2TalonWoodRuin), R2BA_TalonRuinedHouse01 (R2TalonWoodRuin), R2BA_TalonRuinedHouse03 (R2TalonWoodRuin), R2BA_TalonRuinedHouse01 (R2TalonWoodRuin), R2BA_TalonRuinedHouse03 (R2TalonWoodRuin), R2BA_TalonRuinedHouse02 (R2TalonWoodRuin), R2BA_TalonRuinedHouse02 (R2TalonWoodRuin), 
13-15:02:56.208 12_02 -LOG- Creating and spawning 315 structures took 85ms
Total Presets:82
2151,976[Decoration] Request Reload COMPLETE
13-15:02:56.481 12_02 -LOG- Playfield 'Dambup' with type 'planet' class=5 and playfield seed 271836 loaded (651 ms)
[Decoration] Start Loading Deco Presets None
**NullReferenceException: Object reference not set to an instance of an object**
  at Assembly-CSharp.DialogFactory.FreeMenu (UnityEngine.Object ) [0x00106] in <97982ac660d64313a4f8e70c3a523117>:0 
  at Assembly-CSharp.WindowContext.Update () [0x000fc] in <97982ac660d64313a4f8e70c3a523117>:0 
  at GameStartup.Update () [0x00000] in <97982ac660d64313a4f8e70c3a523117>:0 

### Playfield Name

Dambup

### Playfield Class

Snow

### Star Name

Eurynachik

### Star Class

G

### Game Seed

249663

**Comment by RavienGaming** [comment]
This is likely a game bug and will need to be reproduced and reported using a vanilla save game.
When reproducing a game bug in a vanilla save, make sure you are using the same mode _(singleplayer/co-op/dedicated multiplayer, survival/creative)_ as what you were using when the issue happened in the scenario.
To see a list of known game bugs or to report a new one please see: https://empyriononline.com/forums/bugs.24/
