### ISSUE TITLE
Ch 6 Hostile Apparatus problem

### ISSUE THREAD

**Issue by curtnoel** [RavienGaming/Reforged-Eden-2#384]
### Reforged Eden 2 Build Number

23

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Main Story Mission...chapter 6 Lights Out  mainframe intrusion step
after you switch the circuit breaker the door to the checkpoint area closes and you cannot enter. Cant blow it up either.
I noticed the door was open when I arrived and it opens when I switch the breaker box back again

### Error code from console or log (Optional)

no error code

### POI Name

Zirax Communication Station

### Playfield Name

Akua Moon

### Playfield Class

Barren Moon

### Star Name

Alpha

### Star Class

G Starting System

### Mission Name

Ch 6 Hostile Apparatus

### Mission Objective

mainframe intrusion

### Game Seed

multiplayer...not sure

**Comment by VermillionX** [comment]
If you're on a server and someone does the POI before you and it hasn't regenerated, the door signal will be inverted.
As of build 23 (provided the POI has regenerated or it's a new save) there should be a console in the room before the incinerator that (if you are up to that part of the mission) will give you the option to manually toggle the signals being sent between the switches/sensors and the incinerator and its doors.

**Comment by curtnoel** [comment]
thx for reply! i will revisit it
