### ISSUE TITLE
QA: Dread start really sucks, please add hoverbike to starting equipment and more wrecks/structures

### ISSUE THREAD

**Issue by RedScourge** [RavienGaming/Reforged-Eden-2#385]
### Reforged Eden 2 Build Number

24

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

When you go to start a new playthrough of RE2 on Dread, you are started off in a bunker, the quest asks you to blow up cores from nearby NPC structures, however the NPC structures are several miles away from each other and impossible to spot from a distance due to the hilly terrain. You could end up running 40 km in order to advance through the quests.

Recommendations:
- Double the number of POIs and random junk structures (Playfields/Starter_Dread/playfield_static.yaml)
- Add hoverbike to starting inventory (add "PlayerBike," to Playfields/Starter_Dread/playfield_static.yaml:1352-1355)

### Error code from console or log (Optional)

N/A

### Playfield Name

Dread

### Playfield Class

Dead

### Star Name

Epsilon

### Star Class

MStartingSystem

### Mission Name

Intro: Dread

### Mission Objective

Repair IDA

**Comment by RedScourge** [comment]
I think there are probably enough of the little ruins that get scattered around the main POIs, but there are not enough POIs, so by the luck of the draw, you may simply be 10km away from the nearest cluster of ruins and POIs. This is especially notable in combination with not having a hoverbike because leveling up is VERY slow, and you can't even build a suitable HV until you at least get the quest rewarded XP from destroying 4 NPC cores.

I think I fixed this by doubling or tripling how many of the main POIs there are that all the smaller ruins cluster around in the config, like Eden_RuinsLogisticsAuxT1, Eden_Beacon, Eden_RuinsSpaceTether, Eden_RuinsSpaceRadar, Eden_RuinsCivilianMain, and Eden_RuinsMiningPit in playfield_static.yaml

**Comment by VermillionX** [comment]
It's supposed to suck.

**Comment by RedScourge** [comment]
In that case, please consider replacing "Difficulty: Hard" with "Experience: Unpleasant" in the start screen info, as these are two very different things. Someone who expects a difficult challenge is going to be disappointed when they realize what's really ahead of them is 4 hours of holding down the W key.
