### ISSUE TITLE
CV/Base small oxygen tank energy usage double that of large oxygen tank

### ISSUE THREAD

**Issue by bld** [RavienGaming/Reforged-Eden-2#386]
### Reforged Eden 2 Build Number

24

### Game mode

Creative

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

The CV/Base small oxygen tank uses 10W of power, while the large oxygen tank uses 5W. Seems like this should be reversed. I noticed that all 3 fuel tanks use 1W of power.

**Comment by VermillionX** [comment]
Fixed for next update
