### ISSUE TITLE
Radiation from Advanced Warp Drive

### ISSUE THREAD

**Issue by RStephenHauck** [RavienGaming/Reforged-Eden-2#387]
### Reforged Eden 2 Build Number

4545

### Game mode

Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

I have a CV with an advanced warp drive in an equipment bay.  The bay is encased in carbon blocks and heavy glass.  Airtight blocks all show green.  I have my cockpit directly above the bay and the drive happens to be just under the carbon block flooring of the cockpit.  Standing on this flooring I get 35 rads.  If I stand to the side, also 1 carbon block removed, I get 0.

**Comment by RStephenHauck** [comment]
Poor wording on my part.  Standing to the side of the bay 1 carbon block distance, not "removed".

**Comment by RStephenHauck** [comment]
Went into RE2 creative mode and re-created this so it may or may not be an issue regarding the blocks.  Have the area straddled by the heavy glass and otherwise covered by the plastic blocks.
![383120_286](https://github.com/user-attachments/assets/3555fe81-53b5-4e2c-995e-e79d27a6f528)

Back in the pressurized section, stand back from the overhang and all is well.

![383120_284](https://github.com/user-attachments/assets/83808997-9e49-4bf9-9f1a-3e7926637bfd)


Step up to the glass and the radiation is able to seep through that seam.

![383120_285](https://github.com/user-attachments/assets/156090ce-30b8-4e2e-9559-4b29b420c186)

I'll simply change the design to eliminate the seam and consider this resolved.

**Comment by VermillionX** [comment]
Radioactivity is not stopped by airtightness. It extends exactly 1 same-grid block in every direction from every block of a device. This cannot be changed, nor is it a bug. Same thing happens with heat-emitting blocks.
