### ISSUE TITLE
Oxygen depletion

### ISSUE THREAD

**Issue by RStephenHauck** [RavienGaming/Reforged-Eden-2#388]
### Reforged Eden 2 Build Number

4545

### Game mode

Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

On a planet without O2 and in an Abandoned Reactor which is pressurized (temp and radiation levels show normal).  However, suit still bleeds O2 and have to replenish with items in inventory.  Shouldn't pressurization include O2?

**Comment by VermillionX** [comment]
Airtight does not mean pressurized.

**Comment by RStephenHauck** [comment]
Ah, I was not aware of that.  Many thanks.  Portions of the Reactor do appear pressurized
![383120_283](https://github.com/user-attachments/assets/a382cd9d-ea3f-4133-98b8-eed423195a1a)
but other areas do not and still show ambient temperature.  Many thanks sir!  I will mark this closed.
