### ISSUE TITLE
light missile turret inconsistencies for base/cv

### ISSUE THREAD

**Issue by Tidal-Flame** [RavienGaming/Reforged-Eden-2#390]
### Reforged Eden 2 Build Number

2474

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

The tooltip for the modular block for Light Missile Turret (base) says the missile launcher uses 158mm Rolling Airframe. But when you place it, it uses 158mm laser guided. You have the same information mismatch on empyrionbuddy
https://empyrionbuddy.com/item/TurretBaseRocketBlocks 
https://empyrionbuddy.com/item/TurretBaseRocket
(I didn't test on vanilla as I saw a similar information mismatch from June using CV missile launcher, and figured it would be an RE2 thing)

**Comment by VermillionX** [comment]
Fixed for next update.
Both T1 and T2 missile turret parent block are using the CV info tag instead of the BA one.
