### ISSUE TITLE
some dronite rich asteroids are not targeted and also can not be mined manual

### ISSUE THREAD

**Issue by me777** [RavienGaming/Reforged-Eden-2#391]
### Reforged Eden 2 Build Number

24

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

in a rich asteroid field in drone space some of the dronite asteroids are not targeted and also can not be mined by controling the turret. (in contrast 2 out of the 4 groups worked)
![383120_6](https://github.com/user-attachments/assets/496adaf9-aeb5-4cb3-9937-a11ee8bacf60)

### POI Name

see screenshot of di

### Playfield Name

Lola

### Playfield Class

Rich Asteroid Field

### Star Name

Nouditar

### Star Class

M5

### Game Seed

1319838

**Comment by RavienGaming** [comment]
Did you try firing on the asteroid from a different angle? There's something funky that happens with blocks with large colliders where from some angles the colliders don't work right.

**Comment by me777** [comment]
went back and tried again:
The turrets still did not target the 2 groups. (i went all around the asteroids)
I did use the turrets manual from different angles and for really long, but it never "poped".
Also I did restart both the client and server.

**Comment by me777** [comment]
I can no longer load my savegame, so maybe those were early warnings of a currupted savegame?

**Comment by RavienGaming** [comment]
Maybe. I hope not. I will go ahead and close this issue then but please feel free to re-open it if it happens again.
