### ISSUE TITLE
Trader job asking for advanced CPU extender for a base does not accept the item

### ISSUE THREAD

**Issue by Xerkus** [RavienGaming/Reforged-Eden-2#393]
### Reforged Eden 2 Build Number

24

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Trader in `RBA_ZascosiumMinePolaris` gave supplies job asking for "x1 Advanced CPU Extender for a Base". However he does not accept advanced cpu extender that is `CPUExtenderBAT4R` in RE2 and I assume trader still expects RE/vanilla extender that is not available anymore.

### POI Name

RBA_ZascosiumMinePolaris

### Playfield Name

Yiadead

### Playfield Class

Lava

### Star Name

Ettidu

### Star Class

O1b

**Comment by VermillionX** [comment]
Fixed for next update
