### ISSUE TITLE
Com Relay 451 (intruders) has locked door, quest does not tell you its entry code

### ISSUE THREAD

**Issue by RedScourge** [RavienGaming/Reforged-Eden-2#394]
### Reforged Eden 2 Build Number

24

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Com Relay 451 (intruders part of story mission) has its entry door locked door, and the quest does not tell you its entry code. I had to god mode my way through, but other players on the server wont have that ability.

### Playfield Name

Roggery Sector

### Playfield Class

SpaceOrbitSectorStart

### Star Name

Beta

### Star Class

F

### Mission Name

Chapter 4: The Cruel Stars

### Mission Objective

Running Relays (451)

**Comment by RedScourge** [comment]
Turns out it does show in the PDA but I don't think it shows in the chat dialog like it does for the ones before it.

**Comment by VermillionX** [comment]
The coms chief says it before you reach the airlock. This is automatically transcribed to the PDA logs.
The code is in the PDA Objective description for both "Reach the Airlock" and "Enter Relay 451".
The code is in the PDA Logs for both "Reach the Airlock" and "Enter Relay 451".
It is therefore in the PDA six times.

**Comment by RedScourge** [comment]
I think I have figured out the problem: several dialog messages come up all at about the same time, so there is a good chance you never see the code be stated in the dialog, and then once you get near the door, the PDA entry that it gets stored under is the one that's previously completed, leading the player to believe that it just wasn't logged.
