### ISSUE TITLE
Project Eden Admin Panel on UCH ship opens an Imgur webpage instead of a photo

### ISSUE THREAD

**Issue by RedScourge** [RavienGaming/Reforged-Eden-2#395]
### Reforged Eden 2 Build Number

24

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

When accessing the Project Eden Admin Control Panel in the UCH ships and going to a few of the options, an image is supposed to be displayed, but instead an Imgur webpage is loaded featuring the image on the page. I think Imgur changed how they host files to discourage people from hotlinking right to the photo, so you'll probably have to move this to another place like somewhere inside the GitHub repo perhaps.

![scenario_admin_research_bug](https://github.com/user-attachments/assets/219ca431-47ed-4a2b-8885-6518d902a71a)

### POI Name

UCH Research Vessel

### Playfield Name

UCHN Explorer

### Star Name

Beta

**Comment by RavienGaming** [comment]
Thanks. Fixed for next update.
