### ISSUE TITLE
Gravity generator misses animation (works in vanilla)

### ISSUE THREAD

**Issue by Ente2k** [RavienGaming/Reforged-Eden-2#396]
### Reforged Eden 2 Build Number

24

### Game mode

Creative

### Tested in vanilla

Issue does not happen in vanilla

### Description of issue

The animation of the gravity gen misses in RE2, but works in Vanilla.
No idea whether that can be fixed, if not the issue can maybe at least serve to document the answer.

**Comment by RavienGaming** [comment]
Which specific gravity generator does this? There's like 8 different ones, do they all do it?

**Comment by Ente2k** [comment]
All of them miss the animation. CV and SV ones, too.

**Comment by RavienGaming** [comment]
Thanks. Looks like they need **Class: Generator** added to the configs to properly animate which makes... No sense. Thanks for reporting that.

**Comment by VermillionX** [comment]
Fixed for next update, I guess.
We use a lot of duct tape to get things to work, but this looks like Eleon using their own duct tape.
