### ISSUE TITLE
CV Manual Heavy Laser/Positron, Abusable bug.

### ISSUE THREAD

**Issue by ArtemisRouge** [RavienGaming/Reforged-Eden-2#40]
### Reforged Eden 2 Build Number

RE2 Build 3

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

CV Heavy Model Laser and Positron in RE2 can be completely buried or obstructed in armor and still function. Allowing the 360 degree armoring of either device w/ the ability to fire through your own hull. Ripe for abuse.

Did not work when tested on Medium manual laser. Did not test all other weapons.

**Comment by VermillionX** [comment]
Fixed in next update.
Seems to be a problem with hitscan beams and obstruction checking. Added an exclusion zone in front of the barrel of affected weapons so blocks can't be placed in the 1-block space directly in front of the barrel.
