### ISSUE TITLE
stuck on loading screen

### ISSUE THREAD

**Issue by Samuraikid11** [RavienGaming/Reforged-Eden-2#400]
### Reforged Eden 2 Build Number

12345

### Game mode

Survival

### Tested in vanilla

Issue does not happen in vanilla

### Description of issue

Reforged Eden frozen on Loading screen nothing myself or my friend does fixes it

### Error code from console or log (Optional)

Default

### Playfield Name

Akua

**Comment by Samuraikid11** [comment]
not sure if this helps?

13-23:02:34.122 18_02 -LOG- PfServer (PID 16264) disconnected, no playfield loaded

**Comment by RavienGaming** [comment]
Is this single player, coop, or a dedicated server?

**Comment by Samuraikid11** [comment]
i am running a server on nitrado i can give my config file if that might help?




________________________________

**Comment by Samuraikid11** [comment]
Just incase this might help.

[dedicated.zip](https://github.com/user-attachments/files/18132976/dedicated.zip)

**Comment by RavienGaming** [comment]
No the config won't help. This is likely either a problem with your server, or a problem with how you installed the scenario.
I'd recommend starting a new save game making sure to fully delete all the old save game + cache data on both server and clients, and use a new, unique save game name you've never used before while triple checking you followed all the directions on the RE2 workshop for setting up a server (such as making sure to rename the RE2 scenario folder).

Assuming you already tried all the other troubleshooting like restarting the server, validating files, etc.

I can't help much with server setup though. Kind of beyond my expertise.
