### ISSUE TITLE
Drone POI Brood Assembly spawns Zirax Soldiers

### ISSUE THREAD

**Issue by Ente2k** [RavienGaming/Reforged-Eden-2#401]
### Reforged Eden 2 Build Number

25

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

See screen:
![20241216181649_1](https://github.com/user-attachments/assets/b9add41d-0c44-448e-af44-c6f2992b7c3e)

Also: Proof the Drones work for the Zirax! Death to the Zirax Scum!

**Comment by Xerkus** [comment]
I noticed it in the swarm assembly `RE2_BAO_RogueT1_01` in the bottom core room. Probably all assemblies are affected via copy-paste

**Comment by RavienGaming** [comment]
Thanks. Fixed for next update.
