### ISSUE TITLE
Can not Jump to another system

### ISSUE THREAD

**Issue by Sparrownyx** [RavienGaming/Reforged-Eden-2#405]
### Reforged Eden 2 Build Number

25

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

we selected the System we wanted to make a jump to But it will not jump it does play the jump animation but does not do the jump and it takes the fuel from the ship. We also tried to warp to the sun then Jump to the system and again to another system and it still does not jump.

**Comment by RavienGaming** [comment]
Would need the star class(es) for the systems you tried to warp to.

Can you also provide the global game seed (should be in the server config) and the exact name of the star systems you can't warp to.
Thank you.

**Comment by Sparrownyx** [comment]
We reinstalled the scenario as we believed the whole files were corrupted
we couldnt select other planets when we started. and it was every system
around the original 3 systems. After reinstalled it it was working fine for
now. will keep you posted.

**Comment by RavienGaming** [comment]
Good to hear you figured it out though! I will close this but if you encounter any issues please feel free to open a new report.
Good luck!

**Comment by Sparrownyx** [comment]
Thank you and I will.
