### ISSUE TITLE
Decay gate core destroyed

### ISSUE THREAD

**Issue by WGN-RB** [RavienGaming/Reforged-Eden-2#406]
### Reforged Eden 2 Build Number

v 1.11.10 4546 24-04:16

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Went to the decay gate and did not see the console, did however see the core and blew it up by mistake. Now we cannot use the gate. Says cannot talk to npcs in player based structures after i put a core in,,,, then removed it, is there a way to reset that playfield or something i am missing? I thought that block was indestructable. console is gone as well. can still see the chat for it though

### Error code from console or log (Optional)

You cannot talk to npcs in player based structures

**Comment by RavienGaming** [comment]
The gate isn't working yet nor is the design for it complete. Progenitor space hasn't been setup so you're not missing much.

**Comment by WGN-RB** [comment]
Thanks for the response, good to know i did not mess it up for the rest of the guys. i was trying to set up the gate at the time but the console was small and hard to find,,,, thanks again
