### ISSUE TITLE
Desert Wasteland Custom Planet lacks Drone Base

### ISSUE THREAD

**Issue by Ishantil** [RavienGaming/Reforged-Eden-2#408]
### Reforged Eden 2 Build Number

25

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Desert Wasteland sounded like a cool planet to do a custom run on, noticed it lacks a Drone base, but had some Zirax assets on it.

### Playfield Class

Desert Wasteland

**Comment by RavienGaming** [comment]
Intended, but thanks for reporting. Not all planets will have a drone base. *edit* I assume you meant arid wasteland.

**Comment by Ishantil** [comment]
Ah, yeah, Arid Wasteland, yeah.  Wasn't sure if it was intended or not.  Cheers, Matt/Ishantil
