### ISSUE TITLE
RE2 Build 26 Magmacite Potential Issue - Hell Planets

### ISSUE THREAD

**Issue by StHotPants** [RavienGaming/Reforged-Eden-2#409]
### Reforged Eden 2 Build Number

RE2 Beta Build 26

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

I have checked 2 Hell planets in previously undiscovered stars post update to RE2 Build 26 on the Anvil server. 

Both Hell planets had zero instances of Magmacite on them. Every instance of a <Heat Signature> POI on or over lava turned out to be a crashed ship. 
<img width="1005" alt="image" src="https://github.com/user-attachments/assets/c5db3754-7a97-4b3c-9390-e1bd07f81413" />

**Comment by RavienGaming** [comment]
Did you double click the star before warping to it to verify it hadn't been visited yet?

**Comment by StHotPants** [comment]
> Did you double click the star before warping to it to verify it hadn't been visited yet?

Yes, received the red popup box that said I couldn't see any details on the star as it hasn't been visited yet for both systems. I was intentionally hunting magmacite and checking unknown stars only

**Comment by RavienGaming** [comment]
You may have to report this to the server admins then, as I checked and magmacite was spawning for me in-game and all the configs are set correctly.

**Comment by StHotPants** [comment]
> You may have to report this to the server admins then, as I checked and magmacite was spawning for me in-game and all the configs are set correctly.

Acknowledged. Thank you

**Comment by RavienGaming** [comment]
I will close this for now, but if it happens in single player in new star systems please feel free to bump it or open a new issue.
