### ISSUE TITLE
CV "Medium Blaster Cannon" emits particle FX regardless of damage state

### ISSUE THREAD

**Issue by Lithoboli** [RavienGaming/Reforged-Eden-2#42]
### Reforged Eden 2 Build Number

3

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

The "Medium Blaster Cannon" fixed CV weapon constantly emits grey smoke particles regardless of device health.

**Comment by RavienGaming** [comment]
Thank you! Fixed for the next update.
