### ISSUE TITLE
Starter Quest on Roggery not permitting use of minigun turret for completion

### ISSUE THREAD

**Issue by StHotPants** [RavienGaming/Reforged-Eden-2#43]
### Reforged Eden 2 Build Number

RE2 Build 3

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Starter Quest series on Roggery 5/10/2024. When doing the second state of the Polaris Trader quest by helping the downed freighter fend off attacks by the 3 Zirax bombers the quest does not update for the first objective "Take Control of the Diomese's turrets" when you manually command the Minigun turret. Quest does correctly update when you man the Flak turret. Both turrets record credit for shooting down the Zirax bombers

### POI Name

Ship Landing Site

### Playfield Name

Roggery

### Star Name

Beta

### Mission Name

Chapter 3: Plausible Deniability

### Mission Objective

Manual Control

### Game Seed

156035

**Comment by VermillionX** [comment]
The "Take control of the Diomese's turrets" is not required to complete to finish the objective. It functions as a marker to the location of one of the turrets.
