### ISSUE TITLE
Medium Modulated Laser Turrets (CV) Retrieve as Light Modulated Laser Turrets

### ISSUE THREAD

**Issue by StHotPants** [RavienGaming/Reforged-Eden-2#44]
### Reforged Eden 2 Build Number

RE2 Build 3

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

When retrieving (using an advanced multitool) a Medium Modulated Laser Turret (Visible - IR) it instead returned a Light Modulated Laser Turret

**Comment by RavienGaming** [comment]
Thanks fixed for next update!
