### ISSUE TITLE
PE devices can't be made in Unversal Constructor

### ISSUE THREAD

**Issue by Mario-Radinovic** [RavienGaming/Reforged-Eden-2#47]
### Reforged Eden 2 Build Number

RE2 Build 4

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Devices like Modulated Laser Turrets, Railgun Turrets and Hydroponics Bays can be made in Advanced Constructor but not in Universal Constructor

**Comment by RavienGaming** [comment]
Thanks I'll have to go through all of them and correctly set them!

**Comment by RavienGaming** [comment]
Fixed for next update.
