### ISSUE TITLE
Talon mission Sweep and Clear, delayed spawn of 4th Zirax trooper (also some mission text typos)

### ISSUE THREAD

**Issue by Stan2112** [RavienGaming/Reforged-Eden-2#48]
### Reforged Eden 2 Build Number

4

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Game spawned 3 Zirax troopers instead of 4 outside the Talon Ancient Tower.  Vermillion's guess that the one I shot as it spawned blocked the spawner for the second one seems correct.  Body decayed and 4th trooper showed up.  The mission dialog mentions one up on the roof blocking my exit, but all of them were at ground level.

Once the 4th trooper was killed, the troop transport spawned and brought 4 more just like it should have.
![Sweep Clear](https://github.com/RavienGaming/Reforged-Eden-2/assets/168505441/75582e01-8bea-4187-8940-85995fb31cad)

Part of the chief's speech when you return has some grammar issues.

![chiefspeech1](https://github.com/RavienGaming/Reforged-Eden-2/assets/168505441/90bea5d8-681f-42c9-99f3-ee31d3017165)

I'm thinking the first line should read:
"Following the defeat of the Legacy and their forced dormancy, the Zirax suffered the greatest, or possibly only, losses in the war."

![Kievespeech1](https://github.com/RavienGaming/Reforged-Eden-2/assets/168505441/05a1e60f-e82d-44fc-bec6-6d38e239bc7e)

There's an "@w4" towards the end for some reason

### POI Name

R2BA_TalonTowerStory

### Playfield Name

Akua

**Comment by VermillionX** [comment]
Fixed for next update.
Updated the tower with fancy visuals from the new effect projectors; split the spawner that spawned 2 zirax into 2 spawners spawning 1 zirax so it doesn't get hung up on blocked spawn areas.

Fixed dialog, probably. The `@w4` is a text command telling the dialog to Wait for 2 seconds before continuing on with the text. However, it doesn't like me and has a habit of ignoring the command.

Dialog lines changed to:
"Following the defeat of the Legacy and their forced dormancy; The Zirax who had suffered the greatest, or possibly only, losses in the war saw us Tal'on, centralized within the safety of the Federation's home systems, far from the frontlines, as cowards and not fit to rule..."
