### ISSUE TITLE
Universal Constructor missing many components

### ISSUE THREAD

**Issue by Nothemal** [RavienGaming/Reforged-Eden-2#49]
### Reforged Eden 2 Build Number

4

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Many compenents are missing from the Universal Constructor.  Possibly related to issue #47 
Here are some quick notes, but it needs to full look:
Advanced Electromanget
Gauss Rail
Industrial Fuel
Semiconductors
Quantum Computer
Small Advanced Focusing Lens
Large Advanced Focusing Lens
Industrial Cut Diamond
Advanced Power Regulator
Deutirium Fuel Cell
Tungsten Ingot
Plasma Coil
Suit Oxygen Refill
Dark Matter Pod
Dark Matter Container

**Comment by RavienGaming** [comment]
Yup same issue as #47 . Closing this one to clean up duplicates.
