### ISSUE TITLE
Chemmix Industrial trader has no dialog

### ISSUE THREAD

**Issue by Nothemal** [RavienGaming/Reforged-Eden-2#50]
### Reforged Eden 2 Build Number

5

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

No dialog at all (empty dialog box) and no trade options.

### Error code from console or log (Optional)

There was an error compiling the script, trying to compile again. If the error persists it will be issued again, if not please ignore the preceding error.
(78,32): error CS1002: ; expected
Error compiling dialogue logic in state 'TD_ChemicalPolaris_Start'

**Comment by VermillionX** [comment]
Related to the Starfreight services.
Fixed for next update, and solved another problem where the Starfreight services wouldn't recognize an active order from a factory.
