### ISSUE TITLE
Missing visuals for BA shields?

### ISSUE THREAD

**Issue by Stan2112** [RavienGaming/Reforged-Eden-2#51]
### Reforged Eden 2 Build Number

4

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Noticed a lack of dome shield visuals at a [Polaris] Vehicle Station (R2BA_PolarisVehicleBayT2).  Shield reads 100%.

![baseshield](https://github.com/RavienGaming/Reforged-Eden-2/assets/168505441/f57f8a64-8fa6-46f3-933f-f670bece64e4)

Found a second of the same POI on this planet, same lack of shield visuals.

Found same POI on a different planet (Alpha VII) and the shield visuals were present.

### POI Name

[Polaris] Vehicle Station (R2BA_PolarisVehicleBayT2)

### Playfield Name

Alpha III

### Playfield Class

Desert

**Comment by VermillionX** [comment]
This is the same game bug that plagues generator and shield generator animations. So it's a game bug that requires Eleon to fix.
If you hit a shield generator to trigger a damage state, it will correct itself... sometimes.

**Comment by RavienGaming** [comment]
I believe this game bug was fixed.
I will close it but please feel free to open a new issue if it's still happening.
