### ISSUE TITLE
SI Issues R2BAJ_CrashedShip06

### ISSUE THREAD

**Issue by Ishantil** [RavienGaming/Reforged-Eden-2#54]
### Reforged Eden 2 Build Number

Build 5

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

R2_BAJ_CrashedShip06 explodes into fragments when you remove a piece from one of the nacelles.

### POI Name

R2BAJ_CrashedShip06

**Comment by VermillionX** [comment]
Probably fixed in next update.

**Comment by Ishantil** [comment]
Awesome, thanks!

--------------------------------
Matthew D. Cleveland
