### ISSUE TITLE
Very-Berry Milkshake wrong status effect tooltip

### ISSUE THREAD

**Issue by Mario-Radinovic** [RavienGaming/Reforged-Eden-2#55]
### Reforged Eden 2 Build Number

RE2 Build 5

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Very-Berry Milkshake gives correct effects described in item description, but status effect tooltip is wrong (Saying Maximum health and movement speed)

**Comment by Stan2112** [comment]
![veryberry](https://github.com/RavienGaming/Reforged-Eden-2/assets/168505441/d7bfc2da-fff9-49f1-a70f-5277478d278c)

![veryberry2](https://github.com/RavienGaming/Reforged-Eden-2/assets/168505441/c6ea0d21-6f39-445e-96dd-b29dc1afc119)

I would prefer it to be like the RE1 Strawberry Milkshake given the choice, but either way, something doesn't match here.

**Comment by VermillionX** [comment]
Fixed for next update.
There are less special foods due to overlapping effects and because some conflict with other status effects, resulting in players using food/drink items and getting no buffs or losing a different status effect.
