### ISSUE TITLE
Polaris Mining Quartermaster: "If you see this dialogue please report this to the Reforged Eden 2 developers following the directions found on the workshop."

### ISSUE THREAD

**Issue by Jhoosier79** [RavienGaming/Reforged-Eden-2#56]
### Reforged Eden 2 Build Number

5

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Just doing what the Mining Quartermaster told me to. Foreman convo was fine.

![20240519231659_1](https://github.com/RavienGaming/Reforged-Eden-2/assets/130943415/06b2efb1-6d97-4eec-9032-c172d8c97cb4)

### POI Name

Polaris Mining Foreman

### Playfield Name

Idem Epsilon

### Playfield Class

EdenSpace_POI_MiningT4_1

### Star Name

Ithibur

### Star Class

M1Ia

### Game Seed

8675309

**Comment by StHotPants** [comment]
Happens with both the Commanding Officer and the Merchant on the Mining Foreman ship in the attached picture. All other details are the same as Jhoosier79's report including build

**Comment by RavienGaming** [comment]
Awesome thanks for the report!
