### ISSUE TITLE
CV Laser charges tooltips wrong

### ISSUE THREAD

**Issue by Grabber48** [RavienGaming/Reforged-Eden-2#57]
### Reforged Eden 2 Build Number

5

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

A little mistake I found, for the CV laser turrets light & medium, that I have, the descriptors on the 350 and 450 laser charges for my CV say for mobile platforms which I thought were HV's and the 400 and 500 charges say they are for warships but the base light laser descriptor calls for the 400 and the medium for 600, I haven't unlocked the laser turrets for base only the CV to make things more confusing.Sorry if I am making more work but I am having a lot of fun and have been able to work past these small inconveniences and take out the Zirax carrier around Akua and get some nice CPU upgrades and lots of rare ingots, onward and upward! 

### Playfield Name

Akua

**Comment by VermillionX** [comment]
I have no idea what you're saying.
There is an issue where the tooltip for the laser and plasma turrets calls for the wrong MW and MJ cell, while the weapon wants a different cell. However, there's nothing saying "mobile platform" in any laser or plasma weapon description at all.

Fixed the incorrect MW/MJ listed on the turret tooltip for next update.
