### ISSUE TITLE
Small plasma turbine power reduction doesn't match description

### ISSUE THREAD

**Issue by bld** [RavienGaming/Reforged-Eden-2#58]
### Reforged Eden 2 Build Number

5

### Game mode

Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

I added a small plasma turbine to a CV and noticed the power reduced by 200 W in the control panel. The description says it reduces power by 100 W.

**Comment by VermillionX** [comment]
Fixed for next update
