### ISSUE TITLE
Class 4 Mining Sites - Chromite mining byproduct

### ISSUE THREAD

**Issue by StHotPants** [RavienGaming/Reforged-Eden-2#59]
### Reforged Eden 2 Build Number

RE2 Build 5

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Quantity of raw Iron ore byproduct while mining Chromite Asteroids for the Mining Foreman quest giver seems excessive. Mining the 30k Chromite (5 Chromite Ore Shipments @ 6000 Chromite per shipment) resulted in approximately 40,000 raw iron ore. Took about 7-8 Chromite asteroids to complete the mission and if the normal asteroids result in approximately 4k ore yield then you might consider reducing the iron ore byproduct by roughly 30-50%. 

### POI Name

n/a

### Playfield Name

Mining Site - Class 4

### Playfield Class

Asteroid Field

### Mission Name

Chromite Mining

### Mission Objective

Return to Mining Foreman with 5 Chromite Ore Shipments

**Comment by RavienGaming** [comment]
Thanks, adjusted for next update.
