### ISSUE TITLE
Error after placing solar pannel

### ISSUE THREAD

**Issue by TnT4u** [RavienGaming/Reforged-Eden-2#60]
### Reforged Eden 2 Build Number

1.11.6 4471

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

I get an error pop up when ever I place the panel. I tried placing the capacitor then the panel and the panel then the capacitor and a panel by itself all instances result in an error. I thought initially it was that I had placed them inside a structure under the ground was the issue so I tried outside on the ground with no ground above and it happened there also. 

### Error code from console or log (Optional)

Exception on playfield 'OAVVO II': System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index

### Playfield Name

OAVVO II

### Playfield Class

Barren

### Star Name

Olev-erepte

### Star Class

K5

### Game Seed

243515

**Comment by RavienGaming** [comment]
Please provide the RE2 build number, not the game version.
Did you try restarting your game back to windows desktop?
I was not able to reproduce the issue.

**Comment by TnT4u** [comment]
Oh sorry, thought that was it, its build 5. Yes I've restarted back to desktop. I haven't verified game files though.

**Comment by RavienGaming** [comment]
Try validating files, and if that doesn't work try testing it in a new save game. If it works after validating or works in a new save then it's probably something corrupt with your save or a game bug.
It wouldn't be a scenario issue most likely, as solar works the same regardless of scenario.

**Comment by RavienGaming** [comment]
I'll go ahead and close this for now. If you or anyone else has the same issue again please open a **new** ticket.
