### ISSUE TITLE
Dense Ice - Decomposition Output

### ISSUE THREAD

**Issue by StHotPants** [RavienGaming/Reforged-Eden-2#63]
### Reforged Eden 2 Build Number

RE2 Build 5

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Currently Dense Ice mining results in a deconstructor breakdown of 2 deuterium, 1 coolant, 1 chemicals, 1 salt, and 1 helium. 
Recommend increasing the salt output to either be 2 or (preferred) 4 per dense ice deconstruction. 
Rationale: Salt is a primary, secondary, or tertiary ingredient in a number of food and medicine recipes that can only be found as an uncommon/rare byproduct of either specialty "dense ice" mining or as a byproduct on some planets/moons of terrain mining (usually on the way to get to an actual ore resource). 
Upping the dense ice deconstruction output of salt from 1 to 4 would, I believe, be a relatively balanced update reflecting a game period (mid to late game) where alternative sources of salt would be welcomed due to the inevitable downturn of mining (by this point in the game most players will likely be doing rich/dense, get ingredients from OPV salvage, or have autominers setup on resources.

### Playfield Class

Dense Ice Asteroid

**Comment by RavienGaming** [comment]
Thanks for the feedback. FYI I'm only using Github for reporting scenario issues not necessarily balance issues. For balancing and suggestions please continue to use discord or steam as I will see it there!

**Comment by RavienGaming** [comment]
Adjusted for next update though.
