### ISSUE TITLE
Inefficient Automated Asteroid Harvest Drill - Salvage/Decon

### ISSUE THREAD

**Issue by StHotPants** [RavienGaming/Reforged-Eden-2#64]
### Reforged Eden 2 Build Number

RE2 Build 5

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

In RE1 salvaging/deconstructing Inefficient Automated Asteroid Harvest Drills resulted in small quantities of silver and coolant. In RE2 there are no "special" ingredients in the salvage/deconstruction of these turrets (no palladium or coolant or <insert other component>. Is that intentional? 

### Playfield Class

Rich Asteroid (in Zirax Territory)

**Comment by RavienGaming** [comment]
Intended yes, you get a CV tool turret from them now.
These are going to be found on a lot more NPC vessels as there will now be NPC mining fleets mining normal asteroids too, so it would be too much if they gave those resources for deconstructing.
