### ISSUE TITLE
HV detector has less range than SV detector in atmosphere (said to be equalized some time ago?)

### ISSUE THREAD

**Issue by danielsolaro** [RavienGaming/Reforged-Eden-2#65]
### Reforged Eden 2 Build Number

5

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Both SV and HV detectors have 8km range, but in atmosphere they have different values. I remember a discussion on discord about making HV detector equal to SV detector, I'm assuming they were meant to have same values in atmo too?

**Comment by RavienGaming** [comment]
Fixed in latest update.
