### ISSUE TITLE
Wrong models for Shutter Windows (Large and Small)

### ISSUE THREAD

**Issue by TheRealKokoJacK** [RavienGaming/Reforged-Eden-2#69]
### Reforged Eden 2 Build Number

5

### Game mode

Survival, Creative, Single Player

### Tested in vanilla

Issue does not happen in vanilla

### Description of issue

Vertical (non-transparent) Shutter Windows (Large and Small) are using the transparent model.

**Comment by VermillionX** [comment]
There is no "non-transparent" shutter window. There's airtight and non-airtight.
The vanilla "airtight" ones use the non-airtight models because the windows themselves do not work. The shutters are on the wrong side and the window isn't a window.
So this is intended.

**Comment by TheRealKokoJacK** [comment]
Models in Vanilla: 
![Empyrion 2024-05-23 00-58-39](https://github.com/RavienGaming/Reforged-Eden-2/assets/22179445/e936510f-eff1-4bdf-90a2-15b483edbb72)
![Empyrion 2024-05-23 00-58-41](https://github.com/RavienGaming/Reforged-Eden-2/assets/22179445/55269370-4334-429a-bbcb-e08adba4d7e3)

Models in RE2:
![Empyrion 2024-05-23 00-59-47](https://github.com/RavienGaming/Reforged-Eden-2/assets/22179445/12f47de9-fd92-40d8-a15a-c5897ec388ef)
![Empyrion 2024-05-23 00-59-50](https://github.com/RavienGaming/Reforged-Eden-2/assets/22179445/7fa16049-7300-4265-a58d-1ec1c554c34d)
