### ISSUE TITLE
Constructor and Tech Tree Error

### ISSUE THREAD

**Issue by PaganSavage** [RavienGaming/Reforged-Eden-2#72]
### Reforged Eden 2 Build Number

6

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

In the tech tree the basic plasma turbine is locked and when you go into the large, advanced and universal constructor it is still locked. The problem is that the standard and advanced plasma turbines are not locked and can be constructed.

### Playfield Name

Lokayy Sector edenspaceG_orbit

### Playfield Class

Open Space

### Star Name

Naphatryu

### Star Class

G

### Game Seed

1934

**Comment by VermillionX** [comment]
Are you using a new/recent savegame, or the same one you've been using for over a month?

**Comment by RavienGaming** [comment]
I'm going to close this. If you have the issue again in a new save game please feel free to open a new ticket!

**Comment by PaganSavage** [comment]
Sorry fir not getting back to you sooner. Only get on weekends mostly. And
yes it was on a older save game sorry.
