### ISSUE TITLE
Polaris Mining Quartermaster (Report #56) still without dialogue

### ISSUE THREAD

**Issue by StHotPants** [RavienGaming/Reforged-Eden-2#75]
### Reforged Eden 2 Build Number

RE2 Build 7

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Issue identified in Report #56 not fixed with current Build 7 (I believe build 7 is after the bug report was identified as fixed). 

The Mining Quartermaster on the Mining Foreman ship is one of the randomly spawning ones in a planetary space sector. Not one of the Mining Foreman ships found in Polaris Asteroid fields.
![image](https://github.com/RavienGaming/Reforged-Eden-2/assets/169509491/9229adc2-4098-41d6-a092-86ad9571cb41)

### POI Name

Polaris Mining Foreman

### Playfield Name

DEQR 15472 I

### Playfield Class

Dead world orbit

### Star Name

Rhi Beta

### Star Class

D

### Game Seed

25781

**Comment by RavienGaming** [comment]
Thanks. Removed the mining foreman from spawning in normal orbits until I can remake the mining fleets better so this should be fixed for next update.
