### ISSUE TITLE
Turrets and Compact Shields not upgradeable with Multitool

### ISSUE THREAD

**Issue by Grabber48** [RavienGaming/Reforged-Eden-2#76]
### Reforged Eden 2 Build Number

7

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Can't upgrade compact shields or light turrets for SV or CV with multitool items are unlocked but says "not unlocked or doesn't exist". The upgrades don't exist in vanilla so can't be tested in vanilla. Most other items upgrade ok.

### Playfield Name

Akua

### Playfield Class

Temperate

### Star Name

Alpha

**Comment by RavienGaming** [comment]
Do the light turrets say on their tooltip that they can be upgraded to medium turrets? And how many medium weapons do you already have?

**Comment by Grabber48** [comment]
No and neither do medium ion thrusters but they can be upgraded with the multitool. The SV standard shield generator says it can be upgraded to advanced but it can't when tried. Its hard to know from playing RE 1 what is changed intentionally or accidentally missed when things are different from what your used to. On my CV I have 4 medium turrets and 2 light turrets well below maximum.
-------- Original message --------From: RavienGaming ***@***.***> Date: 2024-05-26  8:25 p.m.  (GMT-05:00) To: RavienGaming/Reforged-Eden-2 ***@***.***> Cc: Grabber48 ***@***.***>, Author ***@***.***> Subject: Re: [RavienGaming/Reforged-Eden-2] Turrets and Compact Shields not upgradeable with Multitool (Issue #76) 
Do the light turrets say on their tooltip that they can be upgraded to medium turrets?

**Comment by RavienGaming** [comment]
Do you also have medium fixed weapons? The game will not let you upgrade any block if that upgrade would put you over the block limit, even if you're upgrading say a shield generator the game counts an upgrade as "adding a new block" for the limits. It's not smart enough to know that you're upgrading a block in-place, not adding a new one.

**Comment by Grabber48** [comment]
> Do you also have medium fixed weapons? The game will not let you upgrade any block if that upgrade would put you over the block limit, even if you're upgrading say a shield generator the game counts an upgrade as "adding a new block" for the limits. It's not smart enough to know that you're upgrading a block in-place, not adding a new one.

On SV have 1 small gatling turret and 4 ligh laser cannons block count 419.

On CV 2 light laser turrets, 2 medium laser turrets, 2 medium missile turrets, 2 medium plasma turrets and 2 light ship cannons, 5 sentries  block count 425. Still able to upgrade thrusters, blocks and constructors on both small ships..

Also have a captured base I can't upgrade the light gatling turrets on also just a complexity 1

**Comment by VermillionX** [comment]
Fixed for next update.
