### ISSUE TITLE
Unstable Warp Core POI Broken

### ISSUE THREAD

**Issue by Kainne00** [RavienGaming/Reforged-Eden-2#78]
### Reforged Eden 2 Build Number

Build 7

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Tested against 3 different Unstable Warp Core POIs in Single Player survival.  The POIs had not been touched by any other player (or myself) prior to attempt.  

When approaching the 'safe' side and interacting with the console w/yellow marker over it, the message popup reads as follows and cannot be further interacted with to complete the POI/event.
![UWC](https://github.com/RavienGaming/Reforged-Eden-2/assets/168397912/7f7a3f68-c487-48d5-ba15-1c28ad2a49a1)

### Error code from console or log (Optional)

Console output as follows: 
![uwc2](https://github.com/RavienGaming/Reforged-Eden-2/assets/168397912/d32625f1-1d15-4dbc-8a1b-d0de13969cd9)

Effectively the console may be trying to trigger something the game doesn't know how to handle via signal logic in SP.

### POI Name

Unstable Warp Core

### Playfield Name

Every playfiel it spawns

### Playfield Class

Space

### Star Name

N/A

### Star Class

N/A

### Mission Name

N/A

### Mission Objective

N/A

### Game Seed

765063

**Comment by RavienGaming** [comment]
Thanks for reporting this. It seems the signals on the blueprint are broken so I will have to redo all the signal logic for it.
