### ISSUE TITLE
SV Homing Missile Launcher doesn't keep firing when you hold down the fire button

### ISSUE THREAD

**Issue by Ente2k** [RavienGaming/Reforged-Eden-2#80]
### Reforged Eden 2 Build Number

8

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

The SV Medium Homing Missile Launcher will only fire a single round when you hold down the fire button and then stops. Need to perma-click which is annoying.

**Comment by VermillionX** [comment]
That's not really a bug. But okay, changed for next update.
