### ISSUE TITLE
Purgatory start: only Supply Cache that contains Iron Ore spawned 3km away from Cryo bunker

### ISSUE THREAD

**Issue by Mario-Radinovic** [RavienGaming/Reforged-Eden-2#81]
### Reforged Eden 2 Build Number

RE2 Build 8

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

On purgatory start I failed to find any iron ore or any way to make portable constructor.
Considering how low range of hand detector is, it is very unlikely that player would be able to find a Supply Cache that is almost 3km away from starting area (one that contained 20 iron ore).

### Playfield Name

Purgatory

### Game Seed

707027

**Comment by RavienGaming** [comment]
You get a constructor in one of the first supply caches you visit, as well as several more so you have extras. The loot is predetermined based on how many caches you have opened so you'll always get the same loot in the same order.
If you had respawned on the starter planet at a later time you cannot obtain the cache rewards again however so I recommend keeping a ship or base with some supplies on the planet in case you need to respawn there for some reason.

FYI you need to access the large cargo box on the cache to obtain the loot. The little cargo boxes just have random cargo box loot. There are several supply caches within handheld detector or visual range of the cryobunker.
