### ISSUE TITLE
Rogue Starter Planet: Missing starter gear cargo box in Armory

### ISSUE THREAD

**Issue by Bjornkarl249** [RavienGaming/Reforged-Eden-2#82]
### Reforged Eden 2 Build Number

8

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

The cargo box containing the rogue planet starting gear is missing from the armory. This issue is present on both rogue starting planets.

### POI Name

Crashed Transport Front

### Playfield Name

1) Rogue PX-37	2) Rogue J-5565

### Playfield Class

1) Dark Rogue Starter	2) Rogue Starter

### Star Name

1) Rogue System		2) Epsilon

### Star Class

1) RStartingSystem		2) MStartingSystem

### Mission Name

Intro: Rogue Planet

### Mission Objective

Find the Armory

### Game Seed

1) 611640	2) 979178

**Comment by Ishantil** [comment]
I can confirm this happened to us one Dark Rogue

**Comment by RavienGaming** [comment]
Fixed in next update thanks!
