### ISSUE TITLE
Polaris OPV with Zirax Affiliation Patrolling Polaris Planetary Territory

### ISSUE THREAD

**Issue by Lithoboli** [RavienGaming/Reforged-Eden-2#84]
### Reforged Eden 2 Build Number

8

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

A Zirax-controlled Kellen-Class OPV was present patrolling a Polaris POI cluster on a Desert planet, specifically a 2019 custom planet challenge finalist.
![20240602143706_1](https://github.com/RavienGaming/Reforged-Eden-2/assets/168792982/799df346-81bc-43ab-aa2d-9fd5ae5bacf0)

### POI Name

R2OPV_PolarisCorvette01

### Playfield Name

Reputistel

### Playfield Class

Desert

### Star Name

Valethe

### Star Class

A

### Game Seed

2051342

**Comment by RavienGaming** [comment]
Thanks fixed in next update.
