### ISSUE TITLE
Zirax Soldiers Spawning on Nascent Moons in Polaris Territory

### ISSUE THREAD

**Issue by michael-harris** [RavienGaming/Reforged-Eden-2#85]
### Reforged Eden 2 Build Number

8

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

There are zirax soldiers and ripperdogs on Nascent moons running around on the surface despite there being no Zirax structures on the playfield.  This seems odd also because there is no other Zirax presence in Polaris Space.

**Comment by RavienGaming** [comment]
Fixed next update thanks!
