### ISSUE TITLE
Zirax Soldiers spawning on Lava Nascent Planets in Polaris Space

### ISSUE THREAD

**Issue by michael-harris** [RavienGaming/Reforged-Eden-2#86]
### Reforged Eden 2 Build Number

8

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

There are zirax soldiers and mechs on Nascent moons running around on the surface despite there being no Zirax structures on the playfield.  This seems odd also because there is no other Zirax presence in Polaris Space.

**Comment by RavienGaming** [comment]
Thanks fixed for the next update.
