### ISSUE TITLE
Zascosium asteroids seem EXTREMELY rare compared to RE1 in Polaris space

### ISSUE THREAD

**Issue by michael-harris** [RavienGaming/Reforged-Eden-2#88]
### Reforged Eden 2 Build Number

8

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

When exploring Polaris space I have only found one hot star with one zascosium asteroid despite having visited around 30 stars at this point.  The previous playthru was the same experience.  Not sure if this is intended (in which case, perhaps the PDA should be updated?) or not, but I wanted to let you know.

**Comment by RavienGaming** [comment]
Same chances as RE1. 20%.
