### ISSUE TITLE
Orbital Alloy Smeltery does not require Refinery License

### ISSUE THREAD

**Issue by Nothemal** [RavienGaming/Reforged-Eden-2#89]
### Reforged Eden 2 Build Number

8

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

The Orbital Alloy Smeltery (Polaris) 'Eden_BAO_PolAlloy' has LCDs saying the Refinery License is required, but does not check for that.  Was able to refine ore without ever having the license.

**Comment by RavienGaming** [comment]
Thanks fixed for next update.
