### ISSUE TITLE
SV Hyperlasers do much more damage against turrets then the other SV heavy weapons.

### ISSUE THREAD

**Issue by Ente2k** [RavienGaming/Reforged-Eden-2#90]
### Reforged Eden 2 Build Number

8

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Tested different SV heavy weapons against turrets, the Hyperlasers do about double the damage of plasma and 30mm Vulcan. And apparently still 1.5 times the damage of the rails. Which seems way overpowered for them.
Might be turrets count as devices for their bonus. Or its the old bug where lasers do triple damage.

**Comment by VermillionX** [comment]
Tested. They do the exact amount of damage they say. 2222 damage per hit.

**Comment by RavienGaming** [comment]
I will close this for now but please open a new issue if something happens again.

**Comment by Ente2k** [comment]
Well if they do the intended dpmI would ask why that intended dpm is 2x that of plasma/GAU/rails VS. Turrets?
