### ISSUE TITLE
CV Standard Shield not upgradeable to Advanced Shield

### ISSUE THREAD

**Issue by danielsolaro** [RavienGaming/Reforged-Eden-2#93]
### Reforged Eden 2 Build Number

8

### Game mode

Survival, Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Upgrades unlocked in the tree, still doesn't show when multitool is in hands.
![20240603002124_1](https://github.com/RavienGaming/Reforged-Eden-2/assets/8516353/cde5c493-0339-49cb-a626-27a835b0fa96)

**Comment by RavienGaming** [comment]
Duplicate of #21
