### ISSUE TITLE
Zirax ground troops spawn on Frozen Inferno Planet in Colonists territory

### ISSUE THREAD

**Issue by Mario-Radinovic** [RavienGaming/Reforged-Eden-2#95]
### Reforged Eden 2 Build Number

RE2 Build 8

### Game mode

Survival

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Zirax Troops spawn in Colonists territory on Frozen Inferno planet (Glacier Snow biome)

### Playfield Class

Frozen Inferno

**Comment by Mario-Radinovic** [comment]
Update: Found them in Build 9 in Dunes biome as well (Frozen Inferno planet type - Polaris territory this time)

**Comment by RavienGaming** [comment]
Thanks fixed for next update.
