### ISSUE TITLE
New game scenario page still has Alpha in title

### ISSUE THREAD

**Issue by Mario-Radinovic** [RavienGaming/Reforged-Eden-2#97]
### Reforged Eden 2 Build Number

RE2 Build 10

### Game mode

Survival, Creative, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

![20240607141648_1](https://github.com/RavienGaming/Reforged-Eden-2/assets/65545773/ce0122d8-e141-4f8e-a5fd-dd94dda90100)

**Comment by RavienGaming** [comment]
Thanks this should be fixed in the latest update once Steam downloads the update to your PC.
