### ISSUE TITLE
Omicron Biome Dirt is graphite

### ISSUE THREAD

**Issue by Kainne00** [RavienGaming/Reforged-Eden-2#98]
### Reforged Eden 2 Build Number

10

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

On Omicron in the "Cactus" Biome, the surface dirt appears as standard brown dirt/sand for the planet. All normal.

the instant it is marred from a drill or salvage tool, the top layer is revealed with the dark gray graphite texture and mines out as graphite for the entire surface of the biome.

This may be intended, but seems like it is unintentional.

### Error code from console or log (Optional)

N/A

### POI Name

n/a

### Playfield Name

Omicron

### Playfield Class

Desert Starter

### Star Name

Beta

### Mission Name

N/A

### Mission Objective

N/A

### Game Seed

UNK

**Comment by RavienGaming** [comment]
Thanks I will get that fixed!
